/* contacts-esd-setup.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-esd-setup.vala, do not modify */

/*
 * This code is ported to Vala from evolution with this license:
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with the program; if not, see <http://www.gnu.org/licenses/>
 *
 */
/* FIXME: the async bindings seem to be broken for this function.*/

#include <gtk/gtk.h>
#include <libedataserver/libedataserver.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <libedataserverui/libedataserverui.h>
#include <glib-object.h>
#include <glib/gi18n-lib.h>
#include <goa/goa.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;
typedef struct _ContactsOnCredentialsRequiredData ContactsOnCredentialsRequiredData;
typedef struct _ContactsOnSourceTrustPromptHasRunData ContactsOnSourceTrustPromptHasRunData;

struct _Block1Data {
	int _ref_count_;
	ESource* source;
	gpointer _async_data_;
};

struct _ContactsOnCredentialsRequiredData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ESource* source;
	ESourceCredentialsReason reason;
	gchar* cert_pem;
	GTlsCertificateFlags cert_errors;
	GError* err;
	Block1Data* _data1_;
	ECredentialsPrompter* _tmp0_;
	gboolean _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	ECredentialsPrompter* _tmp7_;
	GtkWindow* _tmp8_;
};

struct _ContactsOnSourceTrustPromptHasRunData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ESource* source;
	GAsyncResult* res;
	GError* e;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GError* _tmp2_;
	const gchar* _tmp3_;
	GError* _vala1_e;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GError* _tmp6_;
	const gchar* _tmp7_;
	GError* _inner_error0_;
};

extern ESourceRegistry* contacts_eds_source_registry;
ESourceRegistry* contacts_eds_source_registry = NULL;
extern ECredentialsPrompter* contacts_eds_credentials_prompter;
ECredentialsPrompter* contacts_eds_credentials_prompter = NULL;

void e_trust_prompt_run_for_source (GtkWindow* parent,
                                    ESource* source,
                                    const gchar* certificate_pem,
                                    GTlsCertificateFlags certificate_errors,
                                    const gchar* error_text,
                                    gboolean allow_source_save,
                                    GCancellable* cancellable,
                                    GAsyncReadyCallback callback,
                                    gpointer callback_target);
gboolean e_trust_prompt_run_for_source_finish (ESource* source,
                                               GAsyncResult* _result_,
                                               ETrustPromptResponse* response,
                                               GError** error);
gboolean contacts_ensure_eds_accounts (gboolean allow_interaction);
static void _g_object_unref0_ (gpointer var);
static inline void _g_list_free__g_object_unref0_ (GList* self);
static void __lambda4_ (ESource* src,
                 ESourceCredentialsReason reason,
                 const gchar* cert_pem,
                 GTlsCertificateFlags cert_err,
                 GError* err);
void contacts_on_credentials_required (ESource* source,
                                       ESourceCredentialsReason reason,
                                       const gchar* cert_pem,
                                       GTlsCertificateFlags cert_errors,
                                       GError* err,
                                       GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
void contacts_on_credentials_required_finish (GAsyncResult* _res_);
static void ___lambda4__e_source_registry_credentials_required (ESourceRegistry* _sender,
                                                         ESource* source,
                                                         ESourceCredentialsReason reason,
                                                         const gchar* certificate_pem,
                                                         GTlsCertificateFlags certificate_errors,
                                                         GError* op_error,
                                                         gpointer self);
static void contacts_on_credentials_required_data_free (gpointer _data);
static gboolean contacts_on_credentials_required_co (ContactsOnCredentialsRequiredData* _data_);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void ___lambda5_ (Block1Data* _data1_,
                  GObject* obj,
                  GAsyncResult* res);
void contacts_on_source_trust_prompt_has_run (ESource* source,
                                              GAsyncResult* res,
                                              GAsyncReadyCallback _callback_,
                                              gpointer _user_data_);
void contacts_on_source_trust_prompt_has_run_finish (GAsyncResult* _res_);
static void ____lambda5__gasync_ready_callback (GObject* source_object,
                                         GAsyncResult* res,
                                         gpointer self);
static void contacts_on_source_trust_prompt_has_run_data_free (gpointer _data);
static gboolean contacts_on_source_trust_prompt_has_run_co (ContactsOnSourceTrustPromptHasRunData* _data_);
static void contacts_on_source_trust_prompt_has_run_ready (GObject* source_object,
                                                    GAsyncResult* _res_,
                                                    gpointer _user_data_);
gboolean contacts_has_goa_account (void);
gboolean contacts_esource_uid_is_google (const gchar* uid);
gchar* contacts_lookup_esource_name_by_uid (const gchar* uid);
gchar* contacts_lookup_esource_name_by_uid_for_contact (const gchar* uid);
GtkImage* contacts_get_icon_for_goa_account (const gchar* goa_id);

static gpointer
_g_object_ref0 (gpointer self)
{
#line 47 "../src/contacts-esd-setup.vala"
	return self ? g_object_ref (self) : NULL;
#line 162 "contacts-esd-setup.c"
}

static void
_g_object_unref0_ (gpointer var)
{
#line 50 "../src/contacts-esd-setup.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 170 "contacts-esd-setup.c"
}

static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
#line 50 "../src/contacts-esd-setup.vala"
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
#line 178 "contacts-esd-setup.c"
}

static void
__lambda4_ (ESource* src,
            ESourceCredentialsReason reason,
            const gchar* cert_pem,
            GTlsCertificateFlags cert_err,
            GError* err)
{
#line 66 "../src/contacts-esd-setup.vala"
	g_return_if_fail (src != NULL);
#line 66 "../src/contacts-esd-setup.vala"
	g_return_if_fail (cert_pem != NULL);
#line 66 "../src/contacts-esd-setup.vala"
	g_return_if_fail (err != NULL);
#line 67 "../src/contacts-esd-setup.vala"
	contacts_on_credentials_required (src, reason, cert_pem, cert_err, err, NULL, NULL);
#line 196 "contacts-esd-setup.c"
}

static void
___lambda4__e_source_registry_credentials_required (ESourceRegistry* _sender,
                                                    ESource* source,
                                                    ESourceCredentialsReason reason,
                                                    const gchar* certificate_pem,
                                                    GTlsCertificateFlags certificate_errors,
                                                    GError* op_error,
                                                    gpointer self)
{
#line 66 "../src/contacts-esd-setup.vala"
	__lambda4_ (source, reason, certificate_pem, certificate_errors, op_error);
#line 210 "contacts-esd-setup.c"
}

gboolean
contacts_ensure_eds_accounts (gboolean allow_interaction)
{
	ESourceRegistry* _tmp0_;
	ESourceRegistry* _tmp7_;
	ECredentialsPrompter* _tmp8_;
	ESourceCredentialsProvider* credentials_provider = NULL;
	ECredentialsPrompter* _tmp10_;
	ESourceCredentialsProvider* _tmp11_;
	ESourceCredentialsProvider* _tmp12_;
	ESourceRegistry* _tmp13_;
	GList* _tmp14_;
	ESourceRegistry* _tmp19_;
	GList* _tmp20_;
	ESourceRegistry* _tmp31_;
	ECredentialsPrompter* _tmp32_;
	GError* _inner_error0_ = NULL;
	gboolean result = FALSE;
#line 29 "../src/contacts-esd-setup.vala"
	_tmp0_ = contacts_eds_source_registry;
#line 29 "../src/contacts-esd-setup.vala"
	if (_tmp0_ != NULL) {
#line 30 "../src/contacts-esd-setup.vala"
		result = TRUE;
#line 30 "../src/contacts-esd-setup.vala"
		return result;
#line 239 "contacts-esd-setup.c"
	}
	{
		ESourceRegistry* _tmp1_ = NULL;
		ESourceRegistry* _tmp2_;
		ESourceRegistry* _tmp3_;
#line 36 "../src/contacts-esd-setup.vala"
		_tmp2_ = e_source_registry_new_sync (NULL, &_inner_error0_);
#line 36 "../src/contacts-esd-setup.vala"
		_tmp1_ = _tmp2_;
#line 36 "../src/contacts-esd-setup.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 251 "contacts-esd-setup.c"
			goto __catch0_g_error;
		}
#line 36 "../src/contacts-esd-setup.vala"
		_tmp3_ = _tmp1_;
#line 36 "../src/contacts-esd-setup.vala"
		_tmp1_ = NULL;
#line 36 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (contacts_eds_source_registry);
#line 36 "../src/contacts-esd-setup.vala"
		contacts_eds_source_registry = _tmp3_;
#line 35 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (_tmp1_);
#line 264 "contacts-esd-setup.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp4_;
		const gchar* _tmp5_;
#line 35 "../src/contacts-esd-setup.vala"
		e = _inner_error0_;
#line 35 "../src/contacts-esd-setup.vala"
		_inner_error0_ = NULL;
#line 38 "../src/contacts-esd-setup.vala"
		_tmp4_ = e;
#line 38 "../src/contacts-esd-setup.vala"
		_tmp5_ = _tmp4_->message;
#line 38 "../src/contacts-esd-setup.vala"
		g_warning ("contacts-esd-setup.vala:38: Couldn't load EDS SourceRegistry: %s", _tmp5_);
#line 39 "../src/contacts-esd-setup.vala"
		result = FALSE;
#line 39 "../src/contacts-esd-setup.vala"
		_g_error_free0 (e);
#line 39 "../src/contacts-esd-setup.vala"
		return result;
#line 288 "contacts-esd-setup.c"
	}
	__finally0:
#line 35 "../src/contacts-esd-setup.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 293 "contacts-esd-setup.c"
		gboolean _tmp6_ = FALSE;
#line 35 "../src/contacts-esd-setup.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 35 "../src/contacts-esd-setup.vala"
		g_clear_error (&_inner_error0_);
#line 35 "../src/contacts-esd-setup.vala"
		return _tmp6_;
#line 301 "contacts-esd-setup.c"
	}
#line 42 "../src/contacts-esd-setup.vala"
	_tmp7_ = contacts_eds_source_registry;
#line 42 "../src/contacts-esd-setup.vala"
	_tmp8_ = e_credentials_prompter_new (_tmp7_);
#line 42 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (contacts_eds_credentials_prompter);
#line 42 "../src/contacts-esd-setup.vala"
	contacts_eds_credentials_prompter = _tmp8_;
#line 44 "../src/contacts-esd-setup.vala"
	if (!allow_interaction) {
#line 313 "contacts-esd-setup.c"
		ECredentialsPrompter* _tmp9_;
#line 45 "../src/contacts-esd-setup.vala"
		_tmp9_ = contacts_eds_credentials_prompter;
#line 45 "../src/contacts-esd-setup.vala"
		e_credentials_prompter_set_auto_prompt (_tmp9_, FALSE);
#line 319 "contacts-esd-setup.c"
	}
#line 47 "../src/contacts-esd-setup.vala"
	_tmp10_ = contacts_eds_credentials_prompter;
#line 47 "../src/contacts-esd-setup.vala"
	_tmp11_ = e_credentials_prompter_get_provider (_tmp10_);
#line 47 "../src/contacts-esd-setup.vala"
	_tmp12_ = _g_object_ref0 (_tmp11_);
#line 47 "../src/contacts-esd-setup.vala"
	credentials_provider = _tmp12_;
#line 50 "../src/contacts-esd-setup.vala"
	_tmp13_ = contacts_eds_source_registry;
#line 50 "../src/contacts-esd-setup.vala"
	_tmp14_ = e_source_registry_list_sources (_tmp13_, NULL);
#line 333 "contacts-esd-setup.c"
	{
		GList* source_collection = NULL;
		GList* source_it = NULL;
#line 50 "../src/contacts-esd-setup.vala"
		source_collection = _tmp14_;
#line 50 "../src/contacts-esd-setup.vala"
		for (source_it = source_collection; source_it != NULL; source_it = source_it->next) {
#line 341 "contacts-esd-setup.c"
			ESource* _tmp15_;
			ESource* source = NULL;
#line 50 "../src/contacts-esd-setup.vala"
			_tmp15_ = _g_object_ref0 ((ESource*) source_it->data);
#line 50 "../src/contacts-esd-setup.vala"
			source = _tmp15_;
#line 348 "contacts-esd-setup.c"
			{
				ESource* _tmp16_;
#line 52 "../src/contacts-esd-setup.vala"
				_tmp16_ = source;
#line 52 "../src/contacts-esd-setup.vala"
				if (!e_source_has_extension (_tmp16_, E_SOURCE_EXTENSION_ADDRESS_BOOK)) {
#line 355 "contacts-esd-setup.c"
					ECredentialsPrompter* _tmp17_;
					ESource* _tmp18_;
#line 53 "../src/contacts-esd-setup.vala"
					_tmp17_ = contacts_eds_credentials_prompter;
#line 53 "../src/contacts-esd-setup.vala"
					_tmp18_ = source;
#line 53 "../src/contacts-esd-setup.vala"
					e_credentials_prompter_set_auto_prompt_disabled_for (_tmp17_, _tmp18_, TRUE);
#line 364 "contacts-esd-setup.c"
				}
#line 50 "../src/contacts-esd-setup.vala"
				_g_object_unref0 (source);
#line 368 "contacts-esd-setup.c"
			}
		}
#line 50 "../src/contacts-esd-setup.vala"
		(source_collection == NULL) ? NULL : (source_collection = (_g_list_free__g_object_unref0_ (source_collection), NULL));
#line 373 "contacts-esd-setup.c"
	}
#line 58 "../src/contacts-esd-setup.vala"
	_tmp19_ = contacts_eds_source_registry;
#line 58 "../src/contacts-esd-setup.vala"
	_tmp20_ = e_source_registry_list_sources (_tmp19_, E_SOURCE_EXTENSION_ADDRESS_BOOK);
#line 379 "contacts-esd-setup.c"
	{
		GList* source_collection = NULL;
		GList* source_it = NULL;
#line 58 "../src/contacts-esd-setup.vala"
		source_collection = _tmp20_;
#line 58 "../src/contacts-esd-setup.vala"
		for (source_it = source_collection; source_it != NULL; source_it = source_it->next) {
#line 387 "contacts-esd-setup.c"
			ESource* _tmp21_;
			ESource* source = NULL;
#line 58 "../src/contacts-esd-setup.vala"
			_tmp21_ = _g_object_ref0 ((ESource*) source_it->data);
#line 58 "../src/contacts-esd-setup.vala"
			source = _tmp21_;
#line 394 "contacts-esd-setup.c"
			{
				ESource* cred_source = NULL;
				ESourceCredentialsProvider* _tmp22_;
				ESource* _tmp23_;
				ESource* _tmp24_;
				gboolean _tmp25_ = FALSE;
				ESource* _tmp26_;
#line 59 "../src/contacts-esd-setup.vala"
				_tmp22_ = credentials_provider;
#line 59 "../src/contacts-esd-setup.vala"
				_tmp23_ = source;
#line 59 "../src/contacts-esd-setup.vala"
				_tmp24_ = e_source_credentials_provider_ref_credentials_source (_tmp22_, _tmp23_);
#line 59 "../src/contacts-esd-setup.vala"
				cred_source = _tmp24_;
#line 60 "../src/contacts-esd-setup.vala"
				_tmp26_ = cred_source;
#line 60 "../src/contacts-esd-setup.vala"
				if (_tmp26_ != NULL) {
#line 414 "contacts-esd-setup.c"
					ESource* _tmp27_;
					ESource* _tmp28_;
#line 60 "../src/contacts-esd-setup.vala"
					_tmp27_ = source;
#line 60 "../src/contacts-esd-setup.vala"
					_tmp28_ = cred_source;
#line 60 "../src/contacts-esd-setup.vala"
					_tmp25_ = !e_source_equal (_tmp27_, _tmp28_);
#line 423 "contacts-esd-setup.c"
				} else {
#line 60 "../src/contacts-esd-setup.vala"
					_tmp25_ = FALSE;
#line 427 "contacts-esd-setup.c"
				}
#line 60 "../src/contacts-esd-setup.vala"
				if (_tmp25_) {
#line 431 "contacts-esd-setup.c"
					ECredentialsPrompter* _tmp29_;
					ESource* _tmp30_;
#line 61 "../src/contacts-esd-setup.vala"
					_tmp29_ = contacts_eds_credentials_prompter;
#line 61 "../src/contacts-esd-setup.vala"
					_tmp30_ = cred_source;
#line 61 "../src/contacts-esd-setup.vala"
					e_credentials_prompter_set_auto_prompt_disabled_for (_tmp29_, _tmp30_, FALSE);
#line 440 "contacts-esd-setup.c"
				}
#line 58 "../src/contacts-esd-setup.vala"
				_g_object_unref0 (cred_source);
#line 58 "../src/contacts-esd-setup.vala"
				_g_object_unref0 (source);
#line 446 "contacts-esd-setup.c"
			}
		}
#line 58 "../src/contacts-esd-setup.vala"
		(source_collection == NULL) ? NULL : (source_collection = (_g_list_free__g_object_unref0_ (source_collection), NULL));
#line 451 "contacts-esd-setup.c"
	}
#line 66 "../src/contacts-esd-setup.vala"
	_tmp31_ = contacts_eds_source_registry;
#line 66 "../src/contacts-esd-setup.vala"
	g_signal_connect (_tmp31_, "credentials-required", (GCallback) ___lambda4__e_source_registry_credentials_required, NULL);
#line 70 "../src/contacts-esd-setup.vala"
	_tmp32_ = contacts_eds_credentials_prompter;
#line 70 "../src/contacts-esd-setup.vala"
	e_credentials_prompter_process_awaiting_credentials (_tmp32_);
#line 72 "../src/contacts-esd-setup.vala"
	result = TRUE;
#line 72 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (credentials_provider);
#line 72 "../src/contacts-esd-setup.vala"
	return result;
#line 467 "contacts-esd-setup.c"
}

static void
contacts_on_credentials_required_data_free (gpointer _data)
{
	ContactsOnCredentialsRequiredData* _data_;
	_data_ = _data;
	_g_free0 (_data_->cert_pem);
	g_slice_free (ContactsOnCredentialsRequiredData, _data_);
}

void
contacts_on_credentials_required (ESource* source,
                                  ESourceCredentialsReason reason,
                                  const gchar* cert_pem,
                                  GTlsCertificateFlags cert_errors,
                                  GError* err,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_)
{
	ContactsOnCredentialsRequiredData* _data_;
	ESource* _tmp0_;
	gchar* _tmp1_;
	_data_ = g_slice_new0 (ContactsOnCredentialsRequiredData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, contacts_on_credentials_required_data_free);
	_tmp0_ = _g_object_ref0 (source);
	_g_object_unref0 (_data_->source);
	_data_->source = _tmp0_;
	_data_->reason = reason;
	_tmp1_ = g_strdup (cert_pem);
	_g_free0 (_data_->cert_pem);
	_data_->cert_pem = _tmp1_;
	_data_->cert_errors = cert_errors;
	_data_->err = err;
	contacts_on_credentials_required_co (_data_);
}

void
contacts_on_credentials_required_finish (GAsyncResult* _res_)
{
	ContactsOnCredentialsRequiredData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 75 "../src/contacts-esd-setup.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 75 "../src/contacts-esd-setup.vala"
	return _data1_;
#line 520 "contacts-esd-setup.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 75 "../src/contacts-esd-setup.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 75 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (_data1_->source);
#line 75 "../src/contacts-esd-setup.vala"
		g_slice_free (Block1Data, _data1_);
#line 534 "contacts-esd-setup.c"
	}
}

static void
___lambda5_ (Block1Data* _data1_,
             GObject* obj,
             GAsyncResult* res)
{
#line 87 "../src/contacts-esd-setup.vala"
	g_return_if_fail (res != NULL);
#line 87 "../src/contacts-esd-setup.vala"
	contacts_on_source_trust_prompt_has_run (_data1_->source, res, NULL, NULL);
#line 547 "contacts-esd-setup.c"
}

static void
____lambda5__gasync_ready_callback (GObject* source_object,
                                    GAsyncResult* res,
                                    gpointer self)
{
#line 85 "../src/contacts-esd-setup.vala"
	___lambda5_ (self, source_object, res);
#line 557 "contacts-esd-setup.c"
}

static gboolean
contacts_on_credentials_required_co (ContactsOnCredentialsRequiredData* _data_)
{
#line 75 "../src/contacts-esd-setup.vala"
	switch (_data_->_state_) {
#line 75 "../src/contacts-esd-setup.vala"
		case 0:
#line 567 "contacts-esd-setup.c"
		goto _state_0;
		default:
#line 75 "../src/contacts-esd-setup.vala"
		g_assert_not_reached ();
#line 572 "contacts-esd-setup.c"
	}
	_state_0:
#line 75 "../src/contacts-esd-setup.vala"
	_data_->_data1_ = g_slice_new0 (Block1Data);
#line 75 "../src/contacts-esd-setup.vala"
	_data_->_data1_->_ref_count_ = 1;
#line 75 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (_data_->_data1_->source);
#line 75 "../src/contacts-esd-setup.vala"
	_data_->_data1_->source = _data_->source;
#line 75 "../src/contacts-esd-setup.vala"
	_data_->_data1_->_async_data_ = _data_;
#line 76 "../src/contacts-esd-setup.vala"
	_data_->_tmp0_ = contacts_eds_credentials_prompter;
#line 76 "../src/contacts-esd-setup.vala"
	if (e_credentials_prompter_get_auto_prompt_disabled_for (_data_->_tmp0_, _data_->_data1_->source)) {
#line 77 "../src/contacts-esd-setup.vala"
		block1_data_unref (_data_->_data1_);
#line 77 "../src/contacts-esd-setup.vala"
		_data_->_data1_ = NULL;
#line 77 "../src/contacts-esd-setup.vala"
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 77 "../src/contacts-esd-setup.vala"
		if (_data_->_state_ != 0) {
#line 77 "../src/contacts-esd-setup.vala"
			while (!g_task_get_completed (_data_->_async_result)) {
#line 77 "../src/contacts-esd-setup.vala"
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 601 "contacts-esd-setup.c"
			}
		}
#line 77 "../src/contacts-esd-setup.vala"
		g_object_unref (_data_->_async_result);
#line 77 "../src/contacts-esd-setup.vala"
		return FALSE;
#line 608 "contacts-esd-setup.c"
	}
#line 79 "../src/contacts-esd-setup.vala"
	if (_data_->reason == E_SOURCE_CREDENTIALS_REASON_ERROR) {
#line 79 "../src/contacts-esd-setup.vala"
		_data_->_tmp1_ = _data_->err != NULL;
#line 614 "contacts-esd-setup.c"
	} else {
#line 79 "../src/contacts-esd-setup.vala"
		_data_->_tmp1_ = FALSE;
#line 618 "contacts-esd-setup.c"
	}
#line 79 "../src/contacts-esd-setup.vala"
	if (_data_->_tmp1_) {
#line 80 "../src/contacts-esd-setup.vala"
		_data_->_tmp2_ = e_source_get_display_name (_data_->_data1_->source);
#line 80 "../src/contacts-esd-setup.vala"
		_data_->_tmp3_ = _data_->_tmp2_;
#line 80 "../src/contacts-esd-setup.vala"
		_data_->_tmp4_ = _data_->err->message;
#line 80 "../src/contacts-esd-setup.vala"
		g_warning ("contacts-esd-setup.vala:80: Failed to autheticate for source \"%s\": %" \
"s", _data_->_tmp3_, _data_->_tmp4_);
#line 81 "../src/contacts-esd-setup.vala"
		block1_data_unref (_data_->_data1_);
#line 81 "../src/contacts-esd-setup.vala"
		_data_->_data1_ = NULL;
#line 81 "../src/contacts-esd-setup.vala"
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 81 "../src/contacts-esd-setup.vala"
		if (_data_->_state_ != 0) {
#line 81 "../src/contacts-esd-setup.vala"
			while (!g_task_get_completed (_data_->_async_result)) {
#line 81 "../src/contacts-esd-setup.vala"
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 642 "contacts-esd-setup.c"
			}
		}
#line 81 "../src/contacts-esd-setup.vala"
		g_object_unref (_data_->_async_result);
#line 81 "../src/contacts-esd-setup.vala"
		return FALSE;
#line 649 "contacts-esd-setup.c"
	}
#line 84 "../src/contacts-esd-setup.vala"
	if (_data_->reason == E_SOURCE_CREDENTIALS_REASON_SSL_FAILED) {
#line 86 "../src/contacts-esd-setup.vala"
		if (_data_->err != NULL) {
#line 86 "../src/contacts-esd-setup.vala"
			_data_->_tmp6_ = _data_->err->message;
#line 86 "../src/contacts-esd-setup.vala"
			_data_->_tmp5_ = _data_->_tmp6_;
#line 659 "contacts-esd-setup.c"
		} else {
#line 86 "../src/contacts-esd-setup.vala"
			_data_->_tmp5_ = NULL;
#line 663 "contacts-esd-setup.c"
		}
#line 85 "../src/contacts-esd-setup.vala"
		_data_->_tmp7_ = contacts_eds_credentials_prompter;
#line 85 "../src/contacts-esd-setup.vala"
		_data_->_tmp8_ = e_credentials_prompter_get_dialog_parent (_data_->_tmp7_);
#line 85 "../src/contacts-esd-setup.vala"
		e_trust_prompt_run_for_source (_data_->_tmp8_, _data_->_data1_->source, _data_->cert_pem, _data_->cert_errors, _data_->_tmp5_, TRUE, NULL, ____lambda5__gasync_ready_callback, _data_->_data1_);
#line 671 "contacts-esd-setup.c"
	}
#line 75 "../src/contacts-esd-setup.vala"
	block1_data_unref (_data_->_data1_);
#line 75 "../src/contacts-esd-setup.vala"
	_data_->_data1_ = NULL;
#line 75 "../src/contacts-esd-setup.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 75 "../src/contacts-esd-setup.vala"
	if (_data_->_state_ != 0) {
#line 75 "../src/contacts-esd-setup.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 75 "../src/contacts-esd-setup.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 685 "contacts-esd-setup.c"
		}
	}
#line 75 "../src/contacts-esd-setup.vala"
	g_object_unref (_data_->_async_result);
#line 75 "../src/contacts-esd-setup.vala"
	return FALSE;
#line 692 "contacts-esd-setup.c"
}

static void
contacts_on_source_trust_prompt_has_run_data_free (gpointer _data)
{
	ContactsOnSourceTrustPromptHasRunData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->source);
	_g_object_unref0 (_data_->res);
	g_slice_free (ContactsOnSourceTrustPromptHasRunData, _data_);
}

void
contacts_on_source_trust_prompt_has_run (ESource* source,
                                         GAsyncResult* res,
                                         GAsyncReadyCallback _callback_,
                                         gpointer _user_data_)
{
	ContactsOnSourceTrustPromptHasRunData* _data_;
	ESource* _tmp0_;
	GAsyncResult* _tmp1_;
	_data_ = g_slice_new0 (ContactsOnSourceTrustPromptHasRunData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, contacts_on_source_trust_prompt_has_run_data_free);
	_tmp0_ = _g_object_ref0 (source);
	_g_object_unref0 (_data_->source);
	_data_->source = _tmp0_;
	_tmp1_ = _g_object_ref0 (res);
	_g_object_unref0 (_data_->res);
	_data_->res = _tmp1_;
	contacts_on_source_trust_prompt_has_run_co (_data_);
}

void
contacts_on_source_trust_prompt_has_run_finish (GAsyncResult* _res_)
{
	ContactsOnSourceTrustPromptHasRunData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
}

static void
contacts_on_source_trust_prompt_has_run_ready (GObject* source_object,
                                               GAsyncResult* _res_,
                                               gpointer _user_data_)
{
	ContactsOnSourceTrustPromptHasRunData* _data_;
#line 101 "../src/contacts-esd-setup.vala"
	_data_ = _user_data_;
#line 101 "../src/contacts-esd-setup.vala"
	_data_->_source_object_ = source_object;
#line 101 "../src/contacts-esd-setup.vala"
	_data_->_res_ = _res_;
#line 101 "../src/contacts-esd-setup.vala"
	contacts_on_source_trust_prompt_has_run_co (_data_);
#line 747 "contacts-esd-setup.c"
}

static gboolean
contacts_on_source_trust_prompt_has_run_co (ContactsOnSourceTrustPromptHasRunData* _data_)
{
#line 91 "../src/contacts-esd-setup.vala"
	switch (_data_->_state_) {
#line 91 "../src/contacts-esd-setup.vala"
		case 0:
#line 757 "contacts-esd-setup.c"
		goto _state_0;
#line 91 "../src/contacts-esd-setup.vala"
		case 1:
#line 761 "contacts-esd-setup.c"
		goto _state_1;
		default:
#line 91 "../src/contacts-esd-setup.vala"
		g_assert_not_reached ();
#line 766 "contacts-esd-setup.c"
	}
	_state_0:
	{
#line 93 "../src/contacts-esd-setup.vala"
		e_trust_prompt_run_for_source_finish (_data_->source, _data_->res, NULL, &_data_->_inner_error0_);
#line 93 "../src/contacts-esd-setup.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 774 "contacts-esd-setup.c"
			goto __catch1_g_error;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
#line 92 "../src/contacts-esd-setup.vala"
		_data_->e = _data_->_inner_error0_;
#line 92 "../src/contacts-esd-setup.vala"
		_data_->_inner_error0_ = NULL;
#line 95 "../src/contacts-esd-setup.vala"
		_data_->_tmp0_ = e_source_get_display_name (_data_->source);
#line 95 "../src/contacts-esd-setup.vala"
		_data_->_tmp1_ = _data_->_tmp0_;
#line 95 "../src/contacts-esd-setup.vala"
		_data_->_tmp2_ = _data_->e;
#line 95 "../src/contacts-esd-setup.vala"
		_data_->_tmp3_ = _data_->_tmp2_->message;
#line 95 "../src/contacts-esd-setup.vala"
		g_warning ("contacts-esd-setup.vala:95: Failed to prompt for trust for source \"%s" \
"\": %s", _data_->_tmp1_, _data_->_tmp3_);
#line 96 "../src/contacts-esd-setup.vala"
		_g_error_free0 (_data_->e);
#line 96 "../src/contacts-esd-setup.vala"
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 96 "../src/contacts-esd-setup.vala"
		if (_data_->_state_ != 0) {
#line 96 "../src/contacts-esd-setup.vala"
			while (!g_task_get_completed (_data_->_async_result)) {
#line 96 "../src/contacts-esd-setup.vala"
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 805 "contacts-esd-setup.c"
			}
		}
#line 96 "../src/contacts-esd-setup.vala"
		g_object_unref (_data_->_async_result);
#line 96 "../src/contacts-esd-setup.vala"
		return FALSE;
#line 812 "contacts-esd-setup.c"
	}
	__finally1:
#line 92 "../src/contacts-esd-setup.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 92 "../src/contacts-esd-setup.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 92 "../src/contacts-esd-setup.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 92 "../src/contacts-esd-setup.vala"
		g_object_unref (_data_->_async_result);
#line 92 "../src/contacts-esd-setup.vala"
		return FALSE;
#line 825 "contacts-esd-setup.c"
	}
	{
#line 101 "../src/contacts-esd-setup.vala"
		_data_->_state_ = 1;
#line 101 "../src/contacts-esd-setup.vala"
		e_source_invoke_authenticate (_data_->source, NULL, NULL, contacts_on_source_trust_prompt_has_run_ready, _data_);
#line 101 "../src/contacts-esd-setup.vala"
		return FALSE;
#line 834 "contacts-esd-setup.c"
		_state_1:
#line 101 "../src/contacts-esd-setup.vala"
		e_source_invoke_authenticate_finish (_data_->source, _data_->_res_, &_data_->_inner_error0_);
#line 101 "../src/contacts-esd-setup.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 840 "contacts-esd-setup.c"
			goto __catch2_g_error;
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
#line 99 "../src/contacts-esd-setup.vala"
		_data_->_vala1_e = _data_->_inner_error0_;
#line 99 "../src/contacts-esd-setup.vala"
		_data_->_inner_error0_ = NULL;
#line 103 "../src/contacts-esd-setup.vala"
		_data_->_tmp4_ = e_source_get_display_name (_data_->source);
#line 103 "../src/contacts-esd-setup.vala"
		_data_->_tmp5_ = _data_->_tmp4_;
#line 103 "../src/contacts-esd-setup.vala"
		_data_->_tmp6_ = _data_->_vala1_e;
#line 103 "../src/contacts-esd-setup.vala"
		_data_->_tmp7_ = _data_->_tmp6_->message;
#line 103 "../src/contacts-esd-setup.vala"
		g_warning ("contacts-esd-setup.vala:103: Failed to invoke authenticate() for sourc" \
"e \"%s\": %s", _data_->_tmp5_, _data_->_tmp7_);
#line 99 "../src/contacts-esd-setup.vala"
		_g_error_free0 (_data_->_vala1_e);
#line 863 "contacts-esd-setup.c"
	}
	__finally2:
#line 99 "../src/contacts-esd-setup.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 99 "../src/contacts-esd-setup.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 99 "../src/contacts-esd-setup.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 99 "../src/contacts-esd-setup.vala"
		g_object_unref (_data_->_async_result);
#line 99 "../src/contacts-esd-setup.vala"
		return FALSE;
#line 876 "contacts-esd-setup.c"
	}
#line 91 "../src/contacts-esd-setup.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 91 "../src/contacts-esd-setup.vala"
	if (_data_->_state_ != 0) {
#line 91 "../src/contacts-esd-setup.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 91 "../src/contacts-esd-setup.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 886 "contacts-esd-setup.c"
		}
	}
#line 91 "../src/contacts-esd-setup.vala"
	g_object_unref (_data_->_async_result);
#line 91 "../src/contacts-esd-setup.vala"
	return FALSE;
#line 893 "contacts-esd-setup.c"
}

gboolean
contacts_has_goa_account (void)
{
	ESourceRegistry* _tmp0_;
	GList* _tmp1_;
	gboolean result = FALSE;
#line 108 "../src/contacts-esd-setup.vala"
	_tmp0_ = contacts_eds_source_registry;
#line 108 "../src/contacts-esd-setup.vala"
	_tmp1_ = e_source_registry_list_sources (_tmp0_, E_SOURCE_EXTENSION_GOA);
#line 906 "contacts-esd-setup.c"
	{
		GList* source_collection = NULL;
		GList* source_it = NULL;
#line 108 "../src/contacts-esd-setup.vala"
		source_collection = _tmp1_;
#line 108 "../src/contacts-esd-setup.vala"
		for (source_it = source_collection; source_it != NULL; source_it = source_it->next) {
#line 914 "contacts-esd-setup.c"
			ESource* _tmp2_;
			ESource* source = NULL;
#line 108 "../src/contacts-esd-setup.vala"
			_tmp2_ = _g_object_ref0 ((ESource*) source_it->data);
#line 108 "../src/contacts-esd-setup.vala"
			source = _tmp2_;
#line 921 "contacts-esd-setup.c"
			{
				ESource* _tmp3_;
				gboolean _tmp4_;
				gboolean _tmp5_;
				ESource* _tmp6_;
				ESource* _tmp7_;
				ESourceExtension* _tmp8_;
				gboolean _tmp9_;
				gboolean _tmp10_;
#line 110 "../src/contacts-esd-setup.vala"
				_tmp3_ = source;
#line 110 "../src/contacts-esd-setup.vala"
				_tmp4_ = e_source_get_enabled (_tmp3_);
#line 110 "../src/contacts-esd-setup.vala"
				_tmp5_ = _tmp4_;
#line 110 "../src/contacts-esd-setup.vala"
				if (!_tmp5_) {
#line 111 "../src/contacts-esd-setup.vala"
					_g_object_unref0 (source);
#line 111 "../src/contacts-esd-setup.vala"
					continue;
#line 943 "contacts-esd-setup.c"
				}
#line 115 "../src/contacts-esd-setup.vala"
				_tmp6_ = source;
#line 115 "../src/contacts-esd-setup.vala"
				if (!e_source_has_extension (_tmp6_, E_SOURCE_EXTENSION_COLLECTION)) {
#line 116 "../src/contacts-esd-setup.vala"
					_g_object_unref0 (source);
#line 116 "../src/contacts-esd-setup.vala"
					continue;
#line 953 "contacts-esd-setup.c"
				}
#line 119 "../src/contacts-esd-setup.vala"
				_tmp7_ = source;
#line 119 "../src/contacts-esd-setup.vala"
				_tmp8_ = e_source_get_extension (_tmp7_, E_SOURCE_EXTENSION_COLLECTION);
#line 119 "../src/contacts-esd-setup.vala"
				_tmp9_ = e_source_collection_get_contacts_enabled (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, e_source_collection_get_type (), ESourceCollection));
#line 119 "../src/contacts-esd-setup.vala"
				_tmp10_ = _tmp9_;
#line 119 "../src/contacts-esd-setup.vala"
				if (_tmp10_) {
#line 120 "../src/contacts-esd-setup.vala"
					result = TRUE;
#line 120 "../src/contacts-esd-setup.vala"
					_g_object_unref0 (source);
#line 120 "../src/contacts-esd-setup.vala"
					(source_collection == NULL) ? NULL : (source_collection = (_g_list_free__g_object_unref0_ (source_collection), NULL));
#line 120 "../src/contacts-esd-setup.vala"
					return result;
#line 973 "contacts-esd-setup.c"
				}
#line 108 "../src/contacts-esd-setup.vala"
				_g_object_unref0 (source);
#line 977 "contacts-esd-setup.c"
			}
		}
#line 108 "../src/contacts-esd-setup.vala"
		(source_collection == NULL) ? NULL : (source_collection = (_g_list_free__g_object_unref0_ (source_collection), NULL));
#line 982 "contacts-esd-setup.c"
	}
#line 124 "../src/contacts-esd-setup.vala"
	result = FALSE;
#line 124 "../src/contacts-esd-setup.vala"
	return result;
#line 988 "contacts-esd-setup.c"
}

gboolean
contacts_esource_uid_is_google (const gchar* uid)
{
	ESource* source = NULL;
	ESourceRegistry* _tmp0_;
	ESource* _tmp1_;
	ESource* _tmp2_;
	ESource* _tmp3_;
	gboolean result = FALSE;
#line 127 "../src/contacts-esd-setup.vala"
	g_return_val_if_fail (uid != NULL, FALSE);
#line 128 "../src/contacts-esd-setup.vala"
	_tmp0_ = contacts_eds_source_registry;
#line 128 "../src/contacts-esd-setup.vala"
	_tmp1_ = e_source_registry_ref_source (_tmp0_, uid);
#line 128 "../src/contacts-esd-setup.vala"
	source = _tmp1_;
#line 129 "../src/contacts-esd-setup.vala"
	_tmp2_ = source;
#line 129 "../src/contacts-esd-setup.vala"
	if (_tmp2_ == NULL) {
#line 130 "../src/contacts-esd-setup.vala"
		result = FALSE;
#line 130 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 130 "../src/contacts-esd-setup.vala"
		return result;
#line 1018 "contacts-esd-setup.c"
	}
#line 133 "../src/contacts-esd-setup.vala"
	_tmp3_ = source;
#line 133 "../src/contacts-esd-setup.vala"
	if (e_source_has_extension (_tmp3_, E_SOURCE_EXTENSION_ADDRESS_BOOK)) {
#line 1024 "contacts-esd-setup.c"
		ESourceExtension* extension = NULL;
		ESource* _tmp4_;
		ESourceExtension* _tmp5_;
		ESourceExtension* _tmp6_;
		ESourceExtension* _tmp7_;
		const gchar* _tmp8_;
		const gchar* _tmp9_;
#line 134 "../src/contacts-esd-setup.vala"
		_tmp4_ = source;
#line 134 "../src/contacts-esd-setup.vala"
		_tmp5_ = e_source_get_extension (_tmp4_, E_SOURCE_EXTENSION_ADDRESS_BOOK);
#line 134 "../src/contacts-esd-setup.vala"
		_tmp6_ = _g_object_ref0 (_tmp5_);
#line 134 "../src/contacts-esd-setup.vala"
		extension = _tmp6_;
#line 135 "../src/contacts-esd-setup.vala"
		_tmp7_ = extension;
#line 135 "../src/contacts-esd-setup.vala"
		_tmp8_ = e_source_backend_get_backend_name (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, e_source_backend_get_type (), ESourceBackend));
#line 135 "../src/contacts-esd-setup.vala"
		_tmp9_ = _tmp8_;
#line 135 "../src/contacts-esd-setup.vala"
		result = g_strcmp0 (_tmp9_, "google") == 0;
#line 135 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (extension);
#line 135 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 135 "../src/contacts-esd-setup.vala"
		return result;
#line 1054 "contacts-esd-setup.c"
	}
#line 138 "../src/contacts-esd-setup.vala"
	result = FALSE;
#line 138 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (source);
#line 138 "../src/contacts-esd-setup.vala"
	return result;
#line 1062 "contacts-esd-setup.c"
}

gchar*
contacts_lookup_esource_name_by_uid (const gchar* uid)
{
	ESource* source = NULL;
	ESourceRegistry* _tmp0_;
	ESource* _tmp1_;
	ESource* _tmp2_;
	ESource* builtin_address_book = NULL;
	ESourceRegistry* _tmp3_;
	ESource* _tmp4_;
	ESource* _tmp5_;
	ESource* _tmp6_;
	ESource* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* result = NULL;
#line 141 "../src/contacts-esd-setup.vala"
	g_return_val_if_fail (uid != NULL, NULL);
#line 142 "../src/contacts-esd-setup.vala"
	_tmp0_ = contacts_eds_source_registry;
#line 142 "../src/contacts-esd-setup.vala"
	_tmp1_ = e_source_registry_ref_source (_tmp0_, uid);
#line 142 "../src/contacts-esd-setup.vala"
	source = _tmp1_;
#line 143 "../src/contacts-esd-setup.vala"
	_tmp2_ = source;
#line 143 "../src/contacts-esd-setup.vala"
	if (_tmp2_ == NULL) {
#line 144 "../src/contacts-esd-setup.vala"
		result = NULL;
#line 144 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 144 "../src/contacts-esd-setup.vala"
		return result;
#line 1100 "contacts-esd-setup.c"
	}
#line 146 "../src/contacts-esd-setup.vala"
	_tmp3_ = contacts_eds_source_registry;
#line 146 "../src/contacts-esd-setup.vala"
	_tmp4_ = e_source_registry_ref_builtin_address_book (_tmp3_);
#line 146 "../src/contacts-esd-setup.vala"
	builtin_address_book = _tmp4_;
#line 148 "../src/contacts-esd-setup.vala"
	_tmp5_ = source;
#line 148 "../src/contacts-esd-setup.vala"
	_tmp6_ = builtin_address_book;
#line 148 "../src/contacts-esd-setup.vala"
	if (e_source_equal (_tmp5_, _tmp6_)) {
#line 1114 "contacts-esd-setup.c"
		gchar* _tmp7_;
#line 149 "../src/contacts-esd-setup.vala"
		_tmp7_ = g_strdup (_ ("Local Address Book"));
#line 149 "../src/contacts-esd-setup.vala"
		result = _tmp7_;
#line 149 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (builtin_address_book);
#line 149 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 149 "../src/contacts-esd-setup.vala"
		return result;
#line 1126 "contacts-esd-setup.c"
	}
#line 151 "../src/contacts-esd-setup.vala"
	if (contacts_esource_uid_is_google (uid)) {
#line 1130 "contacts-esd-setup.c"
		gchar* _tmp8_;
#line 152 "../src/contacts-esd-setup.vala"
		_tmp8_ = g_strdup (_ ("Google"));
#line 152 "../src/contacts-esd-setup.vala"
		result = _tmp8_;
#line 152 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (builtin_address_book);
#line 152 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 152 "../src/contacts-esd-setup.vala"
		return result;
#line 1142 "contacts-esd-setup.c"
	}
#line 154 "../src/contacts-esd-setup.vala"
	_tmp9_ = source;
#line 154 "../src/contacts-esd-setup.vala"
	_tmp10_ = e_source_get_display_name (_tmp9_);
#line 154 "../src/contacts-esd-setup.vala"
	_tmp11_ = _tmp10_;
#line 154 "../src/contacts-esd-setup.vala"
	_tmp12_ = g_strdup (_tmp11_);
#line 154 "../src/contacts-esd-setup.vala"
	result = _tmp12_;
#line 154 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (builtin_address_book);
#line 154 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (source);
#line 154 "../src/contacts-esd-setup.vala"
	return result;
#line 1160 "contacts-esd-setup.c"
}

gchar*
contacts_lookup_esource_name_by_uid_for_contact (const gchar* uid)
{
	ESource* source = NULL;
	ESourceRegistry* _tmp0_;
	ESource* _tmp1_;
	ESource* _tmp2_;
	ESource* builtin_address_book = NULL;
	ESourceRegistry* _tmp3_;
	ESource* _tmp4_;
	ESource* _tmp5_;
	ESource* _tmp6_;
	ESource* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* result = NULL;
#line 157 "../src/contacts-esd-setup.vala"
	g_return_val_if_fail (uid != NULL, NULL);
#line 158 "../src/contacts-esd-setup.vala"
	_tmp0_ = contacts_eds_source_registry;
#line 158 "../src/contacts-esd-setup.vala"
	_tmp1_ = e_source_registry_ref_source (_tmp0_, uid);
#line 158 "../src/contacts-esd-setup.vala"
	source = _tmp1_;
#line 159 "../src/contacts-esd-setup.vala"
	_tmp2_ = source;
#line 159 "../src/contacts-esd-setup.vala"
	if (_tmp2_ == NULL) {
#line 160 "../src/contacts-esd-setup.vala"
		result = NULL;
#line 160 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 160 "../src/contacts-esd-setup.vala"
		return result;
#line 1198 "contacts-esd-setup.c"
	}
#line 162 "../src/contacts-esd-setup.vala"
	_tmp3_ = contacts_eds_source_registry;
#line 162 "../src/contacts-esd-setup.vala"
	_tmp4_ = e_source_registry_ref_builtin_address_book (_tmp3_);
#line 162 "../src/contacts-esd-setup.vala"
	builtin_address_book = _tmp4_;
#line 163 "../src/contacts-esd-setup.vala"
	_tmp5_ = source;
#line 163 "../src/contacts-esd-setup.vala"
	_tmp6_ = builtin_address_book;
#line 163 "../src/contacts-esd-setup.vala"
	if (e_source_equal (_tmp5_, _tmp6_)) {
#line 1212 "contacts-esd-setup.c"
		gchar* _tmp7_;
#line 164 "../src/contacts-esd-setup.vala"
		_tmp7_ = g_strdup (_ ("Local Contact"));
#line 164 "../src/contacts-esd-setup.vala"
		result = _tmp7_;
#line 164 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (builtin_address_book);
#line 164 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 164 "../src/contacts-esd-setup.vala"
		return result;
#line 1224 "contacts-esd-setup.c"
	}
#line 166 "../src/contacts-esd-setup.vala"
	if (contacts_esource_uid_is_google (uid)) {
#line 1228 "contacts-esd-setup.c"
		gchar* _tmp8_;
#line 167 "../src/contacts-esd-setup.vala"
		_tmp8_ = g_strdup (_ ("Google"));
#line 167 "../src/contacts-esd-setup.vala"
		result = _tmp8_;
#line 167 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (builtin_address_book);
#line 167 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (source);
#line 167 "../src/contacts-esd-setup.vala"
		return result;
#line 1240 "contacts-esd-setup.c"
	}
#line 169 "../src/contacts-esd-setup.vala"
	_tmp9_ = source;
#line 169 "../src/contacts-esd-setup.vala"
	_tmp10_ = e_source_get_display_name (_tmp9_);
#line 169 "../src/contacts-esd-setup.vala"
	_tmp11_ = _tmp10_;
#line 169 "../src/contacts-esd-setup.vala"
	_tmp12_ = g_strdup (_tmp11_);
#line 169 "../src/contacts-esd-setup.vala"
	result = _tmp12_;
#line 169 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (builtin_address_book);
#line 169 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (source);
#line 169 "../src/contacts-esd-setup.vala"
	return result;
#line 1258 "contacts-esd-setup.c"
}

GtkImage*
contacts_get_icon_for_goa_account (const gchar* goa_id)
{
	GoaClient* client = NULL;
	GoaObject* goa_object = NULL;
	GoaClient* _tmp5_;
	GoaObject* _tmp6_;
	GIcon* provider_icon = NULL;
	GIcon* _tmp18_;
	GtkImage* _tmp19_;
	GError* _inner_error0_ = NULL;
	GtkImage* result = NULL;
#line 172 "../src/contacts-esd-setup.vala"
	g_return_val_if_fail (goa_id != NULL, NULL);
#line 1275 "contacts-esd-setup.c"
	{
		GoaClient* _tmp0_ = NULL;
		GoaClient* _tmp1_;
		GoaClient* _tmp2_;
#line 175 "../src/contacts-esd-setup.vala"
		_tmp1_ = goa_client_new_sync (NULL, &_inner_error0_);
#line 175 "../src/contacts-esd-setup.vala"
		_tmp0_ = _tmp1_;
#line 175 "../src/contacts-esd-setup.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1286 "contacts-esd-setup.c"
			goto __catch3_g_error;
		}
#line 175 "../src/contacts-esd-setup.vala"
		_tmp2_ = _tmp0_;
#line 175 "../src/contacts-esd-setup.vala"
		_tmp0_ = NULL;
#line 175 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (client);
#line 175 "../src/contacts-esd-setup.vala"
		client = _tmp2_;
#line 174 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (_tmp0_);
#line 1299 "contacts-esd-setup.c"
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		GError* _tmp3_;
		const gchar* _tmp4_;
#line 174 "../src/contacts-esd-setup.vala"
		e = _inner_error0_;
#line 174 "../src/contacts-esd-setup.vala"
		_inner_error0_ = NULL;
#line 177 "../src/contacts-esd-setup.vala"
		_tmp3_ = e;
#line 177 "../src/contacts-esd-setup.vala"
		_tmp4_ = _tmp3_->message;
#line 177 "../src/contacts-esd-setup.vala"
		g_debug ("contacts-esd-setup.vala:177: Couldn't load GOA client \"%s\": %s", goa_id, _tmp4_);
#line 178 "../src/contacts-esd-setup.vala"
		result = NULL;
#line 178 "../src/contacts-esd-setup.vala"
		_g_error_free0 (e);
#line 178 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (client);
#line 178 "../src/contacts-esd-setup.vala"
		return result;
#line 1325 "contacts-esd-setup.c"
	}
	__finally3:
#line 174 "../src/contacts-esd-setup.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 174 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (client);
#line 174 "../src/contacts-esd-setup.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 174 "../src/contacts-esd-setup.vala"
		g_clear_error (&_inner_error0_);
#line 174 "../src/contacts-esd-setup.vala"
		return NULL;
#line 1338 "contacts-esd-setup.c"
	}
#line 181 "../src/contacts-esd-setup.vala"
	_tmp5_ = client;
#line 181 "../src/contacts-esd-setup.vala"
	_tmp6_ = goa_client_lookup_by_id (_tmp5_, goa_id);
#line 181 "../src/contacts-esd-setup.vala"
	goa_object = _tmp6_;
#line 1346 "contacts-esd-setup.c"
	{
		GIcon* _tmp7_ = NULL;
		GoaObject* _tmp8_;
		GoaAccount* _tmp9_;
		GoaAccount* _tmp10_;
		GoaAccount* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		GIcon* _tmp15_;
		GIcon* _tmp16_;
		GIcon* _tmp17_;
#line 185 "../src/contacts-esd-setup.vala"
		_tmp8_ = goa_object;
#line 185 "../src/contacts-esd-setup.vala"
		g_object_get (_tmp8_, "account", &_tmp9_, NULL);
#line 185 "../src/contacts-esd-setup.vala"
		_tmp10_ = _tmp9_;
#line 185 "../src/contacts-esd-setup.vala"
		_tmp11_ = _tmp10_;
#line 185 "../src/contacts-esd-setup.vala"
		g_object_get (_tmp11_, "provider-icon", &_tmp12_, NULL);
#line 185 "../src/contacts-esd-setup.vala"
		_tmp13_ = _tmp12_;
#line 185 "../src/contacts-esd-setup.vala"
		_tmp14_ = _tmp13_;
#line 185 "../src/contacts-esd-setup.vala"
		_tmp15_ = g_icon_new_for_string (_tmp14_, &_inner_error0_);
#line 185 "../src/contacts-esd-setup.vala"
		_tmp16_ = _tmp15_;
#line 185 "../src/contacts-esd-setup.vala"
		_g_free0 (_tmp14_);
#line 185 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (_tmp11_);
#line 185 "../src/contacts-esd-setup.vala"
		_tmp7_ = _tmp16_;
#line 185 "../src/contacts-esd-setup.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1385 "contacts-esd-setup.c"
			goto __catch4_g_error;
		}
#line 185 "../src/contacts-esd-setup.vala"
		_tmp17_ = _tmp7_;
#line 185 "../src/contacts-esd-setup.vala"
		_tmp7_ = NULL;
#line 185 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (provider_icon);
#line 185 "../src/contacts-esd-setup.vala"
		provider_icon = _tmp17_;
#line 184 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (_tmp7_);
#line 1398 "contacts-esd-setup.c"
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
#line 184 "../src/contacts-esd-setup.vala"
		e = _inner_error0_;
#line 184 "../src/contacts-esd-setup.vala"
		_inner_error0_ = NULL;
#line 187 "../src/contacts-esd-setup.vala"
		g_debug ("contacts-esd-setup.vala:187: Couldn't load icon for GOA provider \"%s\"", goa_id);
#line 188 "../src/contacts-esd-setup.vala"
		result = NULL;
#line 188 "../src/contacts-esd-setup.vala"
		_g_error_free0 (e);
#line 188 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (provider_icon);
#line 188 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (goa_object);
#line 188 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (client);
#line 188 "../src/contacts-esd-setup.vala"
		return result;
#line 1422 "contacts-esd-setup.c"
	}
	__finally4:
#line 184 "../src/contacts-esd-setup.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 184 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (provider_icon);
#line 184 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (goa_object);
#line 184 "../src/contacts-esd-setup.vala"
		_g_object_unref0 (client);
#line 184 "../src/contacts-esd-setup.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 184 "../src/contacts-esd-setup.vala"
		g_clear_error (&_inner_error0_);
#line 184 "../src/contacts-esd-setup.vala"
		return NULL;
#line 1439 "contacts-esd-setup.c"
	}
#line 191 "../src/contacts-esd-setup.vala"
	_tmp18_ = provider_icon;
#line 191 "../src/contacts-esd-setup.vala"
	_tmp19_ = (GtkImage*) gtk_image_new_from_gicon (_tmp18_, (GtkIconSize) GTK_ICON_SIZE_DIALOG);
#line 191 "../src/contacts-esd-setup.vala"
	g_object_ref_sink (_tmp19_);
#line 191 "../src/contacts-esd-setup.vala"
	result = _tmp19_;
#line 191 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (provider_icon);
#line 191 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (goa_object);
#line 191 "../src/contacts-esd-setup.vala"
	_g_object_unref0 (client);
#line 191 "../src/contacts-esd-setup.vala"
	return result;
#line 1457 "contacts-esd-setup.c"
}

