/* basic-test.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from basic-test.vala, do not modify */

/*
 * Copyright (C) 2018 Niels De Graef <nielsdegraef@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>
#include <glib-object.h>
#include "contacts.h"

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

void _vala_main (gchar** args,
                 gint args_length1);
void contacts_utils_tests_get_first (void);
static void _contacts_utils_tests_get_first_gtest_func (void);

static void
_contacts_utils_tests_get_first_gtest_func (void)
{
#line 22 "../tests/basic-test.vala"
	contacts_utils_tests_get_first ();
#line 41 "basic-test.c"
}

void
_vala_main (gchar** args,
            gint args_length1)
{
#line 21 "../tests/basic-test.vala"
	g_test_init ((gint*) (&args_length1), &args, NULL);
#line 22 "../tests/basic-test.vala"
	g_test_add_func ("/utils/get_first", _contacts_utils_tests_get_first_gtest_func);
#line 23 "../tests/basic-test.vala"
	g_test_run ();
#line 54 "basic-test.c"
}

int
main (int argc,
      char ** argv)
{
#line 20 "../tests/basic-test.vala"
	_vala_main (argv, argc);
#line 20 "../tests/basic-test.vala"
	return 0;
#line 65 "basic-test.c"
}

void
contacts_utils_tests_get_first (void)
{
	GeeCollection* empty = NULL;
	GeeCollection* _tmp0_;
	gpointer _tmp1_;
	GObject* _tmp2_;
#line 28 "../tests/basic-test.vala"
	_tmp0_ = gee_collection_empty (G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref);
#line 28 "../tests/basic-test.vala"
	empty = _tmp0_;
#line 29 "../tests/basic-test.vala"
	_tmp1_ = contacts_utils_get_first (G_TYPE_OBJECT, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, empty);
#line 29 "../tests/basic-test.vala"
	_tmp2_ = (GObject*) _tmp1_;
#line 29 "../tests/basic-test.vala"
	g_assert_true (_tmp2_ == NULL);
#line 29 "../tests/basic-test.vala"
	_g_object_unref0 (_tmp2_);
#line 27 "../tests/basic-test.vala"
	_g_object_unref0 (empty);
#line 89 "basic-test.c"
}

