'\" t
.\"     Title: gnome-contacts
.\"    Author: Alexander Larsson <alexl@redhat.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 01/09/2020
.\"    Manual: User Commands
.\"    Source: GNOME
.\"  Language: English
.\"
.TH "GNOME\-CONTACTS" "1" "" "GNOME" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------


        

        

        .SH "NAME"
gnome-contacts \- Access and store information about contacts


        .SH "SYNOPSIS"

                .HP \w'\fBgnome\-contacts\ \fR\fB[OPTION...]\fR\ 'u

                        \fBgnome\-contacts \fR\fB[OPTION...]\fR
                

        

        .SH "DESCRIPTION"

                

                .PP
\fBgnome\-contacts\fR
is a graphical user interface to access and store information about your contacts\&.


                .PP
gnome\-contacts uses the folks library to pull together contact information from various sources, including telepathy, evolution\-data\-server, your configured GNOME online accounts, etc\&.

        

        .SH "OPTIONS"

                

                

                        .PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4

                                

                                Prints a short help text and exits\&.

                        .RE

                        .PP
\fB\-e\fR, \fB\-\-email\fR
.RS 4

                                

                                Show contact with this email address\&.

                        .RE

                        .PP
\fB\-i\fR, \fB\-\-individual\fR
.RS 4

                                

                                Show contact with this individual id\&.

                        .RE

                        .PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4

                                

                                Show the current version of Contacts\&.

                        .RE
                
        

