/* contacts-contact-sheet.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-contact-sheet.vala, do not modify */

/*
 * Copyright (C) 2011 Alexander Larsson <alexl@redhat.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <folks/folks.h>
#include "contacts.h"
#include <glib.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <glib/gi18n-lib.h>

#define CONTACTS_TYPE_CONTACT_FORM (contacts_contact_form_get_type ())
#define CONTACTS_CONTACT_FORM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_CONTACT_FORM, ContactsContactForm))
#define CONTACTS_CONTACT_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_CONTACT_FORM, ContactsContactFormClass))
#define CONTACTS_IS_CONTACT_FORM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_CONTACT_FORM))
#define CONTACTS_IS_CONTACT_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_CONTACT_FORM))
#define CONTACTS_CONTACT_FORM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_CONTACT_FORM, ContactsContactFormClass))

typedef struct _ContactsContactForm ContactsContactForm;
typedef struct _ContactsContactFormClass ContactsContactFormClass;
typedef struct _ContactsContactFormPrivate ContactsContactFormPrivate;

#define CONTACTS_TYPE_CONTACT_SHEET (contacts_contact_sheet_get_type ())
#define CONTACTS_CONTACT_SHEET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_CONTACT_SHEET, ContactsContactSheet))
#define CONTACTS_CONTACT_SHEET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_CONTACT_SHEET, ContactsContactSheetClass))
#define CONTACTS_IS_CONTACT_SHEET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_CONTACT_SHEET))
#define CONTACTS_IS_CONTACT_SHEET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_CONTACT_SHEET))
#define CONTACTS_CONTACT_SHEET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_CONTACT_SHEET, ContactsContactSheetClass))

typedef struct _ContactsContactSheet ContactsContactSheet;
typedef struct _ContactsContactSheetClass ContactsContactSheetClass;
typedef struct _ContactsContactSheetPrivate ContactsContactSheetPrivate;
enum  {
	CONTACTS_CONTACT_SHEET_0_PROPERTY,
	CONTACTS_CONTACT_SHEET_NUM_PROPERTIES
};
static GParamSpec* contacts_contact_sheet_properties[CONTACTS_CONTACT_SHEET_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CONTACTS_TYPE_AVATAR (contacts_avatar_get_type ())
#define CONTACTS_AVATAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_AVATAR, ContactsAvatar))
#define CONTACTS_AVATAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_AVATAR, ContactsAvatarClass))
#define CONTACTS_IS_AVATAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_AVATAR))
#define CONTACTS_IS_AVATAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_AVATAR))
#define CONTACTS_AVATAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_AVATAR, ContactsAvatarClass))

typedef struct _ContactsAvatar ContactsAvatar;
typedef struct _ContactsAvatarClass ContactsAvatarClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block19Data Block19Data;
typedef struct _Block20Data Block20Data;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _ContactsContactForm {
	GtkGrid parent_instance;
	ContactsContactFormPrivate * priv;
	FolksIndividual* individual;
	ContactsStore* store;
	GtkGrid* container_grid;
	gint last_row;
};

struct _ContactsContactFormClass {
	GtkGridClass parent_class;
};

struct _ContactsContactSheet {
	ContactsContactForm parent_instance;
	ContactsContactSheetPrivate * priv;
};

struct _ContactsContactSheetClass {
	ContactsContactFormClass parent_class;
};

struct _Block19Data {
	int _ref_count_;
	ContactsContactSheet* self;
	GtkLabel* name_label;
};

struct _Block20Data {
	int _ref_count_;
	ContactsContactSheet* self;
	FolksEmailFieldDetails* email;
};

static gpointer contacts_contact_sheet_parent_class = NULL;

GType contacts_contact_form_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsContactForm, g_object_unref)
GType contacts_contact_sheet_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsContactSheet, g_object_unref)
ContactsContactSheet* contacts_contact_sheet_new (FolksIndividual* individual,
                                                  ContactsStore* store);
ContactsContactSheet* contacts_contact_sheet_construct (GType object_type,
                                                        FolksIndividual* individual,
                                                        ContactsStore* store);
ContactsContactForm* contacts_contact_form_construct (GType object_type);
static void contacts_contact_sheet_update (ContactsContactSheet* self);
static void _contacts_contact_sheet_update_g_object_notify (GObject* _sender,
                                                     GParamSpec* pspec,
                                                     gpointer self);
static void _contacts_contact_sheet_update_folks_individual_personas_changed (FolksIndividual* _sender,
                                                                       GeeSet* added,
                                                                       GeeSet* removed,
                                                                       gpointer self);
static void _contacts_contact_sheet_update_contacts_store_quiescent (ContactsStore* _sender,
                                                              gpointer self);
static GtkButton* contacts_contact_sheet_add_row_with_button (ContactsContactSheet* self,
                                                       const gchar* label,
                                                       const gchar* value,
                                                       gboolean use_link_button);
static void contacts_contact_sheet_add_row_with_label (ContactsContactSheet* self,
                                                const gchar* label_value,
                                                const gchar* value);
static void __lambda11_ (ContactsContactSheet* self,
                  GtkWidget* child);
static void ___lambda11__gtk_callback (GtkWidget* widget,
                                gpointer self);
GType contacts_avatar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsAvatar, g_object_unref)
#define PROFILE_SIZE 128
ContactsAvatar* contacts_avatar_new (gint size,
                                     FolksIndividual* individual);
ContactsAvatar* contacts_avatar_construct (GType object_type,
                                           gint size,
                                           FolksIndividual* individual);
static void contacts_contact_sheet_create_name_label (ContactsContactSheet* self);
GtkLabel* contacts_contact_form_create_persona_store_label (ContactsContactForm* self,
                                                            FolksPersona* p);
static void contacts_contact_sheet_add_row_for_property (ContactsContactSheet* self,
                                                  FolksPersona* persona,
                                                  const gchar* property);
static void contacts_contact_sheet_update_name_label (ContactsContactSheet* self,
                                               GtkLabel* name_label);
static Block19Data* block19_data_ref (Block19Data* _data19_);
static void block19_data_unref (void * _userdata_);
static void __lambda12_ (Block19Data* _data19_,
                  GObject* obj,
                  GParamSpec* spec);
static void ___lambda12__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void contacts_contact_sheet_add_emails (ContactsContactSheet* self,
                                        FolksPersona* persona);
static void contacts_contact_sheet_add_phone_nrs (ContactsContactSheet* self,
                                           FolksPersona* persona);
static void contacts_contact_sheet_add_im_addresses (ContactsContactSheet* self,
                                              FolksPersona* persona);
static void contacts_contact_sheet_add_urls (ContactsContactSheet* self,
                                      FolksPersona* persona);
static void contacts_contact_sheet_add_nickname (ContactsContactSheet* self,
                                          FolksPersona* persona);
static void contacts_contact_sheet_add_birthday (ContactsContactSheet* self,
                                          FolksPersona* persona);
static void contacts_contact_sheet_add_notes (ContactsContactSheet* self,
                                       FolksPersona* persona);
static void contacts_contact_sheet_add_postal_addresses (ContactsContactSheet* self,
                                                  FolksPersona* persona);
static Block20Data* block20_data_ref (Block20Data* _data20_);
static void block20_data_unref (void * _userdata_);
static void _____lambda13_ (Block20Data* _data20_);
static void ______lambda13__gtk_button_clicked (GtkButton* _sender,
                                         gpointer self);
static GType contacts_contact_sheet_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

extern const gchar* CONTACTS_CONTACT_FORM_SORTED_PROPERTIES[8];

static gpointer
_g_object_ref0 (gpointer self)
{
#line 29 "../src/contacts-contact-sheet.vala"
	return self ? g_object_ref (self) : NULL;
#line 202 "contacts-contact-sheet.c"
}

static void
_contacts_contact_sheet_update_g_object_notify (GObject* _sender,
                                                GParamSpec* pspec,
                                                gpointer self)
{
#line 32 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_update ((ContactsContactSheet*) self);
#line 212 "contacts-contact-sheet.c"
}

static void
_contacts_contact_sheet_update_folks_individual_personas_changed (FolksIndividual* _sender,
                                                                  GeeSet* added,
                                                                  GeeSet* removed,
                                                                  gpointer self)
{
#line 33 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_update ((ContactsContactSheet*) self);
#line 223 "contacts-contact-sheet.c"
}

static void
_contacts_contact_sheet_update_contacts_store_quiescent (ContactsStore* _sender,
                                                         gpointer self)
{
#line 34 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_update ((ContactsContactSheet*) self);
#line 232 "contacts-contact-sheet.c"
}

ContactsContactSheet*
contacts_contact_sheet_construct (GType object_type,
                                  FolksIndividual* individual,
                                  ContactsStore* store)
{
	ContactsContactSheet * self = NULL;
	FolksIndividual* _tmp0_;
	ContactsStore* _tmp1_;
	FolksIndividual* _tmp2_;
	FolksIndividual* _tmp3_;
	ContactsStore* _tmp4_;
#line 28 "../src/contacts-contact-sheet.vala"
	g_return_val_if_fail (individual != NULL, NULL);
#line 28 "../src/contacts-contact-sheet.vala"
	g_return_val_if_fail (store != NULL, NULL);
#line 28 "../src/contacts-contact-sheet.vala"
	self = (ContactsContactSheet*) contacts_contact_form_construct (object_type);
#line 29 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (individual);
#line 29 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (((ContactsContactForm*) self)->individual);
#line 29 "../src/contacts-contact-sheet.vala"
	((ContactsContactForm*) self)->individual = _tmp0_;
#line 30 "../src/contacts-contact-sheet.vala"
	_tmp1_ = _g_object_ref0 (store);
#line 30 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (((ContactsContactForm*) self)->store);
#line 30 "../src/contacts-contact-sheet.vala"
	((ContactsContactForm*) self)->store = _tmp1_;
#line 32 "../src/contacts-contact-sheet.vala"
	_tmp2_ = ((ContactsContactForm*) self)->individual;
#line 32 "../src/contacts-contact-sheet.vala"
	g_signal_connect_object ((GObject*) _tmp2_, "notify", (GCallback) _contacts_contact_sheet_update_g_object_notify, self, 0);
#line 33 "../src/contacts-contact-sheet.vala"
	_tmp3_ = ((ContactsContactForm*) self)->individual;
#line 33 "../src/contacts-contact-sheet.vala"
	g_signal_connect_object (_tmp3_, "personas-changed", (GCallback) _contacts_contact_sheet_update_folks_individual_personas_changed, self, 0);
#line 34 "../src/contacts-contact-sheet.vala"
	_tmp4_ = ((ContactsContactForm*) self)->store;
#line 34 "../src/contacts-contact-sheet.vala"
	g_signal_connect_object (_tmp4_, "quiescent", (GCallback) _contacts_contact_sheet_update_contacts_store_quiescent, self, 0);
#line 36 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_update (self);
#line 28 "../src/contacts-contact-sheet.vala"
	return self;
#line 280 "contacts-contact-sheet.c"
}

ContactsContactSheet*
contacts_contact_sheet_new (FolksIndividual* individual,
                            ContactsStore* store)
{
#line 28 "../src/contacts-contact-sheet.vala"
	return contacts_contact_sheet_construct (CONTACTS_TYPE_CONTACT_SHEET, individual, store);
#line 289 "contacts-contact-sheet.c"
}

static GtkButton*
contacts_contact_sheet_add_row_with_button (ContactsContactSheet* self,
                                            const gchar* label,
                                            const gchar* value,
                                            gboolean use_link_button)
{
	GtkLabel* type_label = NULL;
	GtkLabel* _tmp0_;
	GtkLabel* _tmp1_;
	GtkLabel* _tmp2_;
	GtkLabel* _tmp3_;
	GtkStyleContext* _tmp4_;
	GtkGrid* _tmp5_;
	GtkLabel* _tmp6_;
	GtkButton* _tmp7_ = NULL;
	GtkButton* value_button = NULL;
	GtkButton* _tmp10_;
	GtkGrid* _tmp11_;
	gint _tmp12_;
	GtkWidget* _tmp13_;
	GtkWidget* _tmp14_;
	GtkButton* result = NULL;
#line 39 "../src/contacts-contact-sheet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "../src/contacts-contact-sheet.vala"
	g_return_val_if_fail (label != NULL, NULL);
#line 39 "../src/contacts-contact-sheet.vala"
	g_return_val_if_fail (value != NULL, NULL);
#line 40 "../src/contacts-contact-sheet.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new (label);
#line 40 "../src/contacts-contact-sheet.vala"
	g_object_ref_sink (_tmp0_);
#line 40 "../src/contacts-contact-sheet.vala"
	type_label = _tmp0_;
#line 41 "../src/contacts-contact-sheet.vala"
	_tmp1_ = type_label;
#line 41 "../src/contacts-contact-sheet.vala"
	gtk_label_set_xalign (_tmp1_, 1.0f);
#line 42 "../src/contacts-contact-sheet.vala"
	_tmp2_ = type_label;
#line 42 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp2_, GTK_ALIGN_END);
#line 43 "../src/contacts-contact-sheet.vala"
	_tmp3_ = type_label;
#line 43 "../src/contacts-contact-sheet.vala"
	_tmp4_ = gtk_widget_get_style_context ((GtkWidget*) _tmp3_);
#line 43 "../src/contacts-contact-sheet.vala"
	gtk_style_context_add_class (_tmp4_, "dim-label");
#line 44 "../src/contacts-contact-sheet.vala"
	_tmp5_ = ((ContactsContactForm*) self)->container_grid;
#line 44 "../src/contacts-contact-sheet.vala"
	_tmp6_ = type_label;
#line 44 "../src/contacts-contact-sheet.vala"
	gtk_grid_attach (_tmp5_, (GtkWidget*) _tmp6_, 0, ((ContactsContactForm*) self)->last_row, 1, 1);
#line 46 "../src/contacts-contact-sheet.vala"
	if (use_link_button) {
#line 348 "contacts-contact-sheet.c"
		GtkLinkButton* _tmp8_;
#line 46 "../src/contacts-contact-sheet.vala"
		_tmp8_ = (GtkLinkButton*) gtk_link_button_new (value);
#line 46 "../src/contacts-contact-sheet.vala"
		g_object_ref_sink (_tmp8_);
#line 46 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (_tmp7_);
#line 46 "../src/contacts-contact-sheet.vala"
		_tmp7_ = (GtkButton*) _tmp8_;
#line 358 "contacts-contact-sheet.c"
	} else {
		GtkButton* _tmp9_;
#line 46 "../src/contacts-contact-sheet.vala"
		_tmp9_ = (GtkButton*) gtk_button_new_with_label (value);
#line 46 "../src/contacts-contact-sheet.vala"
		g_object_ref_sink (_tmp9_);
#line 46 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (_tmp7_);
#line 46 "../src/contacts-contact-sheet.vala"
		_tmp7_ = _tmp9_;
#line 369 "contacts-contact-sheet.c"
	}
#line 46 "../src/contacts-contact-sheet.vala"
	_tmp10_ = _g_object_ref0 (_tmp7_);
#line 46 "../src/contacts-contact-sheet.vala"
	value_button = _tmp10_;
#line 47 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_focus_on_click ((GtkWidget*) value_button, FALSE);
#line 48 "../src/contacts-contact-sheet.vala"
	gtk_button_set_relief (value_button, GTK_RELIEF_NONE);
#line 49 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_halign ((GtkWidget*) value_button, GTK_ALIGN_START);
#line 50 "../src/contacts-contact-sheet.vala"
	_tmp11_ = ((ContactsContactForm*) self)->container_grid;
#line 50 "../src/contacts-contact-sheet.vala"
	gtk_grid_attach (_tmp11_, (GtkWidget*) value_button, 1, ((ContactsContactForm*) self)->last_row, 1, 1);
#line 51 "../src/contacts-contact-sheet.vala"
	_tmp12_ = ((ContactsContactForm*) self)->last_row;
#line 51 "../src/contacts-contact-sheet.vala"
	((ContactsContactForm*) self)->last_row = _tmp12_ + 1;
#line 53 "../src/contacts-contact-sheet.vala"
	_tmp13_ = gtk_bin_get_child ((GtkBin*) value_button);
#line 53 "../src/contacts-contact-sheet.vala"
	gtk_label_set_ellipsize (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp13_) : NULL, PANGO_ELLIPSIZE_END);
#line 54 "../src/contacts-contact-sheet.vala"
	_tmp14_ = gtk_bin_get_child ((GtkBin*) value_button);
#line 54 "../src/contacts-contact-sheet.vala"
	g_object_set (G_TYPE_CHECK_INSTANCE_TYPE (_tmp14_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp14_) : NULL, "wrap-mode", PANGO_WRAP_CHAR, NULL);
#line 56 "../src/contacts-contact-sheet.vala"
	result = value_button;
#line 56 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (_tmp7_);
#line 56 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (type_label);
#line 56 "../src/contacts-contact-sheet.vala"
	return result;
#line 405 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_row_with_label (ContactsContactSheet* self,
                                           const gchar* label_value,
                                           const gchar* value)
{
	GtkLabel* type_label = NULL;
	GtkLabel* _tmp0_;
	GtkStyleContext* _tmp1_;
	GtkGrid* _tmp2_;
	GtkLabel* value_label = NULL;
	GtkLabel* _tmp3_;
	GtkGrid* _tmp4_;
	gint _tmp5_;
#line 59 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 59 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (label_value != NULL);
#line 59 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (value != NULL);
#line 60 "../src/contacts-contact-sheet.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new (label_value);
#line 60 "../src/contacts-contact-sheet.vala"
	g_object_ref_sink (_tmp0_);
#line 60 "../src/contacts-contact-sheet.vala"
	type_label = _tmp0_;
#line 61 "../src/contacts-contact-sheet.vala"
	gtk_label_set_xalign (type_label, 1.0f);
#line 62 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_halign ((GtkWidget*) type_label, GTK_ALIGN_END);
#line 63 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_valign ((GtkWidget*) type_label, GTK_ALIGN_START);
#line 64 "../src/contacts-contact-sheet.vala"
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) type_label);
#line 64 "../src/contacts-contact-sheet.vala"
	gtk_style_context_add_class (_tmp1_, "dim-label");
#line 65 "../src/contacts-contact-sheet.vala"
	_tmp2_ = ((ContactsContactForm*) self)->container_grid;
#line 65 "../src/contacts-contact-sheet.vala"
	gtk_grid_attach (_tmp2_, (GtkWidget*) type_label, 0, ((ContactsContactForm*) self)->last_row, 1, 1);
#line 67 "../src/contacts-contact-sheet.vala"
	_tmp3_ = (GtkLabel*) gtk_label_new (value);
#line 67 "../src/contacts-contact-sheet.vala"
	g_object_ref_sink (_tmp3_);
#line 67 "../src/contacts-contact-sheet.vala"
	value_label = _tmp3_;
#line 68 "../src/contacts-contact-sheet.vala"
	gtk_label_set_line_wrap (value_label, TRUE);
#line 69 "../src/contacts-contact-sheet.vala"
	gtk_label_set_xalign (value_label, 0.0f);
#line 70 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_halign ((GtkWidget*) value_label, GTK_ALIGN_START);
#line 71 "../src/contacts-contact-sheet.vala"
	gtk_label_set_ellipsize (value_label, PANGO_ELLIPSIZE_END);
#line 72 "../src/contacts-contact-sheet.vala"
	g_object_set (value_label, "wrap-mode", PANGO_WRAP_CHAR, NULL);
#line 73 "../src/contacts-contact-sheet.vala"
	gtk_label_set_selectable (value_label, TRUE);
#line 76 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_margin_top ((GtkWidget*) type_label, 3);
#line 77 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_margin_start ((GtkWidget*) value_label, 6);
#line 78 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_margin_top ((GtkWidget*) value_label, 3);
#line 79 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_margin_bottom ((GtkWidget*) value_label, 3);
#line 81 "../src/contacts-contact-sheet.vala"
	_tmp4_ = ((ContactsContactForm*) self)->container_grid;
#line 81 "../src/contacts-contact-sheet.vala"
	gtk_grid_attach (_tmp4_, (GtkWidget*) value_label, 1, ((ContactsContactForm*) self)->last_row, 1, 1);
#line 82 "../src/contacts-contact-sheet.vala"
	_tmp5_ = ((ContactsContactForm*) self)->last_row;
#line 82 "../src/contacts-contact-sheet.vala"
	((ContactsContactForm*) self)->last_row = _tmp5_ + 1;
#line 59 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (value_label);
#line 59 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (type_label);
#line 485 "contacts-contact-sheet.c"
}

static void
__lambda11_ (ContactsContactSheet* self,
             GtkWidget* child)
{
	GtkGrid* _tmp0_;
#line 87 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (child != NULL);
#line 87 "../src/contacts-contact-sheet.vala"
	_tmp0_ = ((ContactsContactForm*) self)->container_grid;
#line 87 "../src/contacts-contact-sheet.vala"
	gtk_container_remove ((GtkContainer*) _tmp0_, child);
#line 499 "contacts-contact-sheet.c"
}

static void
___lambda11__gtk_callback (GtkWidget* widget,
                           gpointer self)
{
#line 87 "../src/contacts-contact-sheet.vala"
	__lambda11_ ((ContactsContactSheet*) self, widget);
#line 508 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_update (ContactsContactSheet* self)
{
	GtkGrid* _tmp0_;
	ContactsAvatar* image_frame = NULL;
	FolksIndividual* _tmp1_;
	ContactsAvatar* _tmp2_;
	ContactsAvatar* _tmp3_;
	ContactsAvatar* _tmp4_;
	GtkGrid* _tmp5_;
	ContactsAvatar* _tmp6_;
	GeeList* personas = NULL;
	FolksIndividual* _tmp7_;
	GeeList* _tmp8_;
#line 85 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 86 "../src/contacts-contact-sheet.vala"
	((ContactsContactForm*) self)->last_row = 0;
#line 87 "../src/contacts-contact-sheet.vala"
	_tmp0_ = ((ContactsContactForm*) self)->container_grid;
#line 87 "../src/contacts-contact-sheet.vala"
	gtk_container_foreach ((GtkContainer*) _tmp0_, ___lambda11__gtk_callback, self);
#line 89 "../src/contacts-contact-sheet.vala"
	_tmp1_ = ((ContactsContactForm*) self)->individual;
#line 89 "../src/contacts-contact-sheet.vala"
	_tmp2_ = contacts_avatar_new (PROFILE_SIZE, _tmp1_);
#line 89 "../src/contacts-contact-sheet.vala"
	g_object_ref_sink (_tmp2_);
#line 89 "../src/contacts-contact-sheet.vala"
	image_frame = _tmp2_;
#line 90 "../src/contacts-contact-sheet.vala"
	_tmp3_ = image_frame;
#line 90 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp3_, FALSE);
#line 91 "../src/contacts-contact-sheet.vala"
	_tmp4_ = image_frame;
#line 91 "../src/contacts-contact-sheet.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp4_, GTK_ALIGN_START);
#line 92 "../src/contacts-contact-sheet.vala"
	_tmp5_ = ((ContactsContactForm*) self)->container_grid;
#line 92 "../src/contacts-contact-sheet.vala"
	_tmp6_ = image_frame;
#line 92 "../src/contacts-contact-sheet.vala"
	gtk_grid_attach (_tmp5_, (GtkWidget*) _tmp6_, 0, 0, 1, 3);
#line 94 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_create_name_label (self);
#line 96 "../src/contacts-contact-sheet.vala"
	((ContactsContactForm*) self)->last_row = ((ContactsContactForm*) self)->last_row + 3;
#line 98 "../src/contacts-contact-sheet.vala"
	_tmp7_ = ((ContactsContactForm*) self)->individual;
#line 98 "../src/contacts-contact-sheet.vala"
	_tmp8_ = contacts_utils_get_personas_for_display (_tmp7_);
#line 98 "../src/contacts-contact-sheet.vala"
	personas = _tmp8_;
#line 565 "contacts-contact-sheet.c"
	{
		GeeList* _p_list = NULL;
		GeeList* _tmp9_;
		GeeList* _tmp10_;
		gint _p_size = 0;
		GeeList* _tmp11_;
		gint _tmp12_;
		gint _tmp13_;
		gint _p_index = 0;
#line 100 "../src/contacts-contact-sheet.vala"
		_tmp9_ = personas;
#line 100 "../src/contacts-contact-sheet.vala"
		_tmp10_ = _g_object_ref0 (_tmp9_);
#line 100 "../src/contacts-contact-sheet.vala"
		_p_list = _tmp10_;
#line 100 "../src/contacts-contact-sheet.vala"
		_tmp11_ = _p_list;
#line 100 "../src/contacts-contact-sheet.vala"
		_tmp12_ = gee_collection_get_size ((GeeCollection*) _tmp11_);
#line 100 "../src/contacts-contact-sheet.vala"
		_tmp13_ = _tmp12_;
#line 100 "../src/contacts-contact-sheet.vala"
		_p_size = _tmp13_;
#line 100 "../src/contacts-contact-sheet.vala"
		_p_index = -1;
#line 100 "../src/contacts-contact-sheet.vala"
		while (TRUE) {
#line 593 "contacts-contact-sheet.c"
			FolksPersona* p = NULL;
			GeeList* _tmp14_;
			gpointer _tmp15_;
			gboolean is_first_persona = FALSE;
			gint persona_store_pos = 0;
			gboolean is_empty_persona = FALSE;
			gboolean _tmp23_ = FALSE;
#line 100 "../src/contacts-contact-sheet.vala"
			_p_index = _p_index + 1;
#line 100 "../src/contacts-contact-sheet.vala"
			if (!(_p_index < _p_size)) {
#line 100 "../src/contacts-contact-sheet.vala"
				break;
#line 607 "contacts-contact-sheet.c"
			}
#line 100 "../src/contacts-contact-sheet.vala"
			_tmp14_ = _p_list;
#line 100 "../src/contacts-contact-sheet.vala"
			_tmp15_ = gee_list_get (_tmp14_, _p_index);
#line 100 "../src/contacts-contact-sheet.vala"
			p = (FolksPersona*) _tmp15_;
#line 101 "../src/contacts-contact-sheet.vala"
			is_first_persona = ((ContactsContactForm*) self)->last_row == 3;
#line 102 "../src/contacts-contact-sheet.vala"
			persona_store_pos = ((ContactsContactForm*) self)->last_row;
#line 103 "../src/contacts-contact-sheet.vala"
			if (!is_first_persona) {
#line 621 "contacts-contact-sheet.c"
				GtkGrid* _tmp16_;
				FolksPersona* _tmp17_;
				GtkLabel* _tmp18_;
				GtkLabel* _tmp19_;
				gint _tmp20_;
#line 104 "../src/contacts-contact-sheet.vala"
				_tmp16_ = ((ContactsContactForm*) self)->container_grid;
#line 104 "../src/contacts-contact-sheet.vala"
				_tmp17_ = p;
#line 104 "../src/contacts-contact-sheet.vala"
				_tmp18_ = contacts_contact_form_create_persona_store_label ((ContactsContactForm*) self, _tmp17_);
#line 104 "../src/contacts-contact-sheet.vala"
				_tmp19_ = _tmp18_;
#line 104 "../src/contacts-contact-sheet.vala"
				gtk_grid_attach (_tmp16_, (GtkWidget*) _tmp19_, 0, ((ContactsContactForm*) self)->last_row, 3, 1);
#line 104 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (_tmp19_);
#line 105 "../src/contacts-contact-sheet.vala"
				_tmp20_ = ((ContactsContactForm*) self)->last_row;
#line 105 "../src/contacts-contact-sheet.vala"
				((ContactsContactForm*) self)->last_row = _tmp20_ + 1;
#line 643 "contacts-contact-sheet.c"
			}
			{
				const gchar** prop_collection = NULL;
				gint prop_collection_length1 = 0;
				gint _prop_collection_size_ = 0;
				gint prop_it = 0;
#line 108 "../src/contacts-contact-sheet.vala"
				prop_collection = CONTACTS_CONTACT_FORM_SORTED_PROPERTIES;
#line 108 "../src/contacts-contact-sheet.vala"
				prop_collection_length1 = G_N_ELEMENTS (CONTACTS_CONTACT_FORM_SORTED_PROPERTIES);
#line 108 "../src/contacts-contact-sheet.vala"
				for (prop_it = 0; prop_it < prop_collection_length1; prop_it = prop_it + 1) {
#line 656 "contacts-contact-sheet.c"
					const gchar* prop = NULL;
#line 108 "../src/contacts-contact-sheet.vala"
					prop = prop_collection[prop_it];
#line 660 "contacts-contact-sheet.c"
					{
						FolksPersona* _tmp21_;
						const gchar* _tmp22_;
#line 109 "../src/contacts-contact-sheet.vala"
						_tmp21_ = p;
#line 109 "../src/contacts-contact-sheet.vala"
						_tmp22_ = prop;
#line 109 "../src/contacts-contact-sheet.vala"
						contacts_contact_sheet_add_row_for_property (self, _tmp21_, _tmp22_);
#line 670 "contacts-contact-sheet.c"
					}
				}
			}
#line 112 "../src/contacts-contact-sheet.vala"
			is_empty_persona = ((ContactsContactForm*) self)->last_row == (persona_store_pos + 1);
#line 113 "../src/contacts-contact-sheet.vala"
			if (!is_first_persona) {
#line 113 "../src/contacts-contact-sheet.vala"
				_tmp23_ = is_empty_persona;
#line 680 "contacts-contact-sheet.c"
			} else {
#line 113 "../src/contacts-contact-sheet.vala"
				_tmp23_ = FALSE;
#line 684 "contacts-contact-sheet.c"
			}
#line 113 "../src/contacts-contact-sheet.vala"
			if (_tmp23_) {
#line 688 "contacts-contact-sheet.c"
				GtkGrid* _tmp24_;
				gint _tmp25_;
#line 114 "../src/contacts-contact-sheet.vala"
				_tmp24_ = ((ContactsContactForm*) self)->container_grid;
#line 114 "../src/contacts-contact-sheet.vala"
				gtk_grid_remove_row (_tmp24_, persona_store_pos);
#line 115 "../src/contacts-contact-sheet.vala"
				_tmp25_ = ((ContactsContactForm*) self)->last_row;
#line 115 "../src/contacts-contact-sheet.vala"
				((ContactsContactForm*) self)->last_row = _tmp25_ - 1;
#line 699 "contacts-contact-sheet.c"
			}
#line 100 "../src/contacts-contact-sheet.vala"
			_g_object_unref0 (p);
#line 703 "contacts-contact-sheet.c"
		}
#line 100 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (_p_list);
#line 707 "contacts-contact-sheet.c"
	}
#line 119 "../src/contacts-contact-sheet.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 85 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (personas);
#line 85 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (image_frame);
#line 715 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_update_name_label (ContactsContactSheet* self,
                                          GtkLabel* name_label)
{
	gchar* name = NULL;
	FolksIndividual* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
#line 122 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 122 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (name_label != NULL);
#line 123 "../src/contacts-contact-sheet.vala"
	_tmp0_ = ((ContactsContactForm*) self)->individual;
#line 123 "../src/contacts-contact-sheet.vala"
	_tmp1_ = folks_individual_get_display_name (_tmp0_);
#line 123 "../src/contacts-contact-sheet.vala"
	_tmp2_ = _tmp1_;
#line 123 "../src/contacts-contact-sheet.vala"
	_tmp3_ = g_markup_printf_escaped ("<span font='16'>%s</span>", _tmp2_);
#line 123 "../src/contacts-contact-sheet.vala"
	name = _tmp3_;
#line 125 "../src/contacts-contact-sheet.vala"
	gtk_label_set_markup (name_label, name);
#line 122 "../src/contacts-contact-sheet.vala"
	_g_free0 (name);
#line 745 "contacts-contact-sheet.c"
}

static Block19Data*
block19_data_ref (Block19Data* _data19_)
{
#line 128 "../src/contacts-contact-sheet.vala"
	g_atomic_int_inc (&_data19_->_ref_count_);
#line 128 "../src/contacts-contact-sheet.vala"
	return _data19_;
#line 755 "contacts-contact-sheet.c"
}

static void
block19_data_unref (void * _userdata_)
{
	Block19Data* _data19_;
	_data19_ = (Block19Data*) _userdata_;
#line 128 "../src/contacts-contact-sheet.vala"
	if (g_atomic_int_dec_and_test (&_data19_->_ref_count_)) {
#line 765 "contacts-contact-sheet.c"
		ContactsContactSheet* self;
#line 128 "../src/contacts-contact-sheet.vala"
		self = _data19_->self;
#line 128 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (_data19_->name_label);
#line 128 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (self);
#line 128 "../src/contacts-contact-sheet.vala"
		g_slice_free (Block19Data, _data19_);
#line 775 "contacts-contact-sheet.c"
	}
}

static void
__lambda12_ (Block19Data* _data19_,
             GObject* obj,
             GParamSpec* spec)
{
	ContactsContactSheet* self;
#line 135 "../src/contacts-contact-sheet.vala"
	self = _data19_->self;
#line 135 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (obj != NULL);
#line 135 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (spec != NULL);
#line 136 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_update_name_label (self, _data19_->name_label);
#line 793 "contacts-contact-sheet.c"
}

static void
___lambda12__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 135 "../src/contacts-contact-sheet.vala"
	__lambda12_ (self, _sender, pspec);
#line 803 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_create_name_label (ContactsContactSheet* self)
{
	Block19Data* _data19_;
	GtkLabel* _tmp0_;
	GtkGrid* _tmp1_;
	FolksIndividual* _tmp2_;
#line 128 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 128 "../src/contacts-contact-sheet.vala"
	_data19_ = g_slice_new0 (Block19Data);
#line 128 "../src/contacts-contact-sheet.vala"
	_data19_->_ref_count_ = 1;
#line 128 "../src/contacts-contact-sheet.vala"
	_data19_->self = g_object_ref (self);
#line 129 "../src/contacts-contact-sheet.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new ("");
#line 129 "../src/contacts-contact-sheet.vala"
	g_object_ref_sink (_tmp0_);
#line 129 "../src/contacts-contact-sheet.vala"
	_data19_->name_label = _tmp0_;
#line 130 "../src/contacts-contact-sheet.vala"
	gtk_label_set_ellipsize (_data19_->name_label, PANGO_ELLIPSIZE_END);
#line 131 "../src/contacts-contact-sheet.vala"
	gtk_label_set_xalign (_data19_->name_label, 0.f);
#line 132 "../src/contacts-contact-sheet.vala"
	gtk_label_set_selectable (_data19_->name_label, TRUE);
#line 133 "../src/contacts-contact-sheet.vala"
	_tmp1_ = ((ContactsContactForm*) self)->container_grid;
#line 133 "../src/contacts-contact-sheet.vala"
	gtk_grid_attach (_tmp1_, (GtkWidget*) _data19_->name_label, 1, 0, 1, 3);
#line 134 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_update_name_label (self, _data19_->name_label);
#line 135 "../src/contacts-contact-sheet.vala"
	_tmp2_ = ((ContactsContactForm*) self)->individual;
#line 135 "../src/contacts-contact-sheet.vala"
	g_signal_connect_data ((GObject*) _tmp2_, "notify::display-name", (GCallback) ___lambda12__g_object_notify, block19_data_ref (_data19_), (GClosureNotify) block19_data_unref, 0);
#line 128 "../src/contacts-contact-sheet.vala"
	block19_data_unref (_data19_);
#line 128 "../src/contacts-contact-sheet.vala"
	_data19_ = NULL;
#line 847 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_row_for_property (ContactsContactSheet* self,
                                             FolksPersona* persona,
                                             const gchar* property)
{
	const gchar* _tmp0_;
	GQuark _tmp2_ = 0U;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label0 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label1 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label2 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label3 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label4 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label5 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label6 = 0;
#line 141 "../src/contacts-contact-sheet.vala"
	static GQuark _tmp1_label7 = 0;
#line 140 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 140 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 140 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (property != NULL);
#line 141 "../src/contacts-contact-sheet.vala"
	_tmp0_ = property;
#line 141 "../src/contacts-contact-sheet.vala"
	_tmp2_ = (NULL == _tmp0_) ? 0 : g_quark_from_string (_tmp0_);
#line 141 "../src/contacts-contact-sheet.vala"
	if (_tmp2_ == ((0 != _tmp1_label0) ? _tmp1_label0 : (_tmp1_label0 = g_quark_from_static_string ("email-addresses")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 887 "contacts-contact-sheet.c"
			default:
			{
#line 143 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_emails (self, persona);
#line 144 "../src/contacts-contact-sheet.vala"
				break;
#line 894 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label1) ? _tmp1_label1 : (_tmp1_label1 = g_quark_from_static_string ("phone-numbers")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 900 "contacts-contact-sheet.c"
			default:
			{
#line 146 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_phone_nrs (self, persona);
#line 147 "../src/contacts-contact-sheet.vala"
				break;
#line 907 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label2) ? _tmp1_label2 : (_tmp1_label2 = g_quark_from_static_string ("im-addresses")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 913 "contacts-contact-sheet.c"
			default:
			{
#line 149 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_im_addresses (self, persona);
#line 150 "../src/contacts-contact-sheet.vala"
				break;
#line 920 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label3) ? _tmp1_label3 : (_tmp1_label3 = g_quark_from_static_string ("urls")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 926 "contacts-contact-sheet.c"
			default:
			{
#line 152 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_urls (self, persona);
#line 153 "../src/contacts-contact-sheet.vala"
				break;
#line 933 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label4) ? _tmp1_label4 : (_tmp1_label4 = g_quark_from_static_string ("nickname")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 939 "contacts-contact-sheet.c"
			default:
			{
#line 155 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_nickname (self, persona);
#line 156 "../src/contacts-contact-sheet.vala"
				break;
#line 946 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label5) ? _tmp1_label5 : (_tmp1_label5 = g_quark_from_static_string ("birthday")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 952 "contacts-contact-sheet.c"
			default:
			{
#line 158 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_birthday (self, persona);
#line 159 "../src/contacts-contact-sheet.vala"
				break;
#line 959 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label6) ? _tmp1_label6 : (_tmp1_label6 = g_quark_from_static_string ("notes")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 965 "contacts-contact-sheet.c"
			default:
			{
#line 161 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_notes (self, persona);
#line 162 "../src/contacts-contact-sheet.vala"
				break;
#line 972 "contacts-contact-sheet.c"
			}
		}
	} else if (_tmp2_ == ((0 != _tmp1_label7) ? _tmp1_label7 : (_tmp1_label7 = g_quark_from_static_string ("postal-addresses")))) {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 978 "contacts-contact-sheet.c"
			default:
			{
#line 164 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_postal_addresses (self, persona);
#line 165 "../src/contacts-contact-sheet.vala"
				break;
#line 985 "contacts-contact-sheet.c"
			}
		}
	} else {
#line 141 "../src/contacts-contact-sheet.vala"
		switch (0) {
#line 991 "contacts-contact-sheet.c"
			default:
			{
#line 167 "../src/contacts-contact-sheet.vala"
				g_debug ("contacts-contact-sheet.vala:167: Unsupported property: %s", property);
#line 168 "../src/contacts-contact-sheet.vala"
				break;
#line 998 "contacts-contact-sheet.c"
			}
		}
	}
}

static Block20Data*
block20_data_ref (Block20Data* _data20_)
{
#line 176 "../src/contacts-contact-sheet.vala"
	g_atomic_int_inc (&_data20_->_ref_count_);
#line 176 "../src/contacts-contact-sheet.vala"
	return _data20_;
#line 1011 "contacts-contact-sheet.c"
}

static void
block20_data_unref (void * _userdata_)
{
	Block20Data* _data20_;
	_data20_ = (Block20Data*) _userdata_;
#line 176 "../src/contacts-contact-sheet.vala"
	if (g_atomic_int_dec_and_test (&_data20_->_ref_count_)) {
#line 1021 "contacts-contact-sheet.c"
		ContactsContactSheet* self;
#line 176 "../src/contacts-contact-sheet.vala"
		self = _data20_->self;
#line 176 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (_data20_->email);
#line 176 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (self);
#line 176 "../src/contacts-contact-sheet.vala"
		g_slice_free (Block20Data, _data20_);
#line 1031 "contacts-contact-sheet.c"
	}
}

static void
_____lambda13_ (Block20Data* _data20_)
{
	ContactsContactSheet* self;
	FolksIndividual* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	FolksEmailFieldDetails* _tmp3_;
	gconstpointer _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
#line 178 "../src/contacts-contact-sheet.vala"
	self = _data20_->self;
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp0_ = ((ContactsContactForm*) self)->individual;
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp1_ = folks_individual_get_display_name (_tmp0_);
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp2_ = _tmp1_;
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp3_ = _data20_->email;
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp4_ = folks_abstract_field_details_get_value ((FolksAbstractFieldDetails*) _tmp3_);
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp5_ = _tmp4_;
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp6_ = g_strdup_printf ("%s <%s>", _tmp2_, (const gchar*) _tmp5_);
#line 179 "../src/contacts-contact-sheet.vala"
	_tmp7_ = _tmp6_;
#line 179 "../src/contacts-contact-sheet.vala"
	contacts_utils_compose_mail (_tmp7_);
#line 179 "../src/contacts-contact-sheet.vala"
	_g_free0 (_tmp7_);
#line 1069 "contacts-contact-sheet.c"
}

static void
______lambda13__gtk_button_clicked (GtkButton* _sender,
                                    gpointer self)
{
#line 178 "../src/contacts-contact-sheet.vala"
	_____lambda13_ (self);
#line 1078 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_emails (ContactsContactSheet* self,
                                   FolksPersona* persona)
{
	FolksEmailDetails* details = NULL;
	FolksEmailDetails* _tmp0_;
	FolksEmailDetails* _tmp1_;
#line 172 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 172 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 173 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_EMAIL_DETAILS) ? ((FolksEmailDetails*) persona) : NULL);
#line 173 "../src/contacts-contact-sheet.vala"
	details = _tmp0_;
#line 174 "../src/contacts-contact-sheet.vala"
	_tmp1_ = details;
#line 174 "../src/contacts-contact-sheet.vala"
	if (_tmp1_ != NULL) {
#line 1100 "contacts-contact-sheet.c"
		GeeList* emails = NULL;
		FolksEmailDetails* _tmp2_;
		GeeSet* _tmp3_;
		GeeSet* _tmp4_;
		GeeList* _tmp5_;
#line 175 "../src/contacts-contact-sheet.vala"
		_tmp2_ = details;
#line 175 "../src/contacts-contact-sheet.vala"
		_tmp3_ = folks_email_details_get_email_addresses (_tmp2_);
#line 175 "../src/contacts-contact-sheet.vala"
		_tmp4_ = _tmp3_;
#line 175 "../src/contacts-contact-sheet.vala"
		_tmp5_ = contacts_utils_sort_fields (FOLKS_TYPE_EMAIL_FIELD_DETAILS, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, (GeeCollection*) _tmp4_);
#line 175 "../src/contacts-contact-sheet.vala"
		emails = _tmp5_;
#line 1116 "contacts-contact-sheet.c"
		{
			GeeList* _email_list = NULL;
			GeeList* _tmp6_;
			GeeList* _tmp7_;
			gint _email_size = 0;
			GeeList* _tmp8_;
			gint _tmp9_;
			gint _tmp10_;
			gint _email_index = 0;
#line 176 "../src/contacts-contact-sheet.vala"
			_tmp6_ = emails;
#line 176 "../src/contacts-contact-sheet.vala"
			_tmp7_ = _g_object_ref0 (_tmp6_);
#line 176 "../src/contacts-contact-sheet.vala"
			_email_list = _tmp7_;
#line 176 "../src/contacts-contact-sheet.vala"
			_tmp8_ = _email_list;
#line 176 "../src/contacts-contact-sheet.vala"
			_tmp9_ = gee_collection_get_size ((GeeCollection*) _tmp8_);
#line 176 "../src/contacts-contact-sheet.vala"
			_tmp10_ = _tmp9_;
#line 176 "../src/contacts-contact-sheet.vala"
			_email_size = _tmp10_;
#line 176 "../src/contacts-contact-sheet.vala"
			_email_index = -1;
#line 176 "../src/contacts-contact-sheet.vala"
			while (TRUE) {
#line 1144 "contacts-contact-sheet.c"
				Block20Data* _data20_;
				GeeList* _tmp11_;
				gpointer _tmp12_;
				GtkButton* button = NULL;
				ContactsTypeSet* _tmp13_;
				ContactsTypeSet* _tmp14_;
				FolksEmailFieldDetails* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				FolksEmailFieldDetails* _tmp18_;
				gconstpointer _tmp19_;
				const gchar* _tmp20_;
				GtkButton* _tmp21_;
				GtkButton* _tmp22_;
				GtkButton* _tmp23_;
#line 176 "../src/contacts-contact-sheet.vala"
				_data20_ = g_slice_new0 (Block20Data);
#line 176 "../src/contacts-contact-sheet.vala"
				_data20_->_ref_count_ = 1;
#line 176 "../src/contacts-contact-sheet.vala"
				_data20_->self = g_object_ref (self);
#line 176 "../src/contacts-contact-sheet.vala"
				_email_index = _email_index + 1;
#line 176 "../src/contacts-contact-sheet.vala"
				if (!(_email_index < _email_size)) {
#line 176 "../src/contacts-contact-sheet.vala"
					block20_data_unref (_data20_);
#line 176 "../src/contacts-contact-sheet.vala"
					_data20_ = NULL;
#line 176 "../src/contacts-contact-sheet.vala"
					break;
#line 1176 "contacts-contact-sheet.c"
				}
#line 176 "../src/contacts-contact-sheet.vala"
				_tmp11_ = _email_list;
#line 176 "../src/contacts-contact-sheet.vala"
				_tmp12_ = gee_list_get (_tmp11_, _email_index);
#line 176 "../src/contacts-contact-sheet.vala"
				_data20_->email = (FolksEmailFieldDetails*) _tmp12_;
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp13_ = contacts_typeset_get_email ();
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp14_ = _tmp13_;
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp15_ = _data20_->email;
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp16_ = contacts_typeset_format_type (_tmp14_, (FolksAbstractFieldDetails*) _tmp15_);
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp17_ = _tmp16_;
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp18_ = _data20_->email;
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp19_ = folks_abstract_field_details_get_value ((FolksAbstractFieldDetails*) _tmp18_);
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp20_ = _tmp19_;
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp21_ = contacts_contact_sheet_add_row_with_button (self, _tmp17_, (const gchar*) _tmp20_, FALSE);
#line 177 "../src/contacts-contact-sheet.vala"
				_tmp22_ = _tmp21_;
#line 177 "../src/contacts-contact-sheet.vala"
				_g_free0 (_tmp17_);
#line 177 "../src/contacts-contact-sheet.vala"
				button = _tmp22_;
#line 178 "../src/contacts-contact-sheet.vala"
				_tmp23_ = button;
#line 178 "../src/contacts-contact-sheet.vala"
				g_signal_connect_data (_tmp23_, "clicked", (GCallback) ______lambda13__gtk_button_clicked, block20_data_ref (_data20_), (GClosureNotify) block20_data_unref, 0);
#line 176 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (button);
#line 176 "../src/contacts-contact-sheet.vala"
				block20_data_unref (_data20_);
#line 176 "../src/contacts-contact-sheet.vala"
				_data20_ = NULL;
#line 1218 "contacts-contact-sheet.c"
			}
#line 176 "../src/contacts-contact-sheet.vala"
			_g_object_unref0 (_email_list);
#line 1222 "contacts-contact-sheet.c"
		}
#line 174 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (emails);
#line 1226 "contacts-contact-sheet.c"
	}
#line 172 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (details);
#line 1230 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_phone_nrs (ContactsContactSheet* self,
                                      FolksPersona* persona)
{
	FolksPhoneDetails* phone_details = NULL;
	FolksPhoneDetails* _tmp0_;
	FolksPhoneDetails* _tmp1_;
#line 185 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 185 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 186 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_PHONE_DETAILS) ? ((FolksPhoneDetails*) persona) : NULL);
#line 186 "../src/contacts-contact-sheet.vala"
	phone_details = _tmp0_;
#line 187 "../src/contacts-contact-sheet.vala"
	_tmp1_ = phone_details;
#line 187 "../src/contacts-contact-sheet.vala"
	if (_tmp1_ != NULL) {
#line 1252 "contacts-contact-sheet.c"
		GeeList* phones = NULL;
		FolksPhoneDetails* _tmp2_;
		GeeSet* _tmp3_;
		GeeSet* _tmp4_;
		GeeList* _tmp5_;
#line 188 "../src/contacts-contact-sheet.vala"
		_tmp2_ = phone_details;
#line 188 "../src/contacts-contact-sheet.vala"
		_tmp3_ = folks_phone_details_get_phone_numbers (_tmp2_);
#line 188 "../src/contacts-contact-sheet.vala"
		_tmp4_ = _tmp3_;
#line 188 "../src/contacts-contact-sheet.vala"
		_tmp5_ = contacts_utils_sort_fields (FOLKS_TYPE_PHONE_FIELD_DETAILS, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, (GeeCollection*) _tmp4_);
#line 188 "../src/contacts-contact-sheet.vala"
		phones = _tmp5_;
#line 1268 "contacts-contact-sheet.c"
		{
			GeeList* _phone_list = NULL;
			GeeList* _tmp6_;
			GeeList* _tmp7_;
			gint _phone_size = 0;
			GeeList* _tmp8_;
			gint _tmp9_;
			gint _tmp10_;
			gint _phone_index = 0;
#line 189 "../src/contacts-contact-sheet.vala"
			_tmp6_ = phones;
#line 189 "../src/contacts-contact-sheet.vala"
			_tmp7_ = _g_object_ref0 (_tmp6_);
#line 189 "../src/contacts-contact-sheet.vala"
			_phone_list = _tmp7_;
#line 189 "../src/contacts-contact-sheet.vala"
			_tmp8_ = _phone_list;
#line 189 "../src/contacts-contact-sheet.vala"
			_tmp9_ = gee_collection_get_size ((GeeCollection*) _tmp8_);
#line 189 "../src/contacts-contact-sheet.vala"
			_tmp10_ = _tmp9_;
#line 189 "../src/contacts-contact-sheet.vala"
			_phone_size = _tmp10_;
#line 189 "../src/contacts-contact-sheet.vala"
			_phone_index = -1;
#line 189 "../src/contacts-contact-sheet.vala"
			while (TRUE) {
#line 1296 "contacts-contact-sheet.c"
				FolksPhoneFieldDetails* phone = NULL;
				GeeList* _tmp11_;
				gpointer _tmp12_;
				ContactsTypeSet* _tmp13_;
				ContactsTypeSet* _tmp14_;
				FolksPhoneFieldDetails* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				FolksPhoneFieldDetails* _tmp18_;
				gconstpointer _tmp19_;
				const gchar* _tmp20_;
#line 189 "../src/contacts-contact-sheet.vala"
				_phone_index = _phone_index + 1;
#line 189 "../src/contacts-contact-sheet.vala"
				if (!(_phone_index < _phone_size)) {
#line 189 "../src/contacts-contact-sheet.vala"
					break;
#line 1314 "contacts-contact-sheet.c"
				}
#line 189 "../src/contacts-contact-sheet.vala"
				_tmp11_ = _phone_list;
#line 189 "../src/contacts-contact-sheet.vala"
				_tmp12_ = gee_list_get (_tmp11_, _phone_index);
#line 189 "../src/contacts-contact-sheet.vala"
				phone = (FolksPhoneFieldDetails*) _tmp12_;
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp13_ = contacts_typeset_get_phone ();
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp14_ = _tmp13_;
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp15_ = phone;
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp16_ = contacts_typeset_format_type (_tmp14_, (FolksAbstractFieldDetails*) _tmp15_);
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp17_ = _tmp16_;
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp18_ = phone;
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp19_ = folks_abstract_field_details_get_value ((FolksAbstractFieldDetails*) _tmp18_);
#line 200 "../src/contacts-contact-sheet.vala"
				_tmp20_ = _tmp19_;
#line 200 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_row_with_label (self, _tmp17_, (const gchar*) _tmp20_);
#line 200 "../src/contacts-contact-sheet.vala"
				_g_free0 (_tmp17_);
#line 189 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (phone);
#line 1344 "contacts-contact-sheet.c"
			}
#line 189 "../src/contacts-contact-sheet.vala"
			_g_object_unref0 (_phone_list);
#line 1348 "contacts-contact-sheet.c"
		}
#line 187 "../src/contacts-contact-sheet.vala"
		_g_object_unref0 (phones);
#line 1352 "contacts-contact-sheet.c"
	}
#line 185 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (phone_details);
#line 1356 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_im_addresses (ContactsContactSheet* self,
                                         FolksPersona* persona)
{
#line 206 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 206 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 1367 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_urls (ContactsContactSheet* self,
                                 FolksPersona* persona)
{
	FolksUrlDetails* url_details = NULL;
	FolksUrlDetails* _tmp0_;
	FolksUrlDetails* _tmp1_;
#line 230 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 230 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 231 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_URL_DETAILS) ? ((FolksUrlDetails*) persona) : NULL);
#line 231 "../src/contacts-contact-sheet.vala"
	url_details = _tmp0_;
#line 232 "../src/contacts-contact-sheet.vala"
	_tmp1_ = url_details;
#line 232 "../src/contacts-contact-sheet.vala"
	if (_tmp1_ != NULL) {
#line 1389 "contacts-contact-sheet.c"
		{
			GeeIterator* _url_it = NULL;
			FolksUrlDetails* _tmp2_;
			GeeSet* _tmp3_;
			GeeSet* _tmp4_;
			GeeIterator* _tmp5_;
#line 233 "../src/contacts-contact-sheet.vala"
			_tmp2_ = url_details;
#line 233 "../src/contacts-contact-sheet.vala"
			_tmp3_ = folks_url_details_get_urls (_tmp2_);
#line 233 "../src/contacts-contact-sheet.vala"
			_tmp4_ = _tmp3_;
#line 233 "../src/contacts-contact-sheet.vala"
			_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 233 "../src/contacts-contact-sheet.vala"
			_url_it = _tmp5_;
#line 233 "../src/contacts-contact-sheet.vala"
			while (TRUE) {
#line 1408 "contacts-contact-sheet.c"
				GeeIterator* _tmp6_;
				FolksUrlFieldDetails* url = NULL;
				GeeIterator* _tmp7_;
				gpointer _tmp8_;
				FolksUrlFieldDetails* _tmp9_;
				gconstpointer _tmp10_;
				const gchar* _tmp11_;
				GtkButton* _tmp12_;
				GtkButton* _tmp13_;
#line 233 "../src/contacts-contact-sheet.vala"
				_tmp6_ = _url_it;
#line 233 "../src/contacts-contact-sheet.vala"
				if (!gee_iterator_next (_tmp6_)) {
#line 233 "../src/contacts-contact-sheet.vala"
					break;
#line 1424 "contacts-contact-sheet.c"
				}
#line 233 "../src/contacts-contact-sheet.vala"
				_tmp7_ = _url_it;
#line 233 "../src/contacts-contact-sheet.vala"
				_tmp8_ = gee_iterator_get (_tmp7_);
#line 233 "../src/contacts-contact-sheet.vala"
				url = (FolksUrlFieldDetails*) _tmp8_;
#line 234 "../src/contacts-contact-sheet.vala"
				_tmp9_ = url;
#line 234 "../src/contacts-contact-sheet.vala"
				_tmp10_ = folks_abstract_field_details_get_value ((FolksAbstractFieldDetails*) _tmp9_);
#line 234 "../src/contacts-contact-sheet.vala"
				_tmp11_ = _tmp10_;
#line 234 "../src/contacts-contact-sheet.vala"
				_tmp12_ = contacts_contact_sheet_add_row_with_button (self, _ ("Website"), (const gchar*) _tmp11_, TRUE);
#line 234 "../src/contacts-contact-sheet.vala"
				_tmp13_ = _tmp12_;
#line 234 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (_tmp13_);
#line 233 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (url);
#line 1446 "contacts-contact-sheet.c"
			}
#line 233 "../src/contacts-contact-sheet.vala"
			_g_object_unref0 (_url_it);
#line 1450 "contacts-contact-sheet.c"
		}
	}
#line 230 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (url_details);
#line 1455 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_nickname (ContactsContactSheet* self,
                                     FolksPersona* persona)
{
	FolksNameDetails* name_details = NULL;
	FolksNameDetails* _tmp0_;
	gboolean _tmp1_ = FALSE;
	FolksNameDetails* _tmp2_;
#line 238 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 238 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 239 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_NAME_DETAILS) ? ((FolksNameDetails*) persona) : NULL);
#line 239 "../src/contacts-contact-sheet.vala"
	name_details = _tmp0_;
#line 240 "../src/contacts-contact-sheet.vala"
	_tmp2_ = name_details;
#line 240 "../src/contacts-contact-sheet.vala"
	if (_tmp2_ != NULL) {
#line 1478 "contacts-contact-sheet.c"
		FolksNameDetails* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
#line 240 "../src/contacts-contact-sheet.vala"
		_tmp3_ = name_details;
#line 240 "../src/contacts-contact-sheet.vala"
		_tmp4_ = folks_name_details_get_nickname (_tmp3_);
#line 240 "../src/contacts-contact-sheet.vala"
		_tmp5_ = _tmp4_;
#line 240 "../src/contacts-contact-sheet.vala"
		_tmp1_ = contacts_is_set (_tmp5_);
#line 1490 "contacts-contact-sheet.c"
	} else {
#line 240 "../src/contacts-contact-sheet.vala"
		_tmp1_ = FALSE;
#line 1494 "contacts-contact-sheet.c"
	}
#line 240 "../src/contacts-contact-sheet.vala"
	if (_tmp1_) {
#line 1498 "contacts-contact-sheet.c"
		FolksNameDetails* _tmp6_;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
#line 241 "../src/contacts-contact-sheet.vala"
		_tmp6_ = name_details;
#line 241 "../src/contacts-contact-sheet.vala"
		_tmp7_ = folks_name_details_get_nickname (_tmp6_);
#line 241 "../src/contacts-contact-sheet.vala"
		_tmp8_ = _tmp7_;
#line 241 "../src/contacts-contact-sheet.vala"
		contacts_contact_sheet_add_row_with_label (self, _ ("Nickname"), _tmp8_);
#line 1510 "contacts-contact-sheet.c"
	}
#line 238 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (name_details);
#line 1514 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_birthday (ContactsContactSheet* self,
                                     FolksPersona* persona)
{
	FolksBirthdayDetails* birthday_details = NULL;
	FolksBirthdayDetails* _tmp0_;
	gboolean _tmp1_ = FALSE;
	FolksBirthdayDetails* _tmp2_;
#line 244 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 244 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 245 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_BIRTHDAY_DETAILS) ? ((FolksBirthdayDetails*) persona) : NULL);
#line 245 "../src/contacts-contact-sheet.vala"
	birthday_details = _tmp0_;
#line 246 "../src/contacts-contact-sheet.vala"
	_tmp2_ = birthday_details;
#line 246 "../src/contacts-contact-sheet.vala"
	if (_tmp2_ != NULL) {
#line 1537 "contacts-contact-sheet.c"
		FolksBirthdayDetails* _tmp3_;
		GDateTime* _tmp4_;
		GDateTime* _tmp5_;
#line 246 "../src/contacts-contact-sheet.vala"
		_tmp3_ = birthday_details;
#line 246 "../src/contacts-contact-sheet.vala"
		_tmp4_ = folks_birthday_details_get_birthday (_tmp3_);
#line 246 "../src/contacts-contact-sheet.vala"
		_tmp5_ = _tmp4_;
#line 246 "../src/contacts-contact-sheet.vala"
		_tmp1_ = _tmp5_ != NULL;
#line 1549 "contacts-contact-sheet.c"
	} else {
#line 246 "../src/contacts-contact-sheet.vala"
		_tmp1_ = FALSE;
#line 1553 "contacts-contact-sheet.c"
	}
#line 246 "../src/contacts-contact-sheet.vala"
	if (_tmp1_) {
#line 1557 "contacts-contact-sheet.c"
		FolksBirthdayDetails* _tmp6_;
		GDateTime* _tmp7_;
		GDateTime* _tmp8_;
		GDateTime* _tmp9_;
		GDateTime* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp6_ = birthday_details;
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp7_ = folks_birthday_details_get_birthday (_tmp6_);
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp8_ = _tmp7_;
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp9_ = g_date_time_to_local (_tmp8_);
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp10_ = _tmp9_;
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp11_ = g_date_time_format (_tmp10_, "%x");
#line 247 "../src/contacts-contact-sheet.vala"
		_tmp12_ = _tmp11_;
#line 247 "../src/contacts-contact-sheet.vala"
		contacts_contact_sheet_add_row_with_label (self, _ ("Birthday"), _tmp12_);
#line 247 "../src/contacts-contact-sheet.vala"
		_g_free0 (_tmp12_);
#line 247 "../src/contacts-contact-sheet.vala"
		_g_date_time_unref0 (_tmp10_);
#line 1585 "contacts-contact-sheet.c"
	}
#line 244 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (birthday_details);
#line 1589 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_add_notes (ContactsContactSheet* self,
                                  FolksPersona* persona)
{
	FolksNoteDetails* note_details = NULL;
	FolksNoteDetails* _tmp0_;
	FolksNoteDetails* _tmp1_;
#line 250 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 250 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 251 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_NOTE_DETAILS) ? ((FolksNoteDetails*) persona) : NULL);
#line 251 "../src/contacts-contact-sheet.vala"
	note_details = _tmp0_;
#line 252 "../src/contacts-contact-sheet.vala"
	_tmp1_ = note_details;
#line 252 "../src/contacts-contact-sheet.vala"
	if (_tmp1_ != NULL) {
#line 1611 "contacts-contact-sheet.c"
		{
			GeeIterator* _note_it = NULL;
			FolksNoteDetails* _tmp2_;
			GeeSet* _tmp3_;
			GeeSet* _tmp4_;
			GeeIterator* _tmp5_;
#line 253 "../src/contacts-contact-sheet.vala"
			_tmp2_ = note_details;
#line 253 "../src/contacts-contact-sheet.vala"
			_tmp3_ = folks_note_details_get_notes (_tmp2_);
#line 253 "../src/contacts-contact-sheet.vala"
			_tmp4_ = _tmp3_;
#line 253 "../src/contacts-contact-sheet.vala"
			_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 253 "../src/contacts-contact-sheet.vala"
			_note_it = _tmp5_;
#line 253 "../src/contacts-contact-sheet.vala"
			while (TRUE) {
#line 1630 "contacts-contact-sheet.c"
				GeeIterator* _tmp6_;
				FolksNoteFieldDetails* note = NULL;
				GeeIterator* _tmp7_;
				gpointer _tmp8_;
				FolksNoteFieldDetails* _tmp9_;
				gconstpointer _tmp10_;
				const gchar* _tmp11_;
#line 253 "../src/contacts-contact-sheet.vala"
				_tmp6_ = _note_it;
#line 253 "../src/contacts-contact-sheet.vala"
				if (!gee_iterator_next (_tmp6_)) {
#line 253 "../src/contacts-contact-sheet.vala"
					break;
#line 1644 "contacts-contact-sheet.c"
				}
#line 253 "../src/contacts-contact-sheet.vala"
				_tmp7_ = _note_it;
#line 253 "../src/contacts-contact-sheet.vala"
				_tmp8_ = gee_iterator_get (_tmp7_);
#line 253 "../src/contacts-contact-sheet.vala"
				note = (FolksNoteFieldDetails*) _tmp8_;
#line 254 "../src/contacts-contact-sheet.vala"
				_tmp9_ = note;
#line 254 "../src/contacts-contact-sheet.vala"
				_tmp10_ = folks_abstract_field_details_get_value ((FolksAbstractFieldDetails*) _tmp9_);
#line 254 "../src/contacts-contact-sheet.vala"
				_tmp11_ = _tmp10_;
#line 254 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_row_with_label (self, _ ("Note"), (const gchar*) _tmp11_);
#line 253 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (note);
#line 1662 "contacts-contact-sheet.c"
			}
#line 253 "../src/contacts-contact-sheet.vala"
			_g_object_unref0 (_note_it);
#line 1666 "contacts-contact-sheet.c"
		}
	}
#line 250 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (note_details);
#line 1671 "contacts-contact-sheet.c"
}

static gchar*
_vala_g_strjoinv (const gchar* separator,
                  gchar** str_array,
                  gint str_array_length1)
{
	gboolean _tmp0_ = FALSE;
	gchar* result = NULL;
#line 1200 "glib-2.0.vapi"
	if (separator == NULL) {
#line 1201 "glib-2.0.vapi"
		separator = "";
#line 1685 "contacts-contact-sheet.c"
	}
#line 1203 "glib-2.0.vapi"
	if (str_array != NULL) {
#line 1689 "contacts-contact-sheet.c"
		gboolean _tmp1_ = FALSE;
#line 1203 "glib-2.0.vapi"
		if (str_array_length1 > 0) {
#line 1203 "glib-2.0.vapi"
			_tmp1_ = TRUE;
#line 1695 "contacts-contact-sheet.c"
		} else {
			gboolean _tmp2_ = FALSE;
#line 1203 "glib-2.0.vapi"
			if (str_array_length1 == -1) {
#line 1700 "contacts-contact-sheet.c"
				const gchar* _tmp3_;
#line 1203 "glib-2.0.vapi"
				_tmp3_ = str_array[0];
#line 1203 "glib-2.0.vapi"
				_tmp2_ = _tmp3_ != NULL;
#line 1706 "contacts-contact-sheet.c"
			} else {
#line 1203 "glib-2.0.vapi"
				_tmp2_ = FALSE;
#line 1710 "contacts-contact-sheet.c"
			}
#line 1203 "glib-2.0.vapi"
			_tmp1_ = _tmp2_;
#line 1714 "contacts-contact-sheet.c"
		}
#line 1203 "glib-2.0.vapi"
		_tmp0_ = _tmp1_;
#line 1718 "contacts-contact-sheet.c"
	} else {
#line 1203 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 1722 "contacts-contact-sheet.c"
	}
#line 1203 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1726 "contacts-contact-sheet.c"
		gint i = 0;
		gsize len = 0UL;
		gint _tmp16_;
		gint _tmp17_;
		const gchar* res = NULL;
		void* _tmp18_;
		void* ptr = NULL;
		const gchar* _tmp19_;
		const gchar* _tmp20_;
		void* _tmp21_;
		const gchar* _tmp31_;
#line 1205 "glib-2.0.vapi"
		len = (gsize) 1;
#line 1740 "contacts-contact-sheet.c"
		{
			gboolean _tmp4_ = FALSE;
#line 1206 "glib-2.0.vapi"
			i = 0;
#line 1206 "glib-2.0.vapi"
			_tmp4_ = TRUE;
#line 1206 "glib-2.0.vapi"
			while (TRUE) {
#line 1749 "contacts-contact-sheet.c"
				gboolean _tmp6_ = FALSE;
				gboolean _tmp7_ = FALSE;
				gint _tmp10_ = 0;
				const gchar* _tmp11_;
#line 1206 "glib-2.0.vapi"
				if (!_tmp4_) {
#line 1756 "contacts-contact-sheet.c"
					gint _tmp5_;
#line 1206 "glib-2.0.vapi"
					_tmp5_ = i;
#line 1206 "glib-2.0.vapi"
					i = _tmp5_ + 1;
#line 1762 "contacts-contact-sheet.c"
				}
#line 1206 "glib-2.0.vapi"
				_tmp4_ = FALSE;
#line 1206 "glib-2.0.vapi"
				if (str_array_length1 != -1) {
#line 1206 "glib-2.0.vapi"
					_tmp7_ = i < str_array_length1;
#line 1770 "contacts-contact-sheet.c"
				} else {
#line 1206 "glib-2.0.vapi"
					_tmp7_ = FALSE;
#line 1774 "contacts-contact-sheet.c"
				}
#line 1206 "glib-2.0.vapi"
				if (_tmp7_) {
#line 1206 "glib-2.0.vapi"
					_tmp6_ = TRUE;
#line 1780 "contacts-contact-sheet.c"
				} else {
					gboolean _tmp8_ = FALSE;
#line 1206 "glib-2.0.vapi"
					if (str_array_length1 == -1) {
#line 1785 "contacts-contact-sheet.c"
						const gchar* _tmp9_;
#line 1206 "glib-2.0.vapi"
						_tmp9_ = str_array[i];
#line 1206 "glib-2.0.vapi"
						_tmp8_ = _tmp9_ != NULL;
#line 1791 "contacts-contact-sheet.c"
					} else {
#line 1206 "glib-2.0.vapi"
						_tmp8_ = FALSE;
#line 1795 "contacts-contact-sheet.c"
					}
#line 1206 "glib-2.0.vapi"
					_tmp6_ = _tmp8_;
#line 1799 "contacts-contact-sheet.c"
				}
#line 1206 "glib-2.0.vapi"
				if (!_tmp6_) {
#line 1206 "glib-2.0.vapi"
					break;
#line 1805 "contacts-contact-sheet.c"
				}
#line 1207 "glib-2.0.vapi"
				_tmp11_ = str_array[i];
#line 1207 "glib-2.0.vapi"
				if (_tmp11_ != NULL) {
#line 1811 "contacts-contact-sheet.c"
					const gchar* _tmp12_;
					gint _tmp13_;
					gint _tmp14_;
#line 1207 "glib-2.0.vapi"
					_tmp12_ = str_array[i];
#line 1207 "glib-2.0.vapi"
					_tmp13_ = strlen ((const gchar*) _tmp12_);
#line 1207 "glib-2.0.vapi"
					_tmp14_ = _tmp13_;
#line 1207 "glib-2.0.vapi"
					_tmp10_ = _tmp14_;
#line 1823 "contacts-contact-sheet.c"
				} else {
#line 1207 "glib-2.0.vapi"
					_tmp10_ = 0;
#line 1827 "contacts-contact-sheet.c"
				}
#line 1207 "glib-2.0.vapi"
				len += (gsize) _tmp10_;
#line 1831 "contacts-contact-sheet.c"
			}
		}
#line 1209 "glib-2.0.vapi"
		if (i == 0) {
#line 1836 "contacts-contact-sheet.c"
			gchar* _tmp15_;
#line 1210 "glib-2.0.vapi"
			_tmp15_ = g_strdup ("");
#line 1210 "glib-2.0.vapi"
			result = _tmp15_;
#line 1210 "glib-2.0.vapi"
			return result;
#line 1844 "contacts-contact-sheet.c"
		}
#line 1212 "glib-2.0.vapi"
		str_array_length1 = i;
#line 1213 "glib-2.0.vapi"
		_tmp16_ = strlen ((const gchar*) separator);
#line 1213 "glib-2.0.vapi"
		_tmp17_ = _tmp16_;
#line 1213 "glib-2.0.vapi"
		len += (gsize) (_tmp17_ * (i - 1));
#line 1215 "glib-2.0.vapi"
		_tmp18_ = g_malloc (len);
#line 1215 "glib-2.0.vapi"
		res = _tmp18_;
#line 1216 "glib-2.0.vapi"
		_tmp19_ = res;
#line 1216 "glib-2.0.vapi"
		_tmp20_ = str_array[0];
#line 1216 "glib-2.0.vapi"
		_tmp21_ = g_stpcpy ((void*) _tmp19_, (const gchar*) _tmp20_);
#line 1216 "glib-2.0.vapi"
		ptr = _tmp21_;
#line 1866 "contacts-contact-sheet.c"
		{
			gboolean _tmp22_ = FALSE;
#line 1217 "glib-2.0.vapi"
			i = 1;
#line 1217 "glib-2.0.vapi"
			_tmp22_ = TRUE;
#line 1217 "glib-2.0.vapi"
			while (TRUE) {
#line 1875 "contacts-contact-sheet.c"
				void* _tmp24_;
				void* _tmp25_;
				const gchar* _tmp26_ = NULL;
				const gchar* _tmp27_;
				void* _tmp29_;
				void* _tmp30_;
#line 1217 "glib-2.0.vapi"
				if (!_tmp22_) {
#line 1884 "contacts-contact-sheet.c"
					gint _tmp23_;
#line 1217 "glib-2.0.vapi"
					_tmp23_ = i;
#line 1217 "glib-2.0.vapi"
					i = _tmp23_ + 1;
#line 1890 "contacts-contact-sheet.c"
				}
#line 1217 "glib-2.0.vapi"
				_tmp22_ = FALSE;
#line 1217 "glib-2.0.vapi"
				if (!(i < str_array_length1)) {
#line 1217 "glib-2.0.vapi"
					break;
#line 1898 "contacts-contact-sheet.c"
				}
#line 1218 "glib-2.0.vapi"
				_tmp24_ = ptr;
#line 1218 "glib-2.0.vapi"
				_tmp25_ = g_stpcpy (_tmp24_, (const gchar*) separator);
#line 1218 "glib-2.0.vapi"
				ptr = _tmp25_;
#line 1219 "glib-2.0.vapi"
				_tmp27_ = str_array[i];
#line 1219 "glib-2.0.vapi"
				if (_tmp27_ != NULL) {
#line 1910 "contacts-contact-sheet.c"
					const gchar* _tmp28_;
#line 1219 "glib-2.0.vapi"
					_tmp28_ = str_array[i];
#line 1219 "glib-2.0.vapi"
					_tmp26_ = (const gchar*) _tmp28_;
#line 1916 "contacts-contact-sheet.c"
				} else {
#line 1219 "glib-2.0.vapi"
					_tmp26_ = "";
#line 1920 "contacts-contact-sheet.c"
				}
#line 1219 "glib-2.0.vapi"
				_tmp29_ = ptr;
#line 1219 "glib-2.0.vapi"
				_tmp30_ = g_stpcpy (_tmp29_, _tmp26_);
#line 1219 "glib-2.0.vapi"
				ptr = _tmp30_;
#line 1928 "contacts-contact-sheet.c"
			}
		}
#line 1222 "glib-2.0.vapi"
		_tmp31_ = res;
#line 1222 "glib-2.0.vapi"
		res = NULL;
#line 1222 "glib-2.0.vapi"
		result = (gchar*) _tmp31_;
#line 1222 "glib-2.0.vapi"
		return result;
#line 1939 "contacts-contact-sheet.c"
	} else {
		gchar* _tmp32_;
#line 1224 "glib-2.0.vapi"
		_tmp32_ = g_strdup ("");
#line 1224 "glib-2.0.vapi"
		result = _tmp32_;
#line 1224 "glib-2.0.vapi"
		return result;
#line 1948 "contacts-contact-sheet.c"
	}
}

static void
contacts_contact_sheet_add_postal_addresses (ContactsContactSheet* self,
                                             FolksPersona* persona)
{
	FolksPostalAddressDetails* addr_details = NULL;
	FolksPostalAddressDetails* _tmp0_;
	FolksPostalAddressDetails* _tmp1_;
#line 258 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (self != NULL);
#line 258 "../src/contacts-contact-sheet.vala"
	g_return_if_fail (persona != NULL);
#line 259 "../src/contacts-contact-sheet.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (persona, FOLKS_TYPE_POSTAL_ADDRESS_DETAILS) ? ((FolksPostalAddressDetails*) persona) : NULL);
#line 259 "../src/contacts-contact-sheet.vala"
	addr_details = _tmp0_;
#line 260 "../src/contacts-contact-sheet.vala"
	_tmp1_ = addr_details;
#line 260 "../src/contacts-contact-sheet.vala"
	if (_tmp1_ != NULL) {
#line 1971 "contacts-contact-sheet.c"
		{
			GeeIterator* _addr_it = NULL;
			FolksPostalAddressDetails* _tmp2_;
			GeeSet* _tmp3_;
			GeeSet* _tmp4_;
			GeeIterator* _tmp5_;
#line 261 "../src/contacts-contact-sheet.vala"
			_tmp2_ = addr_details;
#line 261 "../src/contacts-contact-sheet.vala"
			_tmp3_ = folks_postal_address_details_get_postal_addresses (_tmp2_);
#line 261 "../src/contacts-contact-sheet.vala"
			_tmp4_ = _tmp3_;
#line 261 "../src/contacts-contact-sheet.vala"
			_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 261 "../src/contacts-contact-sheet.vala"
			_addr_it = _tmp5_;
#line 261 "../src/contacts-contact-sheet.vala"
			while (TRUE) {
#line 1990 "contacts-contact-sheet.c"
				GeeIterator* _tmp6_;
				FolksPostalAddressFieldDetails* addr = NULL;
				GeeIterator* _tmp7_;
				gpointer _tmp8_;
				gchar* all_strs = NULL;
				FolksPostalAddressFieldDetails* _tmp9_;
				gconstpointer _tmp10_;
				FolksPostalAddress* _tmp11_;
				gint _tmp12_ = 0;
				gchar** _tmp13_;
				gchar** _tmp14_;
				gint _tmp14__length1;
				gchar* _tmp15_;
				gchar* _tmp16_;
				ContactsTypeSet* _tmp17_;
				ContactsTypeSet* _tmp18_;
				FolksPostalAddressFieldDetails* _tmp19_;
				gchar* _tmp20_;
				gchar* _tmp21_;
				const gchar* _tmp22_;
#line 261 "../src/contacts-contact-sheet.vala"
				_tmp6_ = _addr_it;
#line 261 "../src/contacts-contact-sheet.vala"
				if (!gee_iterator_next (_tmp6_)) {
#line 261 "../src/contacts-contact-sheet.vala"
					break;
#line 2017 "contacts-contact-sheet.c"
				}
#line 261 "../src/contacts-contact-sheet.vala"
				_tmp7_ = _addr_it;
#line 261 "../src/contacts-contact-sheet.vala"
				_tmp8_ = gee_iterator_get (_tmp7_);
#line 261 "../src/contacts-contact-sheet.vala"
				addr = (FolksPostalAddressFieldDetails*) _tmp8_;
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp9_ = addr;
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp10_ = folks_abstract_field_details_get_value ((FolksAbstractFieldDetails*) _tmp9_);
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp11_ = _tmp10_;
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp13_ = contacts_utils_format_address ((FolksPostalAddress*) _tmp11_, &_tmp12_);
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp14_ = _tmp13_;
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp14__length1 = _tmp12_;
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp15_ = _vala_g_strjoinv ("\n", _tmp14_, (gint) _tmp12_);
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp16_ = _tmp15_;
#line 262 "../src/contacts-contact-sheet.vala"
				_tmp14_ = (_vala_array_free (_tmp14_, _tmp14__length1, (GDestroyNotify) g_free), NULL);
#line 262 "../src/contacts-contact-sheet.vala"
				all_strs = _tmp16_;
#line 263 "../src/contacts-contact-sheet.vala"
				_tmp17_ = contacts_typeset_get_general ();
#line 263 "../src/contacts-contact-sheet.vala"
				_tmp18_ = _tmp17_;
#line 263 "../src/contacts-contact-sheet.vala"
				_tmp19_ = addr;
#line 263 "../src/contacts-contact-sheet.vala"
				_tmp20_ = contacts_typeset_format_type (_tmp18_, (FolksAbstractFieldDetails*) _tmp19_);
#line 263 "../src/contacts-contact-sheet.vala"
				_tmp21_ = _tmp20_;
#line 263 "../src/contacts-contact-sheet.vala"
				_tmp22_ = all_strs;
#line 263 "../src/contacts-contact-sheet.vala"
				contacts_contact_sheet_add_row_with_label (self, _tmp21_, _tmp22_);
#line 263 "../src/contacts-contact-sheet.vala"
				_g_free0 (_tmp21_);
#line 261 "../src/contacts-contact-sheet.vala"
				_g_free0 (all_strs);
#line 261 "../src/contacts-contact-sheet.vala"
				_g_object_unref0 (addr);
#line 2065 "contacts-contact-sheet.c"
			}
#line 261 "../src/contacts-contact-sheet.vala"
			_g_object_unref0 (_addr_it);
#line 2069 "contacts-contact-sheet.c"
		}
	}
#line 258 "../src/contacts-contact-sheet.vala"
	_g_object_unref0 (addr_details);
#line 2074 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_class_init (ContactsContactSheetClass * klass,
                                   gpointer klass_data)
{
#line 27 "../src/contacts-contact-sheet.vala"
	contacts_contact_sheet_parent_class = g_type_class_peek_parent (klass);
#line 2083 "contacts-contact-sheet.c"
}

static void
contacts_contact_sheet_instance_init (ContactsContactSheet * self,
                                      gpointer klass)
{
}

/**
 * The contact sheet displays the actual information of a contact.
 *
 * (Note: to edit a contact, use the {@link ContactEditor} instead.
 */
static GType
contacts_contact_sheet_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsContactSheetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_contact_sheet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsContactSheet), 0, (GInstanceInitFunc) contacts_contact_sheet_instance_init, NULL };
	GType contacts_contact_sheet_type_id;
	contacts_contact_sheet_type_id = g_type_register_static (CONTACTS_TYPE_CONTACT_FORM, "ContactsContactSheet", &g_define_type_info, 0);
	return contacts_contact_sheet_type_id;
}

GType
contacts_contact_sheet_get_type (void)
{
	static volatile gsize contacts_contact_sheet_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_contact_sheet_type_id__volatile)) {
		GType contacts_contact_sheet_type_id;
		contacts_contact_sheet_type_id = contacts_contact_sheet_get_type_once ();
		g_once_init_leave (&contacts_contact_sheet_type_id__volatile, contacts_contact_sheet_type_id);
	}
	return contacts_contact_sheet_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

