/* contacts-contact-list.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-contact-list.vala, do not modify */

/*
 * Copyright (C) 2011 Alexander Larsson <alexl@redhat.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <folks/folks.h>
#include "contacts.h"
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <glib/gi18n-lib.h>
#include <pango/pango.h>
#include <math.h>
#include <float.h>

#define CONTACTS_TYPE_CONTACT_LIST (contacts_contact_list_get_type ())
#define CONTACTS_CONTACT_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_CONTACT_LIST, ContactsContactList))
#define CONTACTS_CONTACT_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_CONTACT_LIST, ContactsContactListClass))
#define CONTACTS_IS_CONTACT_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_CONTACT_LIST))
#define CONTACTS_IS_CONTACT_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_CONTACT_LIST))
#define CONTACTS_CONTACT_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_CONTACT_LIST, ContactsContactListClass))

typedef struct _ContactsContactList ContactsContactList;
typedef struct _ContactsContactListClass ContactsContactListClass;
typedef struct _ContactsContactListPrivate ContactsContactListPrivate;
typedef enum  {
	CONTACTS_UI_STATE_NORMAL,
	CONTACTS_UI_STATE_SHOWING,
	CONTACTS_UI_STATE_SELECTING,
	CONTACTS_UI_STATE_UPDATING,
	CONTACTS_UI_STATE_CREATING
} ContactsUiState;

#define CONTACTS_TYPE_UI_STATE (contacts_ui_state_get_type ())
enum  {
	CONTACTS_CONTACT_LIST_0_PROPERTY,
	CONTACTS_CONTACT_LIST_STATE_PROPERTY,
	CONTACTS_CONTACT_LIST_NUM_PROPERTIES
};
static GParamSpec* contacts_contact_list_properties[CONTACTS_CONTACT_LIST_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CONTACTS_TYPE_SETTINGS (contacts_settings_get_type ())
#define CONTACTS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_SETTINGS, ContactsSettings))
#define CONTACTS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_SETTINGS, ContactsSettingsClass))
#define CONTACTS_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_SETTINGS))
#define CONTACTS_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_SETTINGS))
#define CONTACTS_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_SETTINGS, ContactsSettingsClass))

typedef struct _ContactsSettings ContactsSettings;
typedef struct _ContactsSettingsClass ContactsSettingsClass;
typedef struct _Block15Data Block15Data;

#define CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW (contacts_contact_list_contact_data_row_get_type ())
#define CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow))
#define CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRowClass))
#define CONTACTS_CONTACT_LIST_IS_CONTACT_DATA_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW))
#define CONTACTS_CONTACT_LIST_IS_CONTACT_DATA_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW))
#define CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRowClass))

typedef struct _ContactsContactListContactDataRow ContactsContactListContactDataRow;
typedef struct _ContactsContactListContactDataRowClass ContactsContactListContactDataRowClass;
typedef struct _ContactsContactListContactDataRowPrivate ContactsContactListContactDataRowPrivate;
#define _pango_attr_list_unref0(var) ((var == NULL) ? NULL : (var = (pango_attr_list_unref (var), NULL)))
typedef struct _Block16Data Block16Data;

#define CONTACTS_TYPE_AVATAR (contacts_avatar_get_type ())
#define CONTACTS_AVATAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_AVATAR, ContactsAvatar))
#define CONTACTS_AVATAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_AVATAR, ContactsAvatarClass))
#define CONTACTS_IS_AVATAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_AVATAR))
#define CONTACTS_IS_AVATAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_AVATAR))
#define CONTACTS_AVATAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_AVATAR, ContactsAvatarClass))

typedef struct _ContactsAvatar ContactsAvatar;
typedef struct _ContactsAvatarClass ContactsAvatarClass;
enum  {
	CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_0_PROPERTY,
	CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_NUM_PROPERTIES
};
static GParamSpec* contacts_contact_list_contact_data_row_properties[CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_NUM_PROPERTIES];
enum  {
	CONTACTS_CONTACT_LIST_SELECTION_CHANGED_SIGNAL,
	CONTACTS_CONTACT_LIST_CONTACTS_MARKED_SIGNAL,
	CONTACTS_CONTACT_LIST_NUM_SIGNALS
};
static guint contacts_contact_list_signals[CONTACTS_CONTACT_LIST_NUM_SIGNALS] = {0};

struct _ContactsContactList {
	GtkListBox parent_instance;
	ContactsContactListPrivate * priv;
};

struct _ContactsContactListClass {
	GtkListBoxClass parent_class;
};

struct _ContactsContactListPrivate {
	gint nr_contacts_marked;
	FolksQuery* filter_query;
	ContactsStore* store;
	gboolean sort_on_surname;
	ContactsUiState _state;
};

struct _Block15Data {
	int _ref_count_;
	ContactsContactList* self;
	ContactsSettings* settings;
};

struct _ContactsContactListContactDataRow {
	GtkListBoxRow parent_instance;
	ContactsContactListContactDataRowPrivate * priv;
	FolksIndividual* individual;
	GtkCheckButton* selector_button;
};

struct _ContactsContactListContactDataRowClass {
	GtkListBoxRowClass parent_class;
};

struct _Block16Data {
	int _ref_count_;
	ContactsContactList* self;
	ContactsContactListContactDataRow* row;
};

struct _ContactsContactListContactDataRowPrivate {
	GtkLabel* label;
	ContactsAvatar* avatar;
	gboolean checkbox_exposed;
};

static gint ContactsContactList_private_offset;
static gpointer contacts_contact_list_parent_class = NULL;
static gint ContactsContactListContactDataRow_private_offset;
static gpointer contacts_contact_list_contact_data_row_parent_class = NULL;

GType contacts_contact_list_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsContactList, g_object_unref)
GType contacts_ui_state_get_type (void) G_GNUC_CONST;
GType contacts_settings_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsSettings, g_object_unref)
ContactsContactList* contacts_contact_list_new (ContactsSettings* settings,
                                                ContactsStore* store,
                                                FolksQuery* query);
ContactsContactList* contacts_contact_list_construct (GType object_type,
                                                      ContactsSettings* settings,
                                                      ContactsStore* store,
                                                      FolksQuery* query);
static Block15Data* block15_data_ref (Block15Data* _data15_);
static void block15_data_unref (void * _userdata_);
static void __lambda4_ (ContactsContactList* self);
static void ___lambda4__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void contacts_contact_list_on_ui_state_changed (ContactsContactList* self,
                                                GObject* obj,
                                                GParamSpec* pspec);
static void _contacts_contact_list_on_ui_state_changed_g_object_notify (GObject* _sender,
                                                                 GParamSpec* pspec,
                                                                 gpointer self);
gboolean contacts_settings_get_sort_on_surname (ContactsSettings* self);
static void __lambda6_ (Block15Data* _data15_);
static void ___lambda6__g_settings_changed (GSettings* _sender,
                                     const gchar* key,
                                     gpointer self);
static void contacts_contact_list_contact_added_cb (ContactsContactList* self,
                                             ContactsStore* store,
                                             FolksIndividual* i);
static void _contacts_contact_list_contact_added_cb_contacts_store_added (ContactsStore* _sender,
                                                                   FolksIndividual* c,
                                                                   gpointer self);
static void contacts_contact_list_contact_removed_cb (ContactsContactList* self,
                                               ContactsStore* store,
                                               FolksIndividual* i);
static void _contacts_contact_list_contact_removed_cb_contacts_store_removed (ContactsStore* _sender,
                                                                       FolksIndividual* c,
                                                                       gpointer self);
static gint contacts_contact_list_compare_rows (ContactsContactList* self,
                                         GtkListBoxRow* row_a,
                                         GtkListBoxRow* row_b);
static gint _contacts_contact_list_compare_rows_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                                 GtkListBoxRow* row2,
                                                                 gpointer self);
static gboolean contacts_contact_list_filter_row (ContactsContactList* self,
                                           GtkListBoxRow* row);
static gboolean _contacts_contact_list_filter_row_gtk_list_box_filter_func (GtkListBoxRow* row,
                                                                     gpointer self);
static void contacts_contact_list_update_header (ContactsContactList* self,
                                          GtkListBoxRow* row,
                                          GtkListBoxRow* before);
static void _contacts_contact_list_update_header_gtk_list_box_update_header_func (GtkListBoxRow* row,
                                                                           GtkListBoxRow* before,
                                                                           gpointer self);
static GType contacts_contact_list_contact_data_row_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsContactListContactDataRow, g_object_unref)
static void contacts_contact_list_contact_data_row_expose_checkbox (ContactsContactListContactDataRow* self,
                                                             gboolean expose);
ContactsUiState contacts_contact_list_get_state (ContactsContactList* self);
static const gchar* contacts_contact_list_try_get_surname (ContactsContactList* self,
                                                    FolksIndividual* indiv);
static GtkLabel* contacts_contact_list_create_header_label (ContactsContactList* self,
                                                     const gchar* text);
static Block16Data* block16_data_ref (Block16Data* _data16_);
static void block16_data_unref (void * _userdata_);
static ContactsContactListContactDataRow* contacts_contact_list_contact_data_row_new (FolksIndividual* i);
static ContactsContactListContactDataRow* contacts_contact_list_contact_data_row_construct (GType object_type,
                                                                                     FolksIndividual* i);
static void ___lambda7_ (Block16Data* _data16_);
static void contacts_contact_list_on_row_checkbox_toggled (ContactsContactList* self,
                                                    ContactsContactListContactDataRow* row);
static void ____lambda7__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self);
void contacts_contact_list_set_state (ContactsContactList* self,
                                      ContactsUiState value);
static ContactsContactListContactDataRow* contacts_contact_list_find_row_for_contact (ContactsContactList* self,
                                                                               FolksIndividual* individual);
static void contacts_contact_list_real_row_selected (GtkListBox* base,
                                              GtkListBoxRow* row);
void contacts_contact_list_select_contact (ContactsContactList* self,
                                           FolksIndividual* individual);
void contacts_contact_list_hide_contact (ContactsContactList* self,
                                         FolksIndividual* individual);
GeeLinkedList* contacts_contact_list_get_marked_contacts (ContactsContactList* self);
GeeLinkedList* contacts_contact_list_get_marked_contacts_and_hide (ContactsContactList* self);
static gboolean contacts_contact_list_real_button_press_event (GtkWidget* base,
                                                        GdkEventButton* event);
GType contacts_avatar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsAvatar, g_object_unref)
#define CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_LIST_AVATAR_SIZE 48
static void contacts_contact_list_contact_data_row_on_contact_changed (ContactsContactListContactDataRow* self,
                                                                GObject* obj,
                                                                GParamSpec* pspec);
static void _contacts_contact_list_contact_data_row_on_contact_changed_g_object_notify (GObject* _sender,
                                                                                 GParamSpec* pspec,
                                                                                 gpointer self);
ContactsAvatar* contacts_avatar_new (gint size,
                                     FolksIndividual* individual);
ContactsAvatar* contacts_avatar_construct (GType object_type,
                                           gint size,
                                           FolksIndividual* individual);
static void contacts_contact_list_contact_data_row_real_state_flags_changed (GtkWidget* base,
                                                                      GtkStateFlags previous_state);
static void contacts_contact_list_contact_data_row_finalize (GObject * obj);
static GType contacts_contact_list_contact_data_row_get_type_once (void);
static void contacts_contact_list_finalize (GObject * obj);
static GType contacts_contact_list_get_type_once (void);
static void _vala_contacts_contact_list_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec);
static void _vala_contacts_contact_list_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec);

static inline gpointer
contacts_contact_list_get_instance_private (ContactsContactList* self)
{
	return G_STRUCT_MEMBER_P (self, ContactsContactList_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 109 "../src/contacts-contact-list.vala"
	return self ? g_object_ref (self) : NULL;
#line 290 "contacts-contact-list.c"
}

static Block15Data*
block15_data_ref (Block15Data* _data15_)
{
#line 109 "../src/contacts-contact-list.vala"
	g_atomic_int_inc (&_data15_->_ref_count_);
#line 109 "../src/contacts-contact-list.vala"
	return _data15_;
#line 300 "contacts-contact-list.c"
}

static void
block15_data_unref (void * _userdata_)
{
	Block15Data* _data15_;
	_data15_ = (Block15Data*) _userdata_;
#line 109 "../src/contacts-contact-list.vala"
	if (g_atomic_int_dec_and_test (&_data15_->_ref_count_)) {
#line 310 "contacts-contact-list.c"
		ContactsContactList* self;
#line 109 "../src/contacts-contact-list.vala"
		self = _data15_->self;
#line 109 "../src/contacts-contact-list.vala"
		_g_object_unref0 (_data15_->settings);
#line 109 "../src/contacts-contact-list.vala"
		_g_object_unref0 (self);
#line 109 "../src/contacts-contact-list.vala"
		g_slice_free (Block15Data, _data15_);
#line 320 "contacts-contact-list.c"
	}
}

static void
__lambda4_ (ContactsContactList* self)
{
#line 113 "../src/contacts-contact-list.vala"
	gtk_list_box_invalidate_filter ((GtkListBox*) self);
#line 329 "contacts-contact-list.c"
}

static void
___lambda4__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 113 "../src/contacts-contact-list.vala"
	__lambda4_ ((ContactsContactList*) self);
#line 339 "contacts-contact-list.c"
}

static void
_contacts_contact_list_on_ui_state_changed_g_object_notify (GObject* _sender,
                                                            GParamSpec* pspec,
                                                            gpointer self)
{
#line 116 "../src/contacts-contact-list.vala"
	contacts_contact_list_on_ui_state_changed ((ContactsContactList*) self, _sender, pspec);
#line 349 "contacts-contact-list.c"
}

static void
__lambda6_ (Block15Data* _data15_)
{
	ContactsContactList* self;
	gboolean _tmp0_;
	gboolean _tmp1_;
#line 119 "../src/contacts-contact-list.vala"
	self = _data15_->self;
#line 120 "../src/contacts-contact-list.vala"
	_tmp0_ = contacts_settings_get_sort_on_surname (_data15_->settings);
#line 120 "../src/contacts-contact-list.vala"
	_tmp1_ = _tmp0_;
#line 120 "../src/contacts-contact-list.vala"
	self->priv->sort_on_surname = _tmp1_;
#line 121 "../src/contacts-contact-list.vala"
	gtk_list_box_invalidate_sort ((GtkListBox*) self);
#line 368 "contacts-contact-list.c"
}

static void
___lambda6__g_settings_changed (GSettings* _sender,
                                const gchar* key,
                                gpointer self)
{
#line 119 "../src/contacts-contact-list.vala"
	__lambda6_ (self);
#line 378 "contacts-contact-list.c"
}

static void
_contacts_contact_list_contact_added_cb_contacts_store_added (ContactsStore* _sender,
                                                              FolksIndividual* c,
                                                              gpointer self)
{
#line 124 "../src/contacts-contact-list.vala"
	contacts_contact_list_contact_added_cb ((ContactsContactList*) self, _sender, c);
#line 388 "contacts-contact-list.c"
}

static void
_contacts_contact_list_contact_removed_cb_contacts_store_removed (ContactsStore* _sender,
                                                                  FolksIndividual* c,
                                                                  gpointer self)
{
#line 125 "../src/contacts-contact-list.vala"
	contacts_contact_list_contact_removed_cb ((ContactsContactList*) self, _sender, c);
#line 398 "contacts-contact-list.c"
}

static gint
_contacts_contact_list_compare_rows_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                            GtkListBoxRow* row2,
                                                            gpointer self)
{
	gint result;
	result = contacts_contact_list_compare_rows ((ContactsContactList*) self, row1, row2);
#line 131 "../src/contacts-contact-list.vala"
	return result;
#line 410 "contacts-contact-list.c"
}

static gboolean
_contacts_contact_list_filter_row_gtk_list_box_filter_func (GtkListBoxRow* row,
                                                            gpointer self)
{
	gboolean result;
	result = contacts_contact_list_filter_row ((ContactsContactList*) self, row);
#line 132 "../src/contacts-contact-list.vala"
	return result;
#line 421 "contacts-contact-list.c"
}

static void
_contacts_contact_list_update_header_gtk_list_box_update_header_func (GtkListBoxRow* row,
                                                                      GtkListBoxRow* before,
                                                                      gpointer self)
{
#line 133 "../src/contacts-contact-list.vala"
	contacts_contact_list_update_header ((ContactsContactList*) self, row, before);
#line 431 "contacts-contact-list.c"
}

ContactsContactList*
contacts_contact_list_construct (GType object_type,
                                 ContactsSettings* settings,
                                 ContactsStore* store,
                                 FolksQuery* query)
{
	ContactsContactList * self = NULL;
	Block15Data* _data15_;
	ContactsSettings* _tmp0_;
	ContactsStore* _tmp1_;
	FolksQuery* _tmp2_;
	FolksQuery* _tmp3_;
	gboolean _tmp4_;
	gboolean _tmp5_;
	ContactsStore* _tmp6_;
	ContactsStore* _tmp7_;
	GtkStyleContext* _tmp18_;
#line 109 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (settings != NULL, NULL);
#line 109 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (store != NULL, NULL);
#line 109 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (query != NULL, NULL);
#line 109 "../src/contacts-contact-list.vala"
	_data15_ = g_slice_new0 (Block15Data);
#line 109 "../src/contacts-contact-list.vala"
	_data15_->_ref_count_ = 1;
#line 109 "../src/contacts-contact-list.vala"
	_tmp0_ = _g_object_ref0 (settings);
#line 109 "../src/contacts-contact-list.vala"
	_g_object_unref0 (_data15_->settings);
#line 109 "../src/contacts-contact-list.vala"
	_data15_->settings = _tmp0_;
#line 109 "../src/contacts-contact-list.vala"
	self = (ContactsContactList*) g_object_new (object_type, NULL);
#line 109 "../src/contacts-contact-list.vala"
	_data15_->self = g_object_ref (self);
#line 110 "../src/contacts-contact-list.vala"
	gtk_list_box_set_selection_mode ((GtkListBox*) self, GTK_SELECTION_BROWSE);
#line 111 "../src/contacts-contact-list.vala"
	_tmp1_ = _g_object_ref0 (store);
#line 111 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->store);
#line 111 "../src/contacts-contact-list.vala"
	self->priv->store = _tmp1_;
#line 112 "../src/contacts-contact-list.vala"
	_tmp2_ = _g_object_ref0 (query);
#line 112 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->filter_query);
#line 112 "../src/contacts-contact-list.vala"
	self->priv->filter_query = _tmp2_;
#line 113 "../src/contacts-contact-list.vala"
	_tmp3_ = self->priv->filter_query;
#line 113 "../src/contacts-contact-list.vala"
	g_signal_connect_object ((GObject*) _tmp3_, "notify", (GCallback) ___lambda4__g_object_notify, self, 0);
#line 114 "../src/contacts-contact-list.vala"
	gtk_widget_set_visible ((GtkWidget*) self, TRUE);
#line 116 "../src/contacts-contact-list.vala"
	g_signal_connect_object ((GObject*) self, "notify::state", (GCallback) _contacts_contact_list_on_ui_state_changed_g_object_notify, self, 0);
#line 118 "../src/contacts-contact-list.vala"
	_tmp4_ = contacts_settings_get_sort_on_surname (_data15_->settings);
#line 118 "../src/contacts-contact-list.vala"
	_tmp5_ = _tmp4_;
#line 118 "../src/contacts-contact-list.vala"
	self->priv->sort_on_surname = _tmp5_;
#line 119 "../src/contacts-contact-list.vala"
	g_signal_connect_data ((GSettings*) _data15_->settings, "changed::sort-on-surname", (GCallback) ___lambda6__g_settings_changed, block15_data_ref (_data15_), (GClosureNotify) block15_data_unref, 0);
#line 124 "../src/contacts-contact-list.vala"
	_tmp6_ = self->priv->store;
#line 124 "../src/contacts-contact-list.vala"
	g_signal_connect_object (_tmp6_, "added", (GCallback) _contacts_contact_list_contact_added_cb_contacts_store_added, self, 0);
#line 125 "../src/contacts-contact-list.vala"
	_tmp7_ = self->priv->store;
#line 125 "../src/contacts-contact-list.vala"
	g_signal_connect_object (_tmp7_, "removed", (GCallback) _contacts_contact_list_contact_removed_cb_contacts_store_removed, self, 0);
#line 509 "contacts-contact-list.c"
	{
		GeeIterator* _i_it = NULL;
		ContactsStore* _tmp8_;
		GeeCollection* _tmp9_;
		GeeCollection* _tmp10_;
		GeeIterator* _tmp11_;
		GeeIterator* _tmp12_;
#line 126 "../src/contacts-contact-list.vala"
		_tmp8_ = self->priv->store;
#line 126 "../src/contacts-contact-list.vala"
		_tmp9_ = contacts_store_get_contacts (_tmp8_);
#line 126 "../src/contacts-contact-list.vala"
		_tmp10_ = _tmp9_;
#line 126 "../src/contacts-contact-list.vala"
		_tmp11_ = gee_iterable_iterator ((GeeIterable*) _tmp10_);
#line 126 "../src/contacts-contact-list.vala"
		_tmp12_ = _tmp11_;
#line 126 "../src/contacts-contact-list.vala"
		_g_object_unref0 (_tmp10_);
#line 126 "../src/contacts-contact-list.vala"
		_i_it = _tmp12_;
#line 126 "../src/contacts-contact-list.vala"
		while (TRUE) {
#line 533 "contacts-contact-list.c"
			GeeIterator* _tmp13_;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp14_;
			gpointer _tmp15_;
			ContactsStore* _tmp16_;
			FolksIndividual* _tmp17_;
#line 126 "../src/contacts-contact-list.vala"
			_tmp13_ = _i_it;
#line 126 "../src/contacts-contact-list.vala"
			if (!gee_iterator_next (_tmp13_)) {
#line 126 "../src/contacts-contact-list.vala"
				break;
#line 546 "contacts-contact-list.c"
			}
#line 126 "../src/contacts-contact-list.vala"
			_tmp14_ = _i_it;
#line 126 "../src/contacts-contact-list.vala"
			_tmp15_ = gee_iterator_get (_tmp14_);
#line 126 "../src/contacts-contact-list.vala"
			i = (FolksIndividual*) _tmp15_;
#line 127 "../src/contacts-contact-list.vala"
			_tmp16_ = self->priv->store;
#line 127 "../src/contacts-contact-list.vala"
			_tmp17_ = i;
#line 127 "../src/contacts-contact-list.vala"
			contacts_contact_list_contact_added_cb (self, _tmp16_, _tmp17_);
#line 126 "../src/contacts-contact-list.vala"
			_g_object_unref0 (i);
#line 562 "contacts-contact-list.c"
		}
#line 126 "../src/contacts-contact-list.vala"
		_g_object_unref0 (_i_it);
#line 566 "contacts-contact-list.c"
	}
#line 129 "../src/contacts-contact-list.vala"
	_tmp18_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 129 "../src/contacts-contact-list.vala"
	gtk_style_context_add_class (_tmp18_, "contacts-contact-list");
#line 131 "../src/contacts-contact-list.vala"
	gtk_list_box_set_sort_func ((GtkListBox*) self, _contacts_contact_list_compare_rows_gtk_list_box_sort_func, g_object_ref (self), g_object_unref);
#line 132 "../src/contacts-contact-list.vala"
	gtk_list_box_set_filter_func ((GtkListBox*) self, _contacts_contact_list_filter_row_gtk_list_box_filter_func, g_object_ref (self), g_object_unref);
#line 133 "../src/contacts-contact-list.vala"
	gtk_list_box_set_header_func ((GtkListBox*) self, _contacts_contact_list_update_header_gtk_list_box_update_header_func, g_object_ref (self), g_object_unref);
#line 109 "../src/contacts-contact-list.vala"
	block15_data_unref (_data15_);
#line 109 "../src/contacts-contact-list.vala"
	_data15_ = NULL;
#line 109 "../src/contacts-contact-list.vala"
	return self;
#line 584 "contacts-contact-list.c"
}

ContactsContactList*
contacts_contact_list_new (ContactsSettings* settings,
                           ContactsStore* store,
                           FolksQuery* query)
{
#line 109 "../src/contacts-contact-list.vala"
	return contacts_contact_list_construct (CONTACTS_TYPE_CONTACT_LIST, settings, store, query);
#line 594 "contacts-contact-list.c"
}

static void
contacts_contact_list_on_ui_state_changed (ContactsContactList* self,
                                           GObject* obj,
                                           GParamSpec* pspec)
{
	GList* _tmp0_;
	ContactsUiState _tmp8_;
#line 136 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 136 "../src/contacts-contact-list.vala"
	g_return_if_fail (obj != NULL);
#line 136 "../src/contacts-contact-list.vala"
	g_return_if_fail (pspec != NULL);
#line 137 "../src/contacts-contact-list.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 612 "contacts-contact-list.c"
	{
		GList* widget_collection = NULL;
		GList* widget_it = NULL;
#line 137 "../src/contacts-contact-list.vala"
		widget_collection = _tmp0_;
#line 137 "../src/contacts-contact-list.vala"
		for (widget_it = widget_collection; widget_it != NULL; widget_it = widget_it->next) {
#line 620 "contacts-contact-list.c"
			GtkWidget* widget = NULL;
#line 137 "../src/contacts-contact-list.vala"
			widget = (GtkWidget*) widget_it->data;
#line 624 "contacts-contact-list.c"
			{
				ContactsContactListContactDataRow* row = NULL;
				GtkWidget* _tmp1_;
				ContactsContactListContactDataRow* _tmp2_;
				ContactsContactListContactDataRow* _tmp3_;
				ContactsUiState _tmp4_;
				ContactsUiState _tmp5_;
#line 138 "../src/contacts-contact-list.vala"
				_tmp1_ = widget;
#line 138 "../src/contacts-contact-list.vala"
				_tmp2_ = _g_object_ref0 (CONTACTS_CONTACT_LIST_IS_CONTACT_DATA_ROW (_tmp1_) ? ((ContactsContactListContactDataRow*) _tmp1_) : NULL);
#line 138 "../src/contacts-contact-list.vala"
				row = _tmp2_;
#line 139 "../src/contacts-contact-list.vala"
				_tmp3_ = row;
#line 139 "../src/contacts-contact-list.vala"
				_tmp4_ = self->priv->_state;
#line 139 "../src/contacts-contact-list.vala"
				contacts_contact_list_contact_data_row_expose_checkbox (_tmp3_, _tmp4_ == CONTACTS_UI_STATE_SELECTING);
#line 141 "../src/contacts-contact-list.vala"
				_tmp5_ = self->priv->_state;
#line 141 "../src/contacts-contact-list.vala"
				if (_tmp5_ != CONTACTS_UI_STATE_SELECTING) {
#line 648 "contacts-contact-list.c"
					ContactsContactListContactDataRow* _tmp6_;
					GtkCheckButton* _tmp7_;
#line 142 "../src/contacts-contact-list.vala"
					_tmp6_ = row;
#line 142 "../src/contacts-contact-list.vala"
					_tmp7_ = _tmp6_->selector_button;
#line 142 "../src/contacts-contact-list.vala"
					gtk_toggle_button_set_active ((GtkToggleButton*) _tmp7_, FALSE);
#line 657 "contacts-contact-list.c"
				}
#line 137 "../src/contacts-contact-list.vala"
				_g_object_unref0 (row);
#line 661 "contacts-contact-list.c"
			}
		}
#line 137 "../src/contacts-contact-list.vala"
		(widget_collection == NULL) ? NULL : (widget_collection = (g_list_free (widget_collection), NULL));
#line 666 "contacts-contact-list.c"
	}
#line 145 "../src/contacts-contact-list.vala"
	_tmp8_ = self->priv->_state;
#line 145 "../src/contacts-contact-list.vala"
	if (_tmp8_ != CONTACTS_UI_STATE_SELECTING) {
#line 146 "../src/contacts-contact-list.vala"
		self->priv->nr_contacts_marked = 0;
#line 674 "contacts-contact-list.c"
	}
}

static gint
contacts_contact_list_compare_rows (ContactsContactList* self,
                                    GtkListBoxRow* row_a,
                                    GtkListBoxRow* row_b)
{
	FolksIndividual* a = NULL;
	FolksIndividual* _tmp0_;
	FolksIndividual* _tmp1_;
	FolksIndividual* b = NULL;
	FolksIndividual* _tmp2_;
	FolksIndividual* _tmp3_;
	FolksIndividual* _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp6_;
	FolksIndividual* _tmp7_;
	gboolean _tmp8_;
	gboolean _tmp9_;
	const gchar* _tmp14_ = NULL;
	const gchar* a_name = NULL;
	const gchar* _tmp20_ = NULL;
	const gchar* b_name = NULL;
	const gchar* _tmp26_;
	const gchar* _tmp27_;
	gint result = 0;
#line 149 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 149 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (row_a != NULL, 0);
#line 149 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (row_b != NULL, 0);
#line 150 "../src/contacts-contact-list.vala"
	_tmp0_ = G_TYPE_CHECK_INSTANCE_CAST (row_a, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow)->individual;
#line 150 "../src/contacts-contact-list.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 150 "../src/contacts-contact-list.vala"
	a = _tmp1_;
#line 151 "../src/contacts-contact-list.vala"
	_tmp2_ = G_TYPE_CHECK_INSTANCE_CAST (row_b, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow)->individual;
#line 151 "../src/contacts-contact-list.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 151 "../src/contacts-contact-list.vala"
	b = _tmp3_;
#line 154 "../src/contacts-contact-list.vala"
	_tmp4_ = a;
#line 154 "../src/contacts-contact-list.vala"
	_tmp5_ = folks_favourite_details_get_is_favourite ((FolksFavouriteDetails*) _tmp4_);
#line 154 "../src/contacts-contact-list.vala"
	_tmp6_ = _tmp5_;
#line 154 "../src/contacts-contact-list.vala"
	_tmp7_ = b;
#line 154 "../src/contacts-contact-list.vala"
	_tmp8_ = folks_favourite_details_get_is_favourite ((FolksFavouriteDetails*) _tmp7_);
#line 154 "../src/contacts-contact-list.vala"
	_tmp9_ = _tmp8_;
#line 154 "../src/contacts-contact-list.vala"
	if (_tmp6_ != _tmp9_) {
#line 734 "contacts-contact-list.c"
		gint _tmp10_ = 0;
		FolksIndividual* _tmp11_;
		gboolean _tmp12_;
		gboolean _tmp13_;
#line 155 "../src/contacts-contact-list.vala"
		_tmp11_ = a;
#line 155 "../src/contacts-contact-list.vala"
		_tmp12_ = folks_favourite_details_get_is_favourite ((FolksFavouriteDetails*) _tmp11_);
#line 155 "../src/contacts-contact-list.vala"
		_tmp13_ = _tmp12_;
#line 155 "../src/contacts-contact-list.vala"
		if (_tmp13_) {
#line 155 "../src/contacts-contact-list.vala"
			_tmp10_ = -1;
#line 749 "contacts-contact-list.c"
		} else {
#line 155 "../src/contacts-contact-list.vala"
			_tmp10_ = 1;
#line 753 "contacts-contact-list.c"
		}
#line 155 "../src/contacts-contact-list.vala"
		result = _tmp10_;
#line 155 "../src/contacts-contact-list.vala"
		_g_object_unref0 (b);
#line 155 "../src/contacts-contact-list.vala"
		_g_object_unref0 (a);
#line 155 "../src/contacts-contact-list.vala"
		return result;
#line 763 "contacts-contact-list.c"
	}
#line 158 "../src/contacts-contact-list.vala"
	if (self->priv->sort_on_surname) {
#line 767 "contacts-contact-list.c"
		FolksIndividual* _tmp15_;
		const gchar* _tmp16_;
#line 158 "../src/contacts-contact-list.vala"
		_tmp15_ = a;
#line 158 "../src/contacts-contact-list.vala"
		_tmp16_ = contacts_contact_list_try_get_surname (self, _tmp15_);
#line 158 "../src/contacts-contact-list.vala"
		_tmp14_ = _tmp16_;
#line 776 "contacts-contact-list.c"
	} else {
		FolksIndividual* _tmp17_;
		const gchar* _tmp18_;
		const gchar* _tmp19_;
#line 158 "../src/contacts-contact-list.vala"
		_tmp17_ = a;
#line 158 "../src/contacts-contact-list.vala"
		_tmp18_ = folks_individual_get_display_name (_tmp17_);
#line 158 "../src/contacts-contact-list.vala"
		_tmp19_ = _tmp18_;
#line 158 "../src/contacts-contact-list.vala"
		_tmp14_ = _tmp19_;
#line 789 "contacts-contact-list.c"
	}
#line 158 "../src/contacts-contact-list.vala"
	a_name = _tmp14_;
#line 159 "../src/contacts-contact-list.vala"
	if (self->priv->sort_on_surname) {
#line 795 "contacts-contact-list.c"
		FolksIndividual* _tmp21_;
		const gchar* _tmp22_;
#line 159 "../src/contacts-contact-list.vala"
		_tmp21_ = b;
#line 159 "../src/contacts-contact-list.vala"
		_tmp22_ = contacts_contact_list_try_get_surname (self, _tmp21_);
#line 159 "../src/contacts-contact-list.vala"
		_tmp20_ = _tmp22_;
#line 804 "contacts-contact-list.c"
	} else {
		FolksIndividual* _tmp23_;
		const gchar* _tmp24_;
		const gchar* _tmp25_;
#line 159 "../src/contacts-contact-list.vala"
		_tmp23_ = b;
#line 159 "../src/contacts-contact-list.vala"
		_tmp24_ = folks_individual_get_display_name (_tmp23_);
#line 159 "../src/contacts-contact-list.vala"
		_tmp25_ = _tmp24_;
#line 159 "../src/contacts-contact-list.vala"
		_tmp20_ = _tmp25_;
#line 817 "contacts-contact-list.c"
	}
#line 159 "../src/contacts-contact-list.vala"
	b_name = _tmp20_;
#line 161 "../src/contacts-contact-list.vala"
	_tmp26_ = a_name;
#line 161 "../src/contacts-contact-list.vala"
	_tmp27_ = b_name;
#line 161 "../src/contacts-contact-list.vala"
	result = g_utf8_collate (_tmp26_, _tmp27_);
#line 161 "../src/contacts-contact-list.vala"
	_g_object_unref0 (b);
#line 161 "../src/contacts-contact-list.vala"
	_g_object_unref0 (a);
#line 161 "../src/contacts-contact-list.vala"
	return result;
#line 833 "contacts-contact-list.c"
}

static const gchar*
contacts_contact_list_try_get_surname (ContactsContactList* self,
                                       FolksIndividual* indiv)
{
	gboolean _tmp0_ = FALSE;
	FolksStructuredName* _tmp1_;
	FolksStructuredName* _tmp2_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	const gchar* result = NULL;
#line 164 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 164 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (indiv != NULL, NULL);
#line 165 "../src/contacts-contact-list.vala"
	_tmp1_ = folks_name_details_get_structured_name ((FolksNameDetails*) indiv);
#line 165 "../src/contacts-contact-list.vala"
	_tmp2_ = _tmp1_;
#line 165 "../src/contacts-contact-list.vala"
	if (_tmp2_ != NULL) {
#line 856 "contacts-contact-list.c"
		FolksStructuredName* _tmp3_;
		FolksStructuredName* _tmp4_;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
#line 165 "../src/contacts-contact-list.vala"
		_tmp3_ = folks_name_details_get_structured_name ((FolksNameDetails*) indiv);
#line 165 "../src/contacts-contact-list.vala"
		_tmp4_ = _tmp3_;
#line 165 "../src/contacts-contact-list.vala"
		_tmp5_ = folks_structured_name_get_family_name (_tmp4_);
#line 165 "../src/contacts-contact-list.vala"
		_tmp6_ = _tmp5_;
#line 165 "../src/contacts-contact-list.vala"
		_tmp0_ = g_strcmp0 (_tmp6_, "") != 0;
#line 871 "contacts-contact-list.c"
	} else {
#line 165 "../src/contacts-contact-list.vala"
		_tmp0_ = FALSE;
#line 875 "contacts-contact-list.c"
	}
#line 165 "../src/contacts-contact-list.vala"
	if (_tmp0_) {
#line 879 "contacts-contact-list.c"
		FolksStructuredName* _tmp7_;
		FolksStructuredName* _tmp8_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
#line 166 "../src/contacts-contact-list.vala"
		_tmp7_ = folks_name_details_get_structured_name ((FolksNameDetails*) indiv);
#line 166 "../src/contacts-contact-list.vala"
		_tmp8_ = _tmp7_;
#line 166 "../src/contacts-contact-list.vala"
		_tmp9_ = folks_structured_name_get_family_name (_tmp8_);
#line 166 "../src/contacts-contact-list.vala"
		_tmp10_ = _tmp9_;
#line 166 "../src/contacts-contact-list.vala"
		result = _tmp10_;
#line 166 "../src/contacts-contact-list.vala"
		return result;
#line 896 "contacts-contact-list.c"
	}
#line 169 "../src/contacts-contact-list.vala"
	_tmp11_ = folks_individual_get_display_name (indiv);
#line 169 "../src/contacts-contact-list.vala"
	_tmp12_ = _tmp11_;
#line 169 "../src/contacts-contact-list.vala"
	result = _tmp12_;
#line 169 "../src/contacts-contact-list.vala"
	return result;
#line 906 "contacts-contact-list.c"
}

static void
contacts_contact_list_update_header (ContactsContactList* self,
                                     GtkListBoxRow* row,
                                     GtkListBoxRow* before)
{
	FolksIndividual* current = NULL;
	FolksIndividual* _tmp0_;
	FolksIndividual* _tmp1_;
	FolksIndividual* previous = NULL;
	FolksIndividual* _tmp9_;
	FolksIndividual* _tmp10_;
	gboolean _tmp11_ = FALSE;
	FolksIndividual* _tmp12_;
	gboolean _tmp13_;
	gboolean _tmp14_;
#line 172 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 172 "../src/contacts-contact-list.vala"
	g_return_if_fail (row != NULL);
#line 173 "../src/contacts-contact-list.vala"
	_tmp0_ = G_TYPE_CHECK_INSTANCE_CAST (row, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow)->individual;
#line 173 "../src/contacts-contact-list.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 173 "../src/contacts-contact-list.vala"
	current = _tmp1_;
#line 175 "../src/contacts-contact-list.vala"
	if (before == NULL) {
#line 936 "contacts-contact-list.c"
		FolksIndividual* _tmp2_;
		gboolean _tmp3_;
		gboolean _tmp4_;
#line 176 "../src/contacts-contact-list.vala"
		_tmp2_ = current;
#line 176 "../src/contacts-contact-list.vala"
		_tmp3_ = folks_favourite_details_get_is_favourite ((FolksFavouriteDetails*) _tmp2_);
#line 176 "../src/contacts-contact-list.vala"
		_tmp4_ = _tmp3_;
#line 176 "../src/contacts-contact-list.vala"
		if (_tmp4_) {
#line 948 "contacts-contact-list.c"
			GtkLabel* _tmp5_;
			GtkLabel* _tmp6_;
#line 177 "../src/contacts-contact-list.vala"
			_tmp5_ = contacts_contact_list_create_header_label (self, _ ("Favorites"));
#line 177 "../src/contacts-contact-list.vala"
			_tmp6_ = _tmp5_;
#line 177 "../src/contacts-contact-list.vala"
			gtk_list_box_row_set_header (row, (GtkWidget*) _tmp6_);
#line 177 "../src/contacts-contact-list.vala"
			_g_object_unref0 (_tmp6_);
#line 959 "contacts-contact-list.c"
		} else {
			GtkLabel* _tmp7_;
			GtkLabel* _tmp8_;
#line 179 "../src/contacts-contact-list.vala"
			_tmp7_ = contacts_contact_list_create_header_label (self, _ ("All Contacts"));
#line 179 "../src/contacts-contact-list.vala"
			_tmp8_ = _tmp7_;
#line 179 "../src/contacts-contact-list.vala"
			gtk_list_box_row_set_header (row, (GtkWidget*) _tmp8_);
#line 179 "../src/contacts-contact-list.vala"
			_g_object_unref0 (_tmp8_);
#line 971 "contacts-contact-list.c"
		}
#line 180 "../src/contacts-contact-list.vala"
		_g_object_unref0 (current);
#line 180 "../src/contacts-contact-list.vala"
		return;
#line 977 "contacts-contact-list.c"
	}
#line 183 "../src/contacts-contact-list.vala"
	_tmp9_ = G_TYPE_CHECK_INSTANCE_CAST (before, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow)->individual;
#line 183 "../src/contacts-contact-list.vala"
	_tmp10_ = _g_object_ref0 (_tmp9_);
#line 183 "../src/contacts-contact-list.vala"
	previous = _tmp10_;
#line 184 "../src/contacts-contact-list.vala"
	_tmp12_ = current;
#line 184 "../src/contacts-contact-list.vala"
	_tmp13_ = folks_favourite_details_get_is_favourite ((FolksFavouriteDetails*) _tmp12_);
#line 184 "../src/contacts-contact-list.vala"
	_tmp14_ = _tmp13_;
#line 184 "../src/contacts-contact-list.vala"
	if (!_tmp14_) {
#line 993 "contacts-contact-list.c"
		FolksIndividual* _tmp15_;
		gboolean _tmp16_;
		gboolean _tmp17_;
#line 184 "../src/contacts-contact-list.vala"
		_tmp15_ = previous;
#line 184 "../src/contacts-contact-list.vala"
		_tmp16_ = folks_favourite_details_get_is_favourite ((FolksFavouriteDetails*) _tmp15_);
#line 184 "../src/contacts-contact-list.vala"
		_tmp17_ = _tmp16_;
#line 184 "../src/contacts-contact-list.vala"
		_tmp11_ = _tmp17_;
#line 1005 "contacts-contact-list.c"
	} else {
#line 184 "../src/contacts-contact-list.vala"
		_tmp11_ = FALSE;
#line 1009 "contacts-contact-list.c"
	}
#line 184 "../src/contacts-contact-list.vala"
	if (_tmp11_) {
#line 1013 "contacts-contact-list.c"
		GtkLabel* _tmp18_;
		GtkLabel* _tmp19_;
#line 185 "../src/contacts-contact-list.vala"
		_tmp18_ = contacts_contact_list_create_header_label (self, _ ("All Contacts"));
#line 185 "../src/contacts-contact-list.vala"
		_tmp19_ = _tmp18_;
#line 185 "../src/contacts-contact-list.vala"
		gtk_list_box_row_set_header (row, (GtkWidget*) _tmp19_);
#line 185 "../src/contacts-contact-list.vala"
		_g_object_unref0 (_tmp19_);
#line 1024 "contacts-contact-list.c"
	} else {
#line 187 "../src/contacts-contact-list.vala"
		gtk_list_box_row_set_header (row, NULL);
#line 1028 "contacts-contact-list.c"
	}
#line 172 "../src/contacts-contact-list.vala"
	_g_object_unref0 (previous);
#line 172 "../src/contacts-contact-list.vala"
	_g_object_unref0 (current);
#line 1034 "contacts-contact-list.c"
}

static GtkLabel*
contacts_contact_list_create_header_label (ContactsContactList* self,
                                           const gchar* text)
{
	GtkLabel* label = NULL;
	GtkLabel* _tmp0_;
	PangoAttrList* attrs = NULL;
	PangoAttrList* _tmp1_;
	PangoAttribute* _tmp2_;
	PangoAttribute* _tmp3_;
	PangoAttribute* _tmp4_;
	GtkLabel* result = NULL;
#line 191 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 191 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (text != NULL, NULL);
#line 192 "../src/contacts-contact-list.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new (text);
#line 192 "../src/contacts-contact-list.vala"
	g_object_ref_sink (_tmp0_);
#line 192 "../src/contacts-contact-list.vala"
	label = _tmp0_;
#line 193 "../src/contacts-contact-list.vala"
	gtk_widget_set_halign ((GtkWidget*) label, GTK_ALIGN_START);
#line 194 "../src/contacts-contact-list.vala"
	g_object_set ((GtkWidget*) label, "margin", 3, NULL);
#line 195 "../src/contacts-contact-list.vala"
	gtk_widget_set_margin_start ((GtkWidget*) label, 6);
#line 196 "../src/contacts-contact-list.vala"
	gtk_widget_set_margin_top ((GtkWidget*) label, 6);
#line 197 "../src/contacts-contact-list.vala"
	_tmp1_ = pango_attr_list_new ();
#line 197 "../src/contacts-contact-list.vala"
	attrs = _tmp1_;
#line 198 "../src/contacts-contact-list.vala"
	_tmp2_ = pango_attr_weight_new (PANGO_WEIGHT_BOLD);
#line 198 "../src/contacts-contact-list.vala"
	pango_attr_list_insert (attrs, _tmp2_);
#line 199 "../src/contacts-contact-list.vala"
	_tmp3_ = pango_attr_scale_new ((PANGO_SCALE_SMALL + PANGO_SCALE_MEDIUM) / 2.0);
#line 199 "../src/contacts-contact-list.vala"
	pango_attr_list_insert (attrs, _tmp3_);
#line 200 "../src/contacts-contact-list.vala"
	_tmp4_ = pango_attr_foreground_alpha_new ((guint16) 30000);
#line 200 "../src/contacts-contact-list.vala"
	pango_attr_list_insert (attrs, _tmp4_);
#line 201 "../src/contacts-contact-list.vala"
	gtk_label_set_attributes (label, attrs);
#line 202 "../src/contacts-contact-list.vala"
	result = label;
#line 202 "../src/contacts-contact-list.vala"
	_pango_attr_list_unref0 (attrs);
#line 202 "../src/contacts-contact-list.vala"
	return result;
#line 1091 "contacts-contact-list.c"
}

static Block16Data*
block16_data_ref (Block16Data* _data16_)
{
#line 207 "../src/contacts-contact-list.vala"
	g_atomic_int_inc (&_data16_->_ref_count_);
#line 207 "../src/contacts-contact-list.vala"
	return _data16_;
#line 1101 "contacts-contact-list.c"
}

static void
block16_data_unref (void * _userdata_)
{
	Block16Data* _data16_;
	_data16_ = (Block16Data*) _userdata_;
#line 207 "../src/contacts-contact-list.vala"
	if (g_atomic_int_dec_and_test (&_data16_->_ref_count_)) {
#line 1111 "contacts-contact-list.c"
		ContactsContactList* self;
#line 207 "../src/contacts-contact-list.vala"
		self = _data16_->self;
#line 207 "../src/contacts-contact-list.vala"
		_g_object_unref0 (_data16_->row);
#line 207 "../src/contacts-contact-list.vala"
		_g_object_unref0 (self);
#line 207 "../src/contacts-contact-list.vala"
		g_slice_free (Block16Data, _data16_);
#line 1121 "contacts-contact-list.c"
	}
}

static void
___lambda7_ (Block16Data* _data16_)
{
	ContactsContactList* self;
	ContactsContactListContactDataRow* _tmp0_;
#line 209 "../src/contacts-contact-list.vala"
	self = _data16_->self;
#line 209 "../src/contacts-contact-list.vala"
	_tmp0_ = _data16_->row;
#line 209 "../src/contacts-contact-list.vala"
	contacts_contact_list_on_row_checkbox_toggled (self, _tmp0_);
#line 1136 "contacts-contact-list.c"
}

static void
____lambda7__gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                        gpointer self)
{
#line 209 "../src/contacts-contact-list.vala"
	___lambda7_ (self);
#line 1145 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_added_cb (ContactsContactList* self,
                                        ContactsStore* store,
                                        FolksIndividual* i)
{
#line 205 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 205 "../src/contacts-contact-list.vala"
	g_return_if_fail (store != NULL);
#line 205 "../src/contacts-contact-list.vala"
	g_return_if_fail (i != NULL);
#line 207 "../src/contacts-contact-list.vala"
	if (!contacts_utils_is_ignorable (i)) {
#line 1161 "contacts-contact-list.c"
		Block16Data* _data16_;
		ContactsContactListContactDataRow* _tmp0_;
		ContactsContactListContactDataRow* _tmp1_;
		GtkCheckButton* _tmp2_;
		ContactsContactListContactDataRow* _tmp3_;
		GtkCheckButton* _tmp4_;
		ContactsUiState _tmp5_;
		ContactsContactListContactDataRow* _tmp6_;
#line 207 "../src/contacts-contact-list.vala"
		_data16_ = g_slice_new0 (Block16Data);
#line 207 "../src/contacts-contact-list.vala"
		_data16_->_ref_count_ = 1;
#line 207 "../src/contacts-contact-list.vala"
		_data16_->self = g_object_ref (self);
#line 208 "../src/contacts-contact-list.vala"
		_tmp0_ = contacts_contact_list_contact_data_row_new (i);
#line 208 "../src/contacts-contact-list.vala"
		g_object_ref_sink (_tmp0_);
#line 208 "../src/contacts-contact-list.vala"
		_data16_->row = _tmp0_;
#line 209 "../src/contacts-contact-list.vala"
		_tmp1_ = _data16_->row;
#line 209 "../src/contacts-contact-list.vala"
		_tmp2_ = _tmp1_->selector_button;
#line 209 "../src/contacts-contact-list.vala"
		g_signal_connect_data ((GtkToggleButton*) _tmp2_, "toggled", (GCallback) ____lambda7__gtk_toggle_button_toggled, block16_data_ref (_data16_), (GClosureNotify) block16_data_unref, 0);
#line 210 "../src/contacts-contact-list.vala"
		_tmp3_ = _data16_->row;
#line 210 "../src/contacts-contact-list.vala"
		_tmp4_ = _tmp3_->selector_button;
#line 210 "../src/contacts-contact-list.vala"
		_tmp5_ = self->priv->_state;
#line 210 "../src/contacts-contact-list.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp4_, _tmp5_ == CONTACTS_UI_STATE_SELECTING);
#line 212 "../src/contacts-contact-list.vala"
		_tmp6_ = _data16_->row;
#line 212 "../src/contacts-contact-list.vala"
		gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp6_);
#line 207 "../src/contacts-contact-list.vala"
		block16_data_unref (_data16_);
#line 207 "../src/contacts-contact-list.vala"
		_data16_ = NULL;
#line 1204 "contacts-contact-list.c"
	} else {
		const gchar* _tmp7_;
		const gchar* _tmp8_;
#line 214 "../src/contacts-contact-list.vala"
		_tmp7_ = folks_individual_get_id (i);
#line 214 "../src/contacts-contact-list.vala"
		_tmp8_ = _tmp7_;
#line 214 "../src/contacts-contact-list.vala"
		g_debug ("contacts-contact-list.vala:214: Contact %s was ignored", _tmp8_);
#line 1214 "contacts-contact-list.c"
	}
}

static void
contacts_contact_list_on_row_checkbox_toggled (ContactsContactList* self,
                                               ContactsContactListContactDataRow* row)
{
	gint _tmp0_ = 0;
	GtkCheckButton* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_ = FALSE;
	GtkCheckButton* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_ = FALSE;
	GtkCheckButton* _tmp9_;
	gboolean _tmp10_;
	gboolean _tmp11_;
#line 218 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 218 "../src/contacts-contact-list.vala"
	g_return_if_fail (row != NULL);
#line 219 "../src/contacts-contact-list.vala"
	_tmp1_ = row->selector_button;
#line 219 "../src/contacts-contact-list.vala"
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
#line 219 "../src/contacts-contact-list.vala"
	_tmp3_ = _tmp2_;
#line 219 "../src/contacts-contact-list.vala"
	if (_tmp3_) {
#line 219 "../src/contacts-contact-list.vala"
		_tmp0_ = 1;
#line 1248 "contacts-contact-list.c"
	} else {
#line 219 "../src/contacts-contact-list.vala"
		_tmp0_ = -1;
#line 1252 "contacts-contact-list.c"
	}
#line 219 "../src/contacts-contact-list.vala"
	self->priv->nr_contacts_marked = self->priv->nr_contacts_marked + _tmp0_;
#line 222 "../src/contacts-contact-list.vala"
	_tmp5_ = row->selector_button;
#line 222 "../src/contacts-contact-list.vala"
	_tmp6_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp5_);
#line 222 "../src/contacts-contact-list.vala"
	_tmp7_ = _tmp6_;
#line 222 "../src/contacts-contact-list.vala"
	if (_tmp7_) {
#line 222 "../src/contacts-contact-list.vala"
		_tmp4_ = self->priv->nr_contacts_marked == 1;
#line 1266 "contacts-contact-list.c"
	} else {
#line 222 "../src/contacts-contact-list.vala"
		_tmp4_ = FALSE;
#line 1270 "contacts-contact-list.c"
	}
#line 222 "../src/contacts-contact-list.vala"
	if (_tmp4_) {
#line 223 "../src/contacts-contact-list.vala"
		contacts_contact_list_set_state (self, CONTACTS_UI_STATE_SELECTING);
#line 1276 "contacts-contact-list.c"
	}
#line 227 "../src/contacts-contact-list.vala"
	_tmp9_ = row->selector_button;
#line 227 "../src/contacts-contact-list.vala"
	_tmp10_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp9_);
#line 227 "../src/contacts-contact-list.vala"
	_tmp11_ = _tmp10_;
#line 227 "../src/contacts-contact-list.vala"
	if (!_tmp11_) {
#line 227 "../src/contacts-contact-list.vala"
		_tmp8_ = self->priv->nr_contacts_marked == 0;
#line 1288 "contacts-contact-list.c"
	} else {
#line 227 "../src/contacts-contact-list.vala"
		_tmp8_ = FALSE;
#line 1292 "contacts-contact-list.c"
	}
#line 227 "../src/contacts-contact-list.vala"
	if (_tmp8_) {
#line 228 "../src/contacts-contact-list.vala"
		contacts_contact_list_set_state (self, CONTACTS_UI_STATE_SHOWING);
#line 1298 "contacts-contact-list.c"
	}
#line 230 "../src/contacts-contact-list.vala"
	g_signal_emit (self, contacts_contact_list_signals[CONTACTS_CONTACT_LIST_CONTACTS_MARKED_SIGNAL], 0, self->priv->nr_contacts_marked);
#line 1302 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_removed_cb (ContactsContactList* self,
                                          ContactsStore* store,
                                          FolksIndividual* i)
{
	ContactsContactListContactDataRow* row = NULL;
	ContactsContactListContactDataRow* _tmp0_;
	ContactsContactListContactDataRow* _tmp1_;
#line 233 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 233 "../src/contacts-contact-list.vala"
	g_return_if_fail (store != NULL);
#line 233 "../src/contacts-contact-list.vala"
	g_return_if_fail (i != NULL);
#line 234 "../src/contacts-contact-list.vala"
	_tmp0_ = contacts_contact_list_find_row_for_contact (self, i);
#line 234 "../src/contacts-contact-list.vala"
	row = _tmp0_;
#line 235 "../src/contacts-contact-list.vala"
	_tmp1_ = row;
#line 235 "../src/contacts-contact-list.vala"
	if (_tmp1_ != NULL) {
#line 1327 "contacts-contact-list.c"
		ContactsContactListContactDataRow* _tmp2_;
#line 236 "../src/contacts-contact-list.vala"
		_tmp2_ = row;
#line 236 "../src/contacts-contact-list.vala"
		gtk_widget_destroy ((GtkWidget*) _tmp2_);
#line 1333 "contacts-contact-list.c"
	}
#line 233 "../src/contacts-contact-list.vala"
	_g_object_unref0 (row);
#line 1337 "contacts-contact-list.c"
}

static void
contacts_contact_list_real_row_selected (GtkListBox* base,
                                         GtkListBoxRow* row)
{
	ContactsContactList * self;
	ContactsContactListContactDataRow* data = NULL;
	ContactsContactListContactDataRow* _tmp0_;
	ContactsContactListContactDataRow* _tmp1_;
	FolksIndividual* _tmp2_ = NULL;
	ContactsContactListContactDataRow* _tmp3_;
	FolksIndividual* individual = NULL;
	FolksIndividual* _tmp6_;
#line 239 "../src/contacts-contact-list.vala"
	self = (ContactsContactList*) base;
#line 240 "../src/contacts-contact-list.vala"
	_tmp0_ = G_TYPE_CHECK_INSTANCE_CAST (row, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow);
#line 240 "../src/contacts-contact-list.vala"
	_tmp1_ = _g_object_ref0 (CONTACTS_CONTACT_LIST_IS_CONTACT_DATA_ROW (_tmp0_) ? ((ContactsContactListContactDataRow*) _tmp0_) : NULL);
#line 240 "../src/contacts-contact-list.vala"
	data = _tmp1_;
#line 241 "../src/contacts-contact-list.vala"
	_tmp3_ = data;
#line 241 "../src/contacts-contact-list.vala"
	if (_tmp3_ != NULL) {
#line 1364 "contacts-contact-list.c"
		ContactsContactListContactDataRow* _tmp4_;
		FolksIndividual* _tmp5_;
#line 241 "../src/contacts-contact-list.vala"
		_tmp4_ = data;
#line 241 "../src/contacts-contact-list.vala"
		_tmp5_ = _tmp4_->individual;
#line 241 "../src/contacts-contact-list.vala"
		_tmp2_ = _tmp5_;
#line 1373 "contacts-contact-list.c"
	} else {
#line 241 "../src/contacts-contact-list.vala"
		_tmp2_ = NULL;
#line 1377 "contacts-contact-list.c"
	}
#line 241 "../src/contacts-contact-list.vala"
	_tmp6_ = _g_object_ref0 (_tmp2_);
#line 241 "../src/contacts-contact-list.vala"
	individual = _tmp6_;
#line 242 "../src/contacts-contact-list.vala"
	g_signal_emit (self, contacts_contact_list_signals[CONTACTS_CONTACT_LIST_SELECTION_CHANGED_SIGNAL], 0, individual);
#line 239 "../src/contacts-contact-list.vala"
	_g_object_unref0 (individual);
#line 239 "../src/contacts-contact-list.vala"
	_g_object_unref0 (data);
#line 1389 "contacts-contact-list.c"
}

static gboolean
contacts_contact_list_filter_row (ContactsContactList* self,
                                  GtkListBoxRow* row)
{
	FolksIndividual* individual = NULL;
	FolksIndividual* _tmp0_;
	FolksIndividual* _tmp1_;
	FolksQuery* _tmp2_;
	gboolean result = FALSE;
#line 249 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 249 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (row != NULL, FALSE);
#line 250 "../src/contacts-contact-list.vala"
	_tmp0_ = G_TYPE_CHECK_INSTANCE_CAST (row, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow)->individual;
#line 250 "../src/contacts-contact-list.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 250 "../src/contacts-contact-list.vala"
	individual = _tmp1_;
#line 251 "../src/contacts-contact-list.vala"
	_tmp2_ = self->priv->filter_query;
#line 251 "../src/contacts-contact-list.vala"
	result = folks_query_is_match (_tmp2_, individual) > ((guint) 0);
#line 251 "../src/contacts-contact-list.vala"
	_g_object_unref0 (individual);
#line 251 "../src/contacts-contact-list.vala"
	return result;
#line 1419 "contacts-contact-list.c"
}

void
contacts_contact_list_select_contact (ContactsContactList* self,
                                      FolksIndividual* individual)
{
	ContactsContactListContactDataRow* _tmp0_;
	ContactsContactListContactDataRow* _tmp1_;
#line 254 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 255 "../src/contacts-contact-list.vala"
	if (individual == NULL) {
#line 257 "../src/contacts-contact-list.vala"
		gtk_list_box_select_row ((GtkListBox*) self, NULL);
#line 258 "../src/contacts-contact-list.vala"
		return;
#line 1436 "contacts-contact-list.c"
	}
#line 261 "../src/contacts-contact-list.vala"
	_tmp0_ = contacts_contact_list_find_row_for_contact (self, individual);
#line 261 "../src/contacts-contact-list.vala"
	_tmp1_ = _tmp0_;
#line 261 "../src/contacts-contact-list.vala"
	gtk_list_box_select_row ((GtkListBox*) self, (GtkListBoxRow*) _tmp1_);
#line 261 "../src/contacts-contact-list.vala"
	_g_object_unref0 (_tmp1_);
#line 1446 "contacts-contact-list.c"
}

void
contacts_contact_list_hide_contact (ContactsContactList* self,
                                    FolksIndividual* individual)
{
#line 264 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 265 "../src/contacts-contact-list.vala"
	if (individual != NULL) {
#line 1457 "contacts-contact-list.c"
		ContactsContactListContactDataRow* _tmp0_;
		ContactsContactListContactDataRow* _tmp1_;
#line 266 "../src/contacts-contact-list.vala"
		_tmp0_ = contacts_contact_list_find_row_for_contact (self, individual);
#line 266 "../src/contacts-contact-list.vala"
		_tmp1_ = _tmp0_;
#line 266 "../src/contacts-contact-list.vala"
		gtk_widget_hide ((GtkWidget*) _tmp1_);
#line 266 "../src/contacts-contact-list.vala"
		_g_object_unref0 (_tmp1_);
#line 1468 "contacts-contact-list.c"
	}
}

static ContactsContactListContactDataRow*
contacts_contact_list_find_row_for_contact (ContactsContactList* self,
                                            FolksIndividual* individual)
{
	GList* _tmp0_;
	ContactsContactListContactDataRow* result = NULL;
#line 271 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 271 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (individual != NULL, NULL);
#line 272 "../src/contacts-contact-list.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 1484 "contacts-contact-list.c"
	{
		GList* widget_collection = NULL;
		GList* widget_it = NULL;
#line 272 "../src/contacts-contact-list.vala"
		widget_collection = _tmp0_;
#line 272 "../src/contacts-contact-list.vala"
		for (widget_it = widget_collection; widget_it != NULL; widget_it = widget_it->next) {
#line 1492 "contacts-contact-list.c"
			GtkWidget* widget = NULL;
#line 272 "../src/contacts-contact-list.vala"
			widget = (GtkWidget*) widget_it->data;
#line 1496 "contacts-contact-list.c"
			{
				ContactsContactListContactDataRow* row = NULL;
				GtkWidget* _tmp1_;
				ContactsContactListContactDataRow* _tmp2_;
				ContactsContactListContactDataRow* _tmp3_;
				FolksIndividual* _tmp4_;
#line 273 "../src/contacts-contact-list.vala"
				_tmp1_ = widget;
#line 273 "../src/contacts-contact-list.vala"
				_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow));
#line 273 "../src/contacts-contact-list.vala"
				row = _tmp2_;
#line 274 "../src/contacts-contact-list.vala"
				_tmp3_ = row;
#line 274 "../src/contacts-contact-list.vala"
				_tmp4_ = _tmp3_->individual;
#line 274 "../src/contacts-contact-list.vala"
				if (_tmp4_ == individual) {
#line 275 "../src/contacts-contact-list.vala"
					result = row;
#line 275 "../src/contacts-contact-list.vala"
					(widget_collection == NULL) ? NULL : (widget_collection = (g_list_free (widget_collection), NULL));
#line 275 "../src/contacts-contact-list.vala"
					return result;
#line 1521 "contacts-contact-list.c"
				}
#line 272 "../src/contacts-contact-list.vala"
				_g_object_unref0 (row);
#line 1525 "contacts-contact-list.c"
			}
		}
#line 272 "../src/contacts-contact-list.vala"
		(widget_collection == NULL) ? NULL : (widget_collection = (g_list_free (widget_collection), NULL));
#line 1530 "contacts-contact-list.c"
	}
#line 278 "../src/contacts-contact-list.vala"
	result = NULL;
#line 278 "../src/contacts-contact-list.vala"
	return result;
#line 1536 "contacts-contact-list.c"
}

GeeLinkedList*
contacts_contact_list_get_marked_contacts (ContactsContactList* self)
{
	GeeLinkedList* cs = NULL;
	GeeLinkedList* _tmp0_;
	GList* _tmp1_;
	GeeLinkedList* result = NULL;
#line 281 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 282 "../src/contacts-contact-list.vala"
	_tmp0_ = gee_linked_list_new (FOLKS_TYPE_INDIVIDUAL, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 282 "../src/contacts-contact-list.vala"
	cs = _tmp0_;
#line 283 "../src/contacts-contact-list.vala"
	_tmp1_ = gtk_container_get_children ((GtkContainer*) self);
#line 1554 "contacts-contact-list.c"
	{
		GList* widget_collection = NULL;
		GList* widget_it = NULL;
#line 283 "../src/contacts-contact-list.vala"
		widget_collection = _tmp1_;
#line 283 "../src/contacts-contact-list.vala"
		for (widget_it = widget_collection; widget_it != NULL; widget_it = widget_it->next) {
#line 1562 "contacts-contact-list.c"
			GtkWidget* widget = NULL;
#line 283 "../src/contacts-contact-list.vala"
			widget = (GtkWidget*) widget_it->data;
#line 1566 "contacts-contact-list.c"
			{
				ContactsContactListContactDataRow* row = NULL;
				GtkWidget* _tmp2_;
				ContactsContactListContactDataRow* _tmp3_;
				ContactsContactListContactDataRow* _tmp4_;
				GtkCheckButton* _tmp5_;
				gboolean _tmp6_;
				gboolean _tmp7_;
#line 284 "../src/contacts-contact-list.vala"
				_tmp2_ = widget;
#line 284 "../src/contacts-contact-list.vala"
				_tmp3_ = _g_object_ref0 (CONTACTS_CONTACT_LIST_IS_CONTACT_DATA_ROW (_tmp2_) ? ((ContactsContactListContactDataRow*) _tmp2_) : NULL);
#line 284 "../src/contacts-contact-list.vala"
				row = _tmp3_;
#line 285 "../src/contacts-contact-list.vala"
				_tmp4_ = row;
#line 285 "../src/contacts-contact-list.vala"
				_tmp5_ = _tmp4_->selector_button;
#line 285 "../src/contacts-contact-list.vala"
				_tmp6_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp5_);
#line 285 "../src/contacts-contact-list.vala"
				_tmp7_ = _tmp6_;
#line 285 "../src/contacts-contact-list.vala"
				if (_tmp7_) {
#line 1591 "contacts-contact-list.c"
					GeeLinkedList* _tmp8_;
					ContactsContactListContactDataRow* _tmp9_;
					FolksIndividual* _tmp10_;
#line 286 "../src/contacts-contact-list.vala"
					_tmp8_ = cs;
#line 286 "../src/contacts-contact-list.vala"
					_tmp9_ = row;
#line 286 "../src/contacts-contact-list.vala"
					_tmp10_ = _tmp9_->individual;
#line 286 "../src/contacts-contact-list.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp8_, _tmp10_);
#line 1603 "contacts-contact-list.c"
				}
#line 283 "../src/contacts-contact-list.vala"
				_g_object_unref0 (row);
#line 1607 "contacts-contact-list.c"
			}
		}
#line 283 "../src/contacts-contact-list.vala"
		(widget_collection == NULL) ? NULL : (widget_collection = (g_list_free (widget_collection), NULL));
#line 1612 "contacts-contact-list.c"
	}
#line 288 "../src/contacts-contact-list.vala"
	result = cs;
#line 288 "../src/contacts-contact-list.vala"
	return result;
#line 1618 "contacts-contact-list.c"
}

GeeLinkedList*
contacts_contact_list_get_marked_contacts_and_hide (ContactsContactList* self)
{
	GeeLinkedList* cs = NULL;
	GeeLinkedList* _tmp0_;
	GList* _tmp1_;
	GeeLinkedList* result = NULL;
#line 291 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 292 "../src/contacts-contact-list.vala"
	_tmp0_ = gee_linked_list_new (FOLKS_TYPE_INDIVIDUAL, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 292 "../src/contacts-contact-list.vala"
	cs = _tmp0_;
#line 293 "../src/contacts-contact-list.vala"
	_tmp1_ = gtk_container_get_children ((GtkContainer*) self);
#line 1636 "contacts-contact-list.c"
	{
		GList* widget_collection = NULL;
		GList* widget_it = NULL;
#line 293 "../src/contacts-contact-list.vala"
		widget_collection = _tmp1_;
#line 293 "../src/contacts-contact-list.vala"
		for (widget_it = widget_collection; widget_it != NULL; widget_it = widget_it->next) {
#line 1644 "contacts-contact-list.c"
			GtkWidget* widget = NULL;
#line 293 "../src/contacts-contact-list.vala"
			widget = (GtkWidget*) widget_it->data;
#line 1648 "contacts-contact-list.c"
			{
				ContactsContactListContactDataRow* row = NULL;
				GtkWidget* _tmp2_;
				ContactsContactListContactDataRow* _tmp3_;
				ContactsContactListContactDataRow* _tmp4_;
				GtkCheckButton* _tmp5_;
				gboolean _tmp6_;
				gboolean _tmp7_;
#line 294 "../src/contacts-contact-list.vala"
				_tmp2_ = widget;
#line 294 "../src/contacts-contact-list.vala"
				_tmp3_ = _g_object_ref0 (CONTACTS_CONTACT_LIST_IS_CONTACT_DATA_ROW (_tmp2_) ? ((ContactsContactListContactDataRow*) _tmp2_) : NULL);
#line 294 "../src/contacts-contact-list.vala"
				row = _tmp3_;
#line 295 "../src/contacts-contact-list.vala"
				_tmp4_ = row;
#line 295 "../src/contacts-contact-list.vala"
				_tmp5_ = _tmp4_->selector_button;
#line 295 "../src/contacts-contact-list.vala"
				_tmp6_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp5_);
#line 295 "../src/contacts-contact-list.vala"
				_tmp7_ = _tmp6_;
#line 295 "../src/contacts-contact-list.vala"
				if (_tmp7_) {
#line 1673 "contacts-contact-list.c"
					ContactsContactListContactDataRow* _tmp8_;
					GeeLinkedList* _tmp9_;
					ContactsContactListContactDataRow* _tmp10_;
					FolksIndividual* _tmp11_;
#line 296 "../src/contacts-contact-list.vala"
					_tmp8_ = row;
#line 296 "../src/contacts-contact-list.vala"
					gtk_widget_set_visible ((GtkWidget*) _tmp8_, FALSE);
#line 297 "../src/contacts-contact-list.vala"
					_tmp9_ = cs;
#line 297 "../src/contacts-contact-list.vala"
					_tmp10_ = row;
#line 297 "../src/contacts-contact-list.vala"
					_tmp11_ = _tmp10_->individual;
#line 297 "../src/contacts-contact-list.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp9_, _tmp11_);
#line 1690 "contacts-contact-list.c"
				}
#line 293 "../src/contacts-contact-list.vala"
				_g_object_unref0 (row);
#line 1694 "contacts-contact-list.c"
			}
		}
#line 293 "../src/contacts-contact-list.vala"
		(widget_collection == NULL) ? NULL : (widget_collection = (g_list_free (widget_collection), NULL));
#line 1699 "contacts-contact-list.c"
	}
#line 300 "../src/contacts-contact-list.vala"
	result = cs;
#line 300 "../src/contacts-contact-list.vala"
	return result;
#line 1705 "contacts-contact-list.c"
}

static gboolean
contacts_contact_list_real_button_press_event (GtkWidget* base,
                                               GdkEventButton* event)
{
	ContactsContactList * self;
	gboolean result = FALSE;
#line 304 "../src/contacts-contact-list.vala"
	self = (ContactsContactList*) base;
#line 304 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 305 "../src/contacts-contact-list.vala"
	GTK_WIDGET_CLASS (contacts_contact_list_parent_class)->button_press_event ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_list_box_get_type (), GtkListBox), event);
#line 307 "../src/contacts-contact-list.vala"
	if (event->button == ((guint) GDK_BUTTON_SECONDARY)) {
#line 1722 "contacts-contact-list.c"
		ContactsContactListContactDataRow* row = NULL;
		GtkListBoxRow* _tmp0_;
		ContactsContactListContactDataRow* _tmp1_;
		ContactsContactListContactDataRow* _tmp2_;
#line 308 "../src/contacts-contact-list.vala"
		_tmp0_ = gtk_list_box_get_row_at_y ((GtkListBox*) self, (gint) round (event->y));
#line 308 "../src/contacts-contact-list.vala"
		_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow));
#line 308 "../src/contacts-contact-list.vala"
		row = _tmp1_;
#line 309 "../src/contacts-contact-list.vala"
		_tmp2_ = row;
#line 309 "../src/contacts-contact-list.vala"
		if (_tmp2_ != NULL) {
#line 1737 "contacts-contact-list.c"
			ContactsContactListContactDataRow* _tmp3_;
			gboolean _tmp4_ = FALSE;
			ContactsUiState _tmp5_;
			ContactsContactListContactDataRow* _tmp10_;
			GtkCheckButton* _tmp11_;
#line 310 "../src/contacts-contact-list.vala"
			_tmp3_ = row;
#line 310 "../src/contacts-contact-list.vala"
			gtk_list_box_select_row ((GtkListBox*) self, (GtkListBoxRow*) _tmp3_);
#line 311 "../src/contacts-contact-list.vala"
			_tmp5_ = self->priv->_state;
#line 311 "../src/contacts-contact-list.vala"
			if (_tmp5_ != CONTACTS_UI_STATE_SELECTING) {
#line 311 "../src/contacts-contact-list.vala"
				_tmp4_ = TRUE;
#line 1753 "contacts-contact-list.c"
			} else {
				ContactsContactListContactDataRow* _tmp6_;
				GtkCheckButton* _tmp7_;
				gboolean _tmp8_;
				gboolean _tmp9_;
#line 311 "../src/contacts-contact-list.vala"
				_tmp6_ = row;
#line 311 "../src/contacts-contact-list.vala"
				_tmp7_ = _tmp6_->selector_button;
#line 311 "../src/contacts-contact-list.vala"
				_tmp8_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp7_);
#line 311 "../src/contacts-contact-list.vala"
				_tmp9_ = _tmp8_;
#line 311 "../src/contacts-contact-list.vala"
				_tmp4_ = !_tmp9_;
#line 1769 "contacts-contact-list.c"
			}
#line 311 "../src/contacts-contact-list.vala"
			_tmp10_ = row;
#line 311 "../src/contacts-contact-list.vala"
			_tmp11_ = _tmp10_->selector_button;
#line 311 "../src/contacts-contact-list.vala"
			gtk_toggle_button_set_active ((GtkToggleButton*) _tmp11_, _tmp4_);
#line 1777 "contacts-contact-list.c"
		}
#line 307 "../src/contacts-contact-list.vala"
		_g_object_unref0 (row);
#line 1781 "contacts-contact-list.c"
	}
#line 315 "../src/contacts-contact-list.vala"
	result = FALSE;
#line 315 "../src/contacts-contact-list.vala"
	return result;
#line 1787 "contacts-contact-list.c"
}

ContactsUiState
contacts_contact_list_get_state (ContactsContactList* self)
{
	ContactsUiState result;
	ContactsUiState _tmp0_;
#line 107 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 107 "../src/contacts-contact-list.vala"
	_tmp0_ = self->priv->_state;
#line 107 "../src/contacts-contact-list.vala"
	result = _tmp0_;
#line 107 "../src/contacts-contact-list.vala"
	return result;
#line 1803 "contacts-contact-list.c"
}

void
contacts_contact_list_set_state (ContactsContactList* self,
                                 ContactsUiState value)
{
#line 107 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 107 "../src/contacts-contact-list.vala"
	if (contacts_contact_list_get_state (self) != value) {
#line 107 "../src/contacts-contact-list.vala"
		self->priv->_state = value;
#line 107 "../src/contacts-contact-list.vala"
		g_object_notify_by_pspec ((GObject *) self, contacts_contact_list_properties[CONTACTS_CONTACT_LIST_STATE_PROPERTY]);
#line 1818 "contacts-contact-list.c"
	}
}

static inline gpointer
contacts_contact_list_contact_data_row_get_instance_private (ContactsContactListContactDataRow* self)
{
	return G_STRUCT_MEMBER_P (self, ContactsContactListContactDataRow_private_offset);
}

static void
_contacts_contact_list_contact_data_row_on_contact_changed_g_object_notify (GObject* _sender,
                                                                            GParamSpec* pspec,
                                                                            gpointer self)
{
#line 40 "../src/contacts-contact-list.vala"
	contacts_contact_list_contact_data_row_on_contact_changed ((ContactsContactListContactDataRow*) self, _sender, pspec);
#line 1835 "contacts-contact-list.c"
}

static ContactsContactListContactDataRow*
contacts_contact_list_contact_data_row_construct (GType object_type,
                                                  FolksIndividual* i)
{
	ContactsContactListContactDataRow * self = NULL;
	FolksIndividual* _tmp0_;
	FolksIndividual* _tmp1_;
	GtkStyleContext* _tmp2_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp3_;
	FolksIndividual* _tmp4_;
	ContactsAvatar* _tmp5_;
	FolksIndividual* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	GtkLabel* _tmp9_;
	GtkLabel* _tmp10_;
	GtkLabel* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	GtkCheckButton* _tmp14_;
	GtkCheckButton* _tmp15_;
	GtkCheckButton* _tmp16_;
	GtkCheckButton* _tmp17_;
	GtkCheckButton* _tmp18_;
	GtkCheckButton* _tmp19_;
	ContactsAvatar* _tmp20_;
	GtkLabel* _tmp21_;
	GtkCheckButton* _tmp22_;
#line 38 "../src/contacts-contact-list.vala"
	g_return_val_if_fail (i != NULL, NULL);
#line 38 "../src/contacts-contact-list.vala"
	self = (ContactsContactListContactDataRow*) g_object_new (object_type, NULL);
#line 39 "../src/contacts-contact-list.vala"
	_tmp0_ = _g_object_ref0 (i);
#line 39 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->individual);
#line 39 "../src/contacts-contact-list.vala"
	self->individual = _tmp0_;
#line 40 "../src/contacts-contact-list.vala"
	_tmp1_ = self->individual;
#line 40 "../src/contacts-contact-list.vala"
	g_signal_connect_object ((GObject*) _tmp1_, "notify", (GCallback) _contacts_contact_list_contact_data_row_on_contact_changed_g_object_notify, self, 0);
#line 42 "../src/contacts-contact-list.vala"
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 42 "../src/contacts-contact-list.vala"
	gtk_style_context_add_class (_tmp2_, "contact-data-row");
#line 44 "../src/contacts-contact-list.vala"
	_tmp3_ = (GtkGrid*) gtk_grid_new ();
#line 44 "../src/contacts-contact-list.vala"
	g_object_ref_sink (_tmp3_);
#line 44 "../src/contacts-contact-list.vala"
	grid = _tmp3_;
#line 45 "../src/contacts-contact-list.vala"
	g_object_set ((GtkWidget*) grid, "margin", 3, NULL);
#line 46 "../src/contacts-contact-list.vala"
	gtk_widget_set_margin_start ((GtkWidget*) grid, 9);
#line 47 "../src/contacts-contact-list.vala"
	gtk_grid_set_column_spacing (grid, (guint) 10);
#line 48 "../src/contacts-contact-list.vala"
	_tmp4_ = self->individual;
#line 48 "../src/contacts-contact-list.vala"
	_tmp5_ = contacts_avatar_new (CONTACTS_CONTACT_LIST_CONTACT_DATA_ROW_LIST_AVATAR_SIZE, _tmp4_);
#line 48 "../src/contacts-contact-list.vala"
	g_object_ref_sink (_tmp5_);
#line 48 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->avatar);
#line 48 "../src/contacts-contact-list.vala"
	self->priv->avatar = _tmp5_;
#line 50 "../src/contacts-contact-list.vala"
	_tmp6_ = self->individual;
#line 50 "../src/contacts-contact-list.vala"
	_tmp7_ = folks_individual_get_display_name (_tmp6_);
#line 50 "../src/contacts-contact-list.vala"
	_tmp8_ = _tmp7_;
#line 50 "../src/contacts-contact-list.vala"
	_tmp9_ = (GtkLabel*) gtk_label_new (_tmp8_);
#line 50 "../src/contacts-contact-list.vala"
	g_object_ref_sink (_tmp9_);
#line 50 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->label);
#line 50 "../src/contacts-contact-list.vala"
	self->priv->label = _tmp9_;
#line 51 "../src/contacts-contact-list.vala"
	_tmp10_ = self->priv->label;
#line 51 "../src/contacts-contact-list.vala"
	gtk_label_set_ellipsize (_tmp10_, PANGO_ELLIPSIZE_END);
#line 52 "../src/contacts-contact-list.vala"
	_tmp11_ = self->priv->label;
#line 52 "../src/contacts-contact-list.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp11_, GTK_ALIGN_CENTER);
#line 53 "../src/contacts-contact-list.vala"
	_tmp12_ = self->priv->label;
#line 53 "../src/contacts-contact-list.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp12_, GTK_ALIGN_START);
#line 55 "../src/contacts-contact-list.vala"
	_tmp13_ = self->priv->label;
#line 55 "../src/contacts-contact-list.vala"
	gtk_label_set_xalign (_tmp13_, (gfloat) 0);
#line 57 "../src/contacts-contact-list.vala"
	_tmp14_ = (GtkCheckButton*) gtk_check_button_new ();
#line 57 "../src/contacts-contact-list.vala"
	g_object_ref_sink (_tmp14_);
#line 57 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->selector_button);
#line 57 "../src/contacts-contact-list.vala"
	self->selector_button = _tmp14_;
#line 58 "../src/contacts-contact-list.vala"
	_tmp15_ = self->selector_button;
#line 58 "../src/contacts-contact-list.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp15_, FALSE);
#line 59 "../src/contacts-contact-list.vala"
	_tmp16_ = self->selector_button;
#line 59 "../src/contacts-contact-list.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp16_, GTK_ALIGN_CENTER);
#line 60 "../src/contacts-contact-list.vala"
	_tmp17_ = self->selector_button;
#line 60 "../src/contacts-contact-list.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp17_, GTK_ALIGN_END);
#line 61 "../src/contacts-contact-list.vala"
	_tmp18_ = self->selector_button;
#line 61 "../src/contacts-contact-list.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp18_, TRUE);
#line 63 "../src/contacts-contact-list.vala"
	_tmp19_ = self->selector_button;
#line 63 "../src/contacts-contact-list.vala"
	gtk_widget_set_margin_end ((GtkWidget*) _tmp19_, 12);
#line 65 "../src/contacts-contact-list.vala"
	_tmp20_ = self->priv->avatar;
#line 65 "../src/contacts-contact-list.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp20_, 0, 0, 1, 1);
#line 66 "../src/contacts-contact-list.vala"
	_tmp21_ = self->priv->label;
#line 66 "../src/contacts-contact-list.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp21_, 1, 0, 1, 1);
#line 67 "../src/contacts-contact-list.vala"
	_tmp22_ = self->selector_button;
#line 67 "../src/contacts-contact-list.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp22_, 2, 0, 1, 1);
#line 68 "../src/contacts-contact-list.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) grid);
#line 69 "../src/contacts-contact-list.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 38 "../src/contacts-contact-list.vala"
	_g_object_unref0 (grid);
#line 38 "../src/contacts-contact-list.vala"
	return self;
#line 1985 "contacts-contact-list.c"
}

static ContactsContactListContactDataRow*
contacts_contact_list_contact_data_row_new (FolksIndividual* i)
{
#line 38 "../src/contacts-contact-list.vala"
	return contacts_contact_list_contact_data_row_construct (CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, i);
#line 1993 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_data_row_on_contact_changed (ContactsContactListContactDataRow* self,
                                                           GObject* obj,
                                                           GParamSpec* pspec)
{
	GtkLabel* _tmp0_;
	FolksIndividual* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
#line 72 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 72 "../src/contacts-contact-list.vala"
	g_return_if_fail (obj != NULL);
#line 72 "../src/contacts-contact-list.vala"
	g_return_if_fail (pspec != NULL);
#line 73 "../src/contacts-contact-list.vala"
	_tmp0_ = self->priv->label;
#line 73 "../src/contacts-contact-list.vala"
	_tmp1_ = self->individual;
#line 73 "../src/contacts-contact-list.vala"
	_tmp2_ = folks_individual_get_display_name (_tmp1_);
#line 73 "../src/contacts-contact-list.vala"
	_tmp3_ = _tmp2_;
#line 73 "../src/contacts-contact-list.vala"
	gtk_label_set_text (_tmp0_, _tmp3_);
#line 74 "../src/contacts-contact-list.vala"
	gtk_list_box_row_changed ((GtkListBoxRow*) self);
#line 2023 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_data_row_expose_checkbox (ContactsContactListContactDataRow* self,
                                                        gboolean expose)
{
	gboolean hovering = FALSE;
	gboolean _tmp0_ = FALSE;
	GtkCheckButton* _tmp1_;
#line 78 "../src/contacts-contact-list.vala"
	g_return_if_fail (self != NULL);
#line 79 "../src/contacts-contact-list.vala"
	self->priv->checkbox_exposed = expose;
#line 81 "../src/contacts-contact-list.vala"
	hovering = (gtk_widget_get_state_flags ((GtkWidget*) self) & GTK_STATE_FLAG_PRELIGHT) == GTK_STATE_FLAG_PRELIGHT;
#line 82 "../src/contacts-contact-list.vala"
	if (expose) {
#line 82 "../src/contacts-contact-list.vala"
		_tmp0_ = TRUE;
#line 2043 "contacts-contact-list.c"
	} else {
#line 82 "../src/contacts-contact-list.vala"
		_tmp0_ = hovering;
#line 2047 "contacts-contact-list.c"
	}
#line 82 "../src/contacts-contact-list.vala"
	_tmp1_ = self->selector_button;
#line 82 "../src/contacts-contact-list.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp1_, _tmp0_);
#line 2053 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_data_row_real_state_flags_changed (GtkWidget* base,
                                                                 GtkStateFlags previous_state)
{
	ContactsContactListContactDataRow * self;
	gboolean hovering_now = FALSE;
	gboolean was_hovering = FALSE;
#line 87 "../src/contacts-contact-list.vala"
	self = (ContactsContactListContactDataRow*) base;
#line 88 "../src/contacts-contact-list.vala"
	hovering_now = (gtk_widget_get_state_flags ((GtkWidget*) self) & GTK_STATE_FLAG_PRELIGHT) == GTK_STATE_FLAG_PRELIGHT;
#line 89 "../src/contacts-contact-list.vala"
	was_hovering = (previous_state & GTK_STATE_FLAG_PRELIGHT) == GTK_STATE_FLAG_PRELIGHT;
#line 91 "../src/contacts-contact-list.vala"
	if (hovering_now != was_hovering) {
#line 2071 "contacts-contact-list.c"
		gboolean _tmp0_ = FALSE;
		GtkCheckButton* _tmp1_;
#line 92 "../src/contacts-contact-list.vala"
		if (self->priv->checkbox_exposed) {
#line 92 "../src/contacts-contact-list.vala"
			_tmp0_ = TRUE;
#line 2078 "contacts-contact-list.c"
		} else {
#line 92 "../src/contacts-contact-list.vala"
			_tmp0_ = hovering_now;
#line 2082 "contacts-contact-list.c"
		}
#line 92 "../src/contacts-contact-list.vala"
		_tmp1_ = self->selector_button;
#line 92 "../src/contacts-contact-list.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp1_, _tmp0_);
#line 2088 "contacts-contact-list.c"
	}
}

static void
contacts_contact_list_contact_data_row_class_init (ContactsContactListContactDataRowClass * klass,
                                                   gpointer klass_data)
{
#line 28 "../src/contacts-contact-list.vala"
	contacts_contact_list_contact_data_row_parent_class = g_type_class_peek_parent (klass);
#line 28 "../src/contacts-contact-list.vala"
	g_type_class_adjust_private_offset (klass, &ContactsContactListContactDataRow_private_offset);
#line 28 "../src/contacts-contact-list.vala"
	((GtkWidgetClass *) klass)->state_flags_changed = (void (*) (GtkWidget*, GtkStateFlags)) contacts_contact_list_contact_data_row_real_state_flags_changed;
#line 28 "../src/contacts-contact-list.vala"
	G_OBJECT_CLASS (klass)->finalize = contacts_contact_list_contact_data_row_finalize;
#line 2104 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_data_row_instance_init (ContactsContactListContactDataRow * self,
                                                      gpointer klass)
{
#line 28 "../src/contacts-contact-list.vala"
	self->priv = contacts_contact_list_contact_data_row_get_instance_private (self);
#line 36 "../src/contacts-contact-list.vala"
	self->priv->checkbox_exposed = FALSE;
#line 2115 "contacts-contact-list.c"
}

static void
contacts_contact_list_contact_data_row_finalize (GObject * obj)
{
	ContactsContactListContactDataRow * self;
#line 28 "../src/contacts-contact-list.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_CONTACT_LIST_TYPE_CONTACT_DATA_ROW, ContactsContactListContactDataRow);
#line 31 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->individual);
#line 32 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->label);
#line 33 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->avatar);
#line 34 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->selector_button);
#line 28 "../src/contacts-contact-list.vala"
	G_OBJECT_CLASS (contacts_contact_list_contact_data_row_parent_class)->finalize (obj);
#line 2134 "contacts-contact-list.c"
}

static GType
contacts_contact_list_contact_data_row_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsContactListContactDataRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_contact_list_contact_data_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsContactListContactDataRow), 0, (GInstanceInitFunc) contacts_contact_list_contact_data_row_instance_init, NULL };
	GType contacts_contact_list_contact_data_row_type_id;
	contacts_contact_list_contact_data_row_type_id = g_type_register_static (gtk_list_box_row_get_type (), "ContactsContactListContactDataRow", &g_define_type_info, 0);
	ContactsContactListContactDataRow_private_offset = g_type_add_instance_private (contacts_contact_list_contact_data_row_type_id, sizeof (ContactsContactListContactDataRowPrivate));
	return contacts_contact_list_contact_data_row_type_id;
}

static GType
contacts_contact_list_contact_data_row_get_type (void)
{
	static volatile gsize contacts_contact_list_contact_data_row_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_contact_list_contact_data_row_type_id__volatile)) {
		GType contacts_contact_list_contact_data_row_type_id;
		contacts_contact_list_contact_data_row_type_id = contacts_contact_list_contact_data_row_get_type_once ();
		g_once_init_leave (&contacts_contact_list_contact_data_row_type_id__volatile, contacts_contact_list_contact_data_row_type_id);
	}
	return contacts_contact_list_contact_data_row_type_id__volatile;
}

static void
contacts_contact_list_class_init (ContactsContactListClass * klass,
                                  gpointer klass_data)
{
#line 27 "../src/contacts-contact-list.vala"
	contacts_contact_list_parent_class = g_type_class_peek_parent (klass);
#line 27 "../src/contacts-contact-list.vala"
	g_type_class_adjust_private_offset (klass, &ContactsContactList_private_offset);
#line 27 "../src/contacts-contact-list.vala"
	((GtkListBoxClass *) klass)->row_selected = (void (*) (GtkListBox*, GtkListBoxRow*)) contacts_contact_list_real_row_selected;
#line 27 "../src/contacts-contact-list.vala"
	((GtkWidgetClass *) klass)->button_press_event = (gboolean (*) (GtkWidget*, GdkEventButton*)) contacts_contact_list_real_button_press_event;
#line 27 "../src/contacts-contact-list.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_contacts_contact_list_get_property;
#line 27 "../src/contacts-contact-list.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_contacts_contact_list_set_property;
#line 27 "../src/contacts-contact-list.vala"
	G_OBJECT_CLASS (klass)->finalize = contacts_contact_list_finalize;
#line 27 "../src/contacts-contact-list.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CONTACTS_CONTACT_LIST_STATE_PROPERTY, contacts_contact_list_properties[CONTACTS_CONTACT_LIST_STATE_PROPERTY] = g_param_spec_enum ("state", "state", "state", CONTACTS_TYPE_UI_STATE, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 27 "../src/contacts-contact-list.vala"
	contacts_contact_list_signals[CONTACTS_CONTACT_LIST_SELECTION_CHANGED_SIGNAL] = g_signal_new ("selection-changed", CONTACTS_TYPE_CONTACT_LIST, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, FOLKS_TYPE_INDIVIDUAL);
#line 27 "../src/contacts-contact-list.vala"
	contacts_contact_list_signals[CONTACTS_CONTACT_LIST_CONTACTS_MARKED_SIGNAL] = g_signal_new ("contacts-marked", CONTACTS_TYPE_CONTACT_LIST, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
#line 2183 "contacts-contact-list.c"
}

static void
contacts_contact_list_instance_init (ContactsContactList * self,
                                     gpointer klass)
{
#line 27 "../src/contacts-contact-list.vala"
	self->priv = contacts_contact_list_get_instance_private (self);
#line 99 "../src/contacts-contact-list.vala"
	self->priv->nr_contacts_marked = 0;
#line 105 "../src/contacts-contact-list.vala"
	self->priv->sort_on_surname = FALSE;
#line 2196 "contacts-contact-list.c"
}

static void
contacts_contact_list_finalize (GObject * obj)
{
	ContactsContactList * self;
#line 27 "../src/contacts-contact-list.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_CONTACT_LIST, ContactsContactList);
#line 101 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->filter_query);
#line 103 "../src/contacts-contact-list.vala"
	_g_object_unref0 (self->priv->store);
#line 27 "../src/contacts-contact-list.vala"
	G_OBJECT_CLASS (contacts_contact_list_parent_class)->finalize (obj);
#line 2211 "contacts-contact-list.c"
}

/**
 * The ContactList is the actual list of {@link Contact}s that the user sees on
 * the left. It is contained by the {@link ListPane}, which also provides other
 * functionality, such as an action bar.
 */
static GType
contacts_contact_list_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsContactListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_contact_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsContactList), 0, (GInstanceInitFunc) contacts_contact_list_instance_init, NULL };
	GType contacts_contact_list_type_id;
	contacts_contact_list_type_id = g_type_register_static (gtk_list_box_get_type (), "ContactsContactList", &g_define_type_info, 0);
	ContactsContactList_private_offset = g_type_add_instance_private (contacts_contact_list_type_id, sizeof (ContactsContactListPrivate));
	return contacts_contact_list_type_id;
}

GType
contacts_contact_list_get_type (void)
{
	static volatile gsize contacts_contact_list_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_contact_list_type_id__volatile)) {
		GType contacts_contact_list_type_id;
		contacts_contact_list_type_id = contacts_contact_list_get_type_once ();
		g_once_init_leave (&contacts_contact_list_type_id__volatile, contacts_contact_list_type_id);
	}
	return contacts_contact_list_type_id__volatile;
}

static void
_vala_contacts_contact_list_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec)
{
	ContactsContactList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CONTACTS_TYPE_CONTACT_LIST, ContactsContactList);
#line 27 "../src/contacts-contact-list.vala"
	switch (property_id) {
#line 27 "../src/contacts-contact-list.vala"
		case CONTACTS_CONTACT_LIST_STATE_PROPERTY:
#line 27 "../src/contacts-contact-list.vala"
		g_value_set_enum (value, contacts_contact_list_get_state (self));
#line 27 "../src/contacts-contact-list.vala"
		break;
#line 2257 "contacts-contact-list.c"
		default:
#line 27 "../src/contacts-contact-list.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 27 "../src/contacts-contact-list.vala"
		break;
#line 2263 "contacts-contact-list.c"
	}
}

static void
_vala_contacts_contact_list_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec)
{
	ContactsContactList * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CONTACTS_TYPE_CONTACT_LIST, ContactsContactList);
#line 27 "../src/contacts-contact-list.vala"
	switch (property_id) {
#line 27 "../src/contacts-contact-list.vala"
		case CONTACTS_CONTACT_LIST_STATE_PROPERTY:
#line 27 "../src/contacts-contact-list.vala"
		contacts_contact_list_set_state (self, g_value_get_enum (value));
#line 27 "../src/contacts-contact-list.vala"
		break;
#line 2283 "contacts-contact-list.c"
		default:
#line 27 "../src/contacts-contact-list.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 27 "../src/contacts-contact-list.vala"
		break;
#line 2289 "contacts-contact-list.c"
	}
}

