/* contacts-crop-cheese-dialog.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-crop-cheese-dialog.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 2; tab-width: 8 -*- */
/*
 * Copyright (C) 2018 Elias Entrup <elias-git@flump.de>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <cc-crop-area.h>
#include <cheese-flash.h>
#include <cheese-widget.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <cheese/cheese-camera.h>
#include "contacts.h"
#include <glib/gi18n-lib.h>

#define CONTACTS_TYPE_CROP_CHEESE_DIALOG (contacts_crop_cheese_dialog_get_type ())
#define CONTACTS_CROP_CHEESE_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_CROP_CHEESE_DIALOG, ContactsCropCheeseDialog))
#define CONTACTS_CROP_CHEESE_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_CROP_CHEESE_DIALOG, ContactsCropCheeseDialogClass))
#define CONTACTS_IS_CROP_CHEESE_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_CROP_CHEESE_DIALOG))
#define CONTACTS_IS_CROP_CHEESE_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_CROP_CHEESE_DIALOG))
#define CONTACTS_CROP_CHEESE_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_CROP_CHEESE_DIALOG, ContactsCropCheeseDialogClass))

typedef struct _ContactsCropCheeseDialog ContactsCropCheeseDialog;
typedef struct _ContactsCropCheeseDialogClass ContactsCropCheeseDialogClass;
typedef struct _ContactsCropCheeseDialogPrivate ContactsCropCheeseDialogPrivate;
enum  {
	CONTACTS_CROP_CHEESE_DIALOG_0_PROPERTY,
	CONTACTS_CROP_CHEESE_DIALOG_NUM_PROPERTIES
};
static GParamSpec* contacts_crop_cheese_dialog_properties[CONTACTS_CROP_CHEESE_DIALOG_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
enum  {
	CONTACTS_CROP_CHEESE_DIALOG_PICTURE_SELECTED_SIGNAL,
	CONTACTS_CROP_CHEESE_DIALOG_NUM_SIGNALS
};
static guint contacts_crop_cheese_dialog_signals[CONTACTS_CROP_CHEESE_DIALOG_NUM_SIGNALS] = {0};

struct _ContactsCropCheeseDialog {
	GtkWindow parent_instance;
	ContactsCropCheeseDialogPrivate * priv;
};

struct _ContactsCropCheeseDialogClass {
	GtkWindowClass parent_class;
};

struct _ContactsCropCheeseDialogPrivate {
	GtkStack* stack;
	GtkButton* take_another_button;
	CcCropArea* crop_area;
	CheeseFlash* flash;
	CheeseWidget* cheese;
};

static gint ContactsCropCheeseDialog_private_offset;
static gpointer contacts_crop_cheese_dialog_parent_class = NULL;

GType contacts_crop_cheese_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsCropCheeseDialog, g_object_unref)
#define CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CROP "crop"
#define CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CHEESE "cheese"
ContactsCropCheeseDialog* contacts_crop_cheese_dialog_new_for_cheese (GtkWindow* parent);
ContactsCropCheeseDialog* contacts_crop_cheese_dialog_construct_for_cheese (GType object_type,
                                                                            GtkWindow* parent);
static void contacts_crop_cheese_dialog_setup_widget (ContactsCropCheeseDialog* self,
                                               GtkWindow* parent);
ContactsCropCheeseDialog* contacts_crop_cheese_dialog_new_for_crop (GtkWindow* parent,
                                                                    GdkPixbuf* pixbuf);
ContactsCropCheeseDialog* contacts_crop_cheese_dialog_construct_for_crop (GType object_type,
                                                                          GtkWindow* parent,
                                                                          GdkPixbuf* pixbuf);
static void contacts_crop_cheese_dialog_on_cancel_clicked (ContactsCropCheeseDialog* self,
                                                    GtkButton* button);
static void _contacts_crop_cheese_dialog_on_cancel_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                        gpointer self);
static void contacts_crop_cheese_dialog_on_take_another_clicked (ContactsCropCheeseDialog* self,
                                                          GtkButton* button);
static void _contacts_crop_cheese_dialog_on_take_another_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                              gpointer self);
static void contacts_crop_cheese_dialog_on_take_pic_clicked (ContactsCropCheeseDialog* self,
                                                      GtkButton* button);
static void __lambda18_ (ContactsCropCheeseDialog* self,
                  GdkPixbuf* pix);
static void ___lambda18__cheese_camera_photo_taken (CheeseCamera* _sender,
                                             GdkPixbuf* pixbuf,
                                             gpointer self);
static void _contacts_crop_cheese_dialog_on_take_pic_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                          gpointer self);
static void contacts_crop_cheese_dialog_on_done_clicked (ContactsCropCheeseDialog* self,
                                                  GtkButton* button);
static void _contacts_crop_cheese_dialog_on_done_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                      gpointer self);
static void contacts_crop_cheese_dialog_on_destroy (ContactsCropCheeseDialog* self);
static void _contacts_crop_cheese_dialog_on_destroy_gtk_widget_destroy (GtkWidget* _sender,
                                                                 gpointer self);
ContactsCropCheeseDialog* contacts_crop_cheese_dialog_new (void);
ContactsCropCheeseDialog* contacts_crop_cheese_dialog_construct (GType object_type);
static void contacts_crop_cheese_dialog_finalize (GObject * obj);
static GType contacts_crop_cheese_dialog_get_type_once (void);

static inline gpointer
contacts_crop_cheese_dialog_get_instance_private (ContactsCropCheeseDialog* self)
{
	return G_STRUCT_MEMBER_P (self, ContactsCropCheeseDialog_private_offset);
}

ContactsCropCheeseDialog*
contacts_crop_cheese_dialog_construct_for_cheese (GType object_type,
                                                  GtkWindow* parent)
{
	ContactsCropCheeseDialog * self = NULL;
	CheeseFlash* _tmp0_;
	CheeseWidget* _tmp1_;
	CheeseWidget* _tmp2_;
	GtkStack* _tmp3_;
	CheeseWidget* _tmp4_;
	GtkStack* _tmp5_;
#line 39 "../src/contacts-crop-cheese-dialog.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 39 "../src/contacts-crop-cheese-dialog.vala"
	self = (ContactsCropCheeseDialog*) g_object_new (object_type, NULL);
#line 41 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_setup_widget (self, parent);
#line 42 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = (CheeseFlash*) cheese_flash_new ((GtkWidget*) self);
#line 42 "../src/contacts-crop-cheese-dialog.vala"
	g_object_ref_sink (_tmp0_);
#line 42 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->flash);
#line 42 "../src/contacts-crop-cheese-dialog.vala"
	self->priv->flash = _tmp0_;
#line 43 "../src/contacts-crop-cheese-dialog.vala"
	_tmp1_ = (CheeseWidget*) cheese_widget_new ();
#line 43 "../src/contacts-crop-cheese-dialog.vala"
	g_object_ref_sink (_tmp1_);
#line 43 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->cheese);
#line 43 "../src/contacts-crop-cheese-dialog.vala"
	self->priv->cheese = _tmp1_;
#line 44 "../src/contacts-crop-cheese-dialog.vala"
	_tmp2_ = self->priv->cheese;
#line 44 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_show ((GtkWidget*) _tmp2_);
#line 45 "../src/contacts-crop-cheese-dialog.vala"
	_tmp3_ = self->priv->stack;
#line 45 "../src/contacts-crop-cheese-dialog.vala"
	_tmp4_ = self->priv->cheese;
#line 45 "../src/contacts-crop-cheese-dialog.vala"
	gtk_stack_add_named (_tmp3_, (GtkWidget*) _tmp4_, CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CHEESE);
#line 46 "../src/contacts-crop-cheese-dialog.vala"
	_tmp5_ = self->priv->stack;
#line 46 "../src/contacts-crop-cheese-dialog.vala"
	gtk_stack_set_visible_child_name (_tmp5_, CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CHEESE);
#line 39 "../src/contacts-crop-cheese-dialog.vala"
	return self;
#line 176 "contacts-crop-cheese-dialog.c"
}

ContactsCropCheeseDialog*
contacts_crop_cheese_dialog_new_for_cheese (GtkWindow* parent)
{
#line 39 "../src/contacts-crop-cheese-dialog.vala"
	return contacts_crop_cheese_dialog_construct_for_cheese (CONTACTS_TYPE_CROP_CHEESE_DIALOG, parent);
#line 184 "contacts-crop-cheese-dialog.c"
}

ContactsCropCheeseDialog*
contacts_crop_cheese_dialog_construct_for_crop (GType object_type,
                                                GtkWindow* parent,
                                                GdkPixbuf* pixbuf)
{
	ContactsCropCheeseDialog * self = NULL;
	GtkButton* _tmp0_;
	CcCropArea* _tmp1_;
#line 50 "../src/contacts-crop-cheese-dialog.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 50 "../src/contacts-crop-cheese-dialog.vala"
	g_return_val_if_fail (pixbuf != NULL, NULL);
#line 50 "../src/contacts-crop-cheese-dialog.vala"
	self = (ContactsCropCheeseDialog*) g_object_new (object_type, NULL);
#line 51 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_setup_widget (self, parent);
#line 52 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = self->priv->take_another_button;
#line 52 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp0_, FALSE);
#line 53 "../src/contacts-crop-cheese-dialog.vala"
	_tmp1_ = self->priv->crop_area;
#line 53 "../src/contacts-crop-cheese-dialog.vala"
	cc_crop_area_set_picture (_tmp1_, pixbuf);
#line 50 "../src/contacts-crop-cheese-dialog.vala"
	return self;
#line 213 "contacts-crop-cheese-dialog.c"
}

ContactsCropCheeseDialog*
contacts_crop_cheese_dialog_new_for_crop (GtkWindow* parent,
                                          GdkPixbuf* pixbuf)
{
#line 50 "../src/contacts-crop-cheese-dialog.vala"
	return contacts_crop_cheese_dialog_construct_for_crop (CONTACTS_TYPE_CROP_CHEESE_DIALOG, parent, pixbuf);
#line 222 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_setup_widget (ContactsCropCheeseDialog* self,
                                          GtkWindow* parent)
{
	CcCropArea* _tmp0_;
	CcCropArea* _tmp1_;
	CcCropArea* _tmp2_;
	CcCropArea* _tmp3_;
	CcCropArea* _tmp4_;
	GtkStack* _tmp5_;
	CcCropArea* _tmp6_;
#line 57 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (self != NULL);
#line 57 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (parent != NULL);
#line 58 "../src/contacts-crop-cheese-dialog.vala"
	gtk_window_set_transient_for ((GtkWindow*) self, parent);
#line 60 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = (CcCropArea*) cc_crop_area_new ();
#line 60 "../src/contacts-crop-cheese-dialog.vala"
	g_object_ref_sink (_tmp0_);
#line 60 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->crop_area);
#line 60 "../src/contacts-crop-cheese-dialog.vala"
	self->priv->crop_area = _tmp0_;
#line 61 "../src/contacts-crop-cheese-dialog.vala"
	_tmp1_ = self->priv->crop_area;
#line 61 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp1_, TRUE);
#line 62 "../src/contacts-crop-cheese-dialog.vala"
	_tmp2_ = self->priv->crop_area;
#line 62 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp2_, TRUE);
#line 63 "../src/contacts-crop-cheese-dialog.vala"
	_tmp3_ = self->priv->crop_area;
#line 63 "../src/contacts-crop-cheese-dialog.vala"
	cc_crop_area_set_min_size (_tmp3_, 48, 48);
#line 64 "../src/contacts-crop-cheese-dialog.vala"
	_tmp4_ = self->priv->crop_area;
#line 64 "../src/contacts-crop-cheese-dialog.vala"
	cc_crop_area_set_constrain_aspect (_tmp4_, TRUE);
#line 65 "../src/contacts-crop-cheese-dialog.vala"
	_tmp5_ = self->priv->stack;
#line 65 "../src/contacts-crop-cheese-dialog.vala"
	_tmp6_ = self->priv->crop_area;
#line 65 "../src/contacts-crop-cheese-dialog.vala"
	gtk_stack_add_named (_tmp5_, (GtkWidget*) _tmp6_, CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CROP);
#line 272 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_on_cancel_clicked (ContactsCropCheeseDialog* self,
                                               GtkButton* button)
{
#line 69 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (self != NULL);
#line 69 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (button != NULL);
#line 70 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 285 "contacts-crop-cheese-dialog.c"
}

static void
_contacts_crop_cheese_dialog_on_cancel_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                   gpointer self)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_on_cancel_clicked ((ContactsCropCheeseDialog*) self, _sender);
#line 294 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_on_take_another_clicked (ContactsCropCheeseDialog* self,
                                                     GtkButton* button)
{
	GtkStack* _tmp0_;
#line 74 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (self != NULL);
#line 74 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (button != NULL);
#line 76 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = self->priv->stack;
#line 76 "../src/contacts-crop-cheese-dialog.vala"
	gtk_stack_set_visible_child_name (_tmp0_, CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CHEESE);
#line 310 "contacts-crop-cheese-dialog.c"
}

static void
_contacts_crop_cheese_dialog_on_take_another_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                         gpointer self)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_on_take_another_clicked ((ContactsCropCheeseDialog*) self, _sender);
#line 319 "contacts-crop-cheese-dialog.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 83 "../src/contacts-crop-cheese-dialog.vala"
	return self ? g_object_ref (self) : NULL;
#line 327 "contacts-crop-cheese-dialog.c"
}

static void
__lambda18_ (ContactsCropCheeseDialog* self,
             GdkPixbuf* pix)
{
	GtkStack* _tmp0_;
	CcCropArea* _tmp1_;
#line 85 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (pix != NULL);
#line 86 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = self->priv->stack;
#line 86 "../src/contacts-crop-cheese-dialog.vala"
	gtk_stack_set_visible_child_name (_tmp0_, CONTACTS_CROP_CHEESE_DIALOG_STACK_NAME_CROP);
#line 87 "../src/contacts-crop-cheese-dialog.vala"
	_tmp1_ = self->priv->crop_area;
#line 87 "../src/contacts-crop-cheese-dialog.vala"
	cc_crop_area_set_picture (_tmp1_, pix);
#line 346 "contacts-crop-cheese-dialog.c"
}

static void
___lambda18__cheese_camera_photo_taken (CheeseCamera* _sender,
                                        GdkPixbuf* pixbuf,
                                        gpointer self)
{
#line 85 "../src/contacts-crop-cheese-dialog.vala"
	__lambda18_ ((ContactsCropCheeseDialog*) self, pixbuf);
#line 356 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_on_take_pic_clicked (ContactsCropCheeseDialog* self,
                                                 GtkButton* button)
{
	CheeseCamera* camera = NULL;
	CheeseWidget* _tmp0_;
	GObject* _tmp1_;
	CheeseCamera* _tmp2_;
	CheeseFlash* _tmp3_;
	CheeseCamera* _tmp4_;
	CheeseCamera* _tmp5_;
#line 81 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (self != NULL);
#line 81 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (button != NULL);
#line 83 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = self->priv->cheese;
#line 83 "../src/contacts-crop-cheese-dialog.vala"
	_tmp1_ = cheese_widget_get_camera (_tmp0_);
#line 83 "../src/contacts-crop-cheese-dialog.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, CHEESE_TYPE_CAMERA) ? ((CheeseCamera*) _tmp1_) : NULL);
#line 83 "../src/contacts-crop-cheese-dialog.vala"
	camera = _tmp2_;
#line 84 "../src/contacts-crop-cheese-dialog.vala"
	_tmp3_ = self->priv->flash;
#line 84 "../src/contacts-crop-cheese-dialog.vala"
	cheese_flash_fire (_tmp3_);
#line 85 "../src/contacts-crop-cheese-dialog.vala"
	_tmp4_ = camera;
#line 85 "../src/contacts-crop-cheese-dialog.vala"
	g_signal_connect_object (_tmp4_, "photo-taken", (GCallback) ___lambda18__cheese_camera_photo_taken, self, 0);
#line 90 "../src/contacts-crop-cheese-dialog.vala"
	_tmp5_ = camera;
#line 90 "../src/contacts-crop-cheese-dialog.vala"
	if (!cheese_camera_take_photo_pixbuf (_tmp5_)) {
#line 91 "../src/contacts-crop-cheese-dialog.vala"
		contacts_utils_show_error_dialog (_ ("Unable to take photo."), G_TYPE_CHECK_INSTANCE_TYPE (self, gtk_window_get_type ()) ? ((GtkWindow*) self) : NULL);
#line 396 "contacts-crop-cheese-dialog.c"
	}
#line 81 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (camera);
#line 400 "contacts-crop-cheese-dialog.c"
}

static void
_contacts_crop_cheese_dialog_on_take_pic_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                     gpointer self)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_on_take_pic_clicked ((ContactsCropCheeseDialog*) self, _sender);
#line 409 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_on_done_clicked (ContactsCropCheeseDialog* self,
                                             GtkButton* button)
{
	CcCropArea* _tmp0_;
	GdkPixbuf* _tmp1_;
	GdkPixbuf* _tmp2_;
#line 98 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (self != NULL);
#line 98 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (button != NULL);
#line 99 "../src/contacts-crop-cheese-dialog.vala"
	_tmp0_ = self->priv->crop_area;
#line 99 "../src/contacts-crop-cheese-dialog.vala"
	_tmp1_ = cc_crop_area_get_picture (_tmp0_);
#line 99 "../src/contacts-crop-cheese-dialog.vala"
	_tmp2_ = _tmp1_;
#line 99 "../src/contacts-crop-cheese-dialog.vala"
	g_signal_emit (self, contacts_crop_cheese_dialog_signals[CONTACTS_CROP_CHEESE_DIALOG_PICTURE_SELECTED_SIGNAL], 0, _tmp2_);
#line 99 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (_tmp2_);
#line 100 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 435 "contacts-crop-cheese-dialog.c"
}

static void
_contacts_crop_cheese_dialog_on_done_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                 gpointer self)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_on_done_clicked ((ContactsCropCheeseDialog*) self, _sender);
#line 444 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_on_destroy (ContactsCropCheeseDialog* self)
{
#line 104 "../src/contacts-crop-cheese-dialog.vala"
	g_return_if_fail (self != NULL);
#line 110 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->cheese);
#line 110 "../src/contacts-crop-cheese-dialog.vala"
	self->priv->cheese = NULL;
#line 456 "contacts-crop-cheese-dialog.c"
}

static void
_contacts_crop_cheese_dialog_on_destroy_gtk_widget_destroy (GtkWidget* _sender,
                                                            gpointer self)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_on_destroy ((ContactsCropCheeseDialog*) self);
#line 465 "contacts-crop-cheese-dialog.c"
}

ContactsCropCheeseDialog*
contacts_crop_cheese_dialog_construct (GType object_type)
{
	ContactsCropCheeseDialog * self = NULL;
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	self = (ContactsCropCheeseDialog*) g_object_new (object_type, NULL);
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	return self;
#line 476 "contacts-crop-cheese-dialog.c"
}

ContactsCropCheeseDialog*
contacts_crop_cheese_dialog_new (void)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	return contacts_crop_cheese_dialog_construct (CONTACTS_TYPE_CROP_CHEESE_DIALOG);
#line 484 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_class_init (ContactsCropCheeseDialogClass * klass,
                                        gpointer klass_data)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	g_type_class_adjust_private_offset (klass, &ContactsCropCheeseDialog_private_offset);
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	G_OBJECT_CLASS (klass)->finalize = contacts_crop_cheese_dialog_finalize;
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gnome/Contacts/ui/contacts-crop-cheese-dialog.ui");
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	contacts_crop_cheese_dialog_signals[CONTACTS_CROP_CHEESE_DIALOG_PICTURE_SELECTED_SIGNAL] = g_signal_new ("picture-selected", CONTACTS_TYPE_CROP_CHEESE_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, gdk_pixbuf_get_type ());
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "stack", FALSE, ContactsCropCheeseDialog_private_offset + G_STRUCT_OFFSET (ContactsCropCheeseDialogPrivate, stack));
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "take_another_button", FALSE, ContactsCropCheeseDialog_private_offset + G_STRUCT_OFFSET (ContactsCropCheeseDialogPrivate, take_another_button));
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_cancel_clicked", G_CALLBACK(_contacts_crop_cheese_dialog_on_cancel_clicked_gtk_button_clicked));
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_take_another_clicked", G_CALLBACK(_contacts_crop_cheese_dialog_on_take_another_clicked_gtk_button_clicked));
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_take_pic_clicked", G_CALLBACK(_contacts_crop_cheese_dialog_on_take_pic_clicked_gtk_button_clicked));
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_done_clicked", G_CALLBACK(_contacts_crop_cheese_dialog_on_done_clicked_gtk_button_clicked));
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_destroy", G_CALLBACK(_contacts_crop_cheese_dialog_on_destroy_gtk_widget_destroy));
#line 515 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_instance_init (ContactsCropCheeseDialog * self,
                                           gpointer klass)
{
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	self->priv = contacts_crop_cheese_dialog_get_instance_private (self);
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 526 "contacts-crop-cheese-dialog.c"
}

static void
contacts_crop_cheese_dialog_finalize (GObject * obj)
{
	ContactsCropCheeseDialog * self;
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_CROP_CHEESE_DIALOG, ContactsCropCheeseDialog);
#line 24 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->stack);
#line 26 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->take_another_button);
#line 28 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->crop_area);
#line 33 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->flash);
#line 34 "../src/contacts-crop-cheese-dialog.vala"
	_g_object_unref0 (self->priv->cheese);
#line 22 "../src/contacts-crop-cheese-dialog.vala"
	G_OBJECT_CLASS (contacts_crop_cheese_dialog_parent_class)->finalize (obj);
#line 547 "contacts-crop-cheese-dialog.c"
}

static GType
contacts_crop_cheese_dialog_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsCropCheeseDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_crop_cheese_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsCropCheeseDialog), 0, (GInstanceInitFunc) contacts_crop_cheese_dialog_instance_init, NULL };
	GType contacts_crop_cheese_dialog_type_id;
	contacts_crop_cheese_dialog_type_id = g_type_register_static (gtk_window_get_type (), "ContactsCropCheeseDialog", &g_define_type_info, 0);
	ContactsCropCheeseDialog_private_offset = g_type_add_instance_private (contacts_crop_cheese_dialog_type_id, sizeof (ContactsCropCheeseDialogPrivate));
	return contacts_crop_cheese_dialog_type_id;
}

GType
contacts_crop_cheese_dialog_get_type (void)
{
	static volatile gsize contacts_crop_cheese_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_crop_cheese_dialog_type_id__volatile)) {
		GType contacts_crop_cheese_dialog_type_id;
		contacts_crop_cheese_dialog_type_id = contacts_crop_cheese_dialog_get_type_once ();
		g_once_init_leave (&contacts_crop_cheese_dialog_type_id__volatile, contacts_crop_cheese_dialog_type_id);
	}
	return contacts_crop_cheese_dialog_type_id__volatile;
}

