/* contacts-avatar.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-avatar.vala, do not modify */

/*
 * Copyright (C) 2011 Alexander Larsson <alexl@redhat.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <folks/folks.h>
#include <cairo.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include "contacts.h"
#include <stdlib.h>
#include <string.h>
#include <gee.h>

#define CONTACTS_TYPE_AVATAR (contacts_avatar_get_type ())
#define CONTACTS_AVATAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_AVATAR, ContactsAvatar))
#define CONTACTS_AVATAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_AVATAR, ContactsAvatarClass))
#define CONTACTS_IS_AVATAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_AVATAR))
#define CONTACTS_IS_AVATAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_AVATAR))
#define CONTACTS_AVATAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_AVATAR, ContactsAvatarClass))

typedef struct _ContactsAvatar ContactsAvatar;
typedef struct _ContactsAvatarClass ContactsAvatarClass;
typedef struct _ContactsAvatarPrivate ContactsAvatarPrivate;
enum  {
	CONTACTS_AVATAR_0_PROPERTY,
	CONTACTS_AVATAR_NUM_PROPERTIES
};
static GParamSpec* contacts_avatar_properties[CONTACTS_AVATAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ContactsAvatarLoadAvatarData ContactsAvatarLoadAvatarData;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _ContactsAvatar {
	GtkDrawingArea parent_instance;
	ContactsAvatarPrivate * priv;
};

struct _ContactsAvatarClass {
	GtkDrawingAreaClass parent_class;
};

struct _ContactsAvatarPrivate {
	gint size;
	GdkPixbuf* pixbuf;
	GdkPixbuf* cache;
	FolksIndividual* individual;
	gboolean avatar_loaded;
};

struct _ContactsAvatarLoadAvatarData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	ContactsAvatar* self;
	FolksIndividual* _tmp0_;
	GInputStream* stream;
	FolksIndividual* _tmp1_;
	GLoadableIcon* _tmp2_;
	GLoadableIcon* _tmp3_;
	GInputStream* _tmp4_;
	GdkPixbuf* _tmp5_;
	GInputStream* _tmp6_;
	GdkPixbuf* _tmp7_;
	GdkPixbuf* _tmp8_;
	GError* e;
	FolksIndividual* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	GError* _tmp12_;
	const gchar* _tmp13_;
	GError* _inner_error0_;
};

static gint ContactsAvatar_private_offset;
static gpointer contacts_avatar_parent_class = NULL;

GType contacts_avatar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsAvatar, g_object_unref)
ContactsAvatar* contacts_avatar_new (gint size,
                                     FolksIndividual* individual);
ContactsAvatar* contacts_avatar_construct (GType object_type,
                                           gint size,
                                           FolksIndividual* individual);
static void ___lambda5_ (ContactsAvatar* self,
                  GObject* s,
                  GParamSpec* p);
static void contacts_avatar_load_avatar (ContactsAvatar* self,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_);
static void contacts_avatar_load_avatar_finish (ContactsAvatar* self,
                                         GAsyncResult* _res_);
static void ____lambda5__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
void contacts_avatar_set_pixbuf (ContactsAvatar* self,
                                 GdkPixbuf* a_pixbuf);
static void contacts_avatar_load_avatar_data_free (gpointer _data);
static gboolean contacts_avatar_load_avatar_co (ContactsAvatarLoadAvatarData* _data_);
static void contacts_avatar_load_avatar_ready (GObject* source_object,
                                        GAsyncResult* _res_,
                                        gpointer _user_data_);
static gboolean contacts_avatar_real_draw (GtkWidget* base,
                                    cairo_t* cr);
static GdkPixbuf* contacts_avatar_create_contact_avatar (ContactsAvatar* self);
static GdkPixbuf* contacts_avatar_create_fallback (ContactsAvatar* self);
static void contacts_avatar_draw_cached_avatar (ContactsAvatar* self,
                                         cairo_t* cr);
static gchar* contacts_avatar_find_display_name (ContactsAvatar* self);
static gchar* contacts_avatar_look_up_alias_for_display_name (ContactsAvatar* self,
                                                       FolksPersona* p);
static gchar* contacts_avatar_look_up_name_details_for_display_name (ContactsAvatar* self,
                                                              FolksPersona* p);
static void contacts_avatar_finalize (GObject * obj);
static GType contacts_avatar_get_type_once (void);

static inline gpointer
contacts_avatar_get_instance_private (ContactsAvatar* self)
{
	return G_STRUCT_MEMBER_P (self, ContactsAvatar_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 37 "../src/contacts-avatar.vala"
	return self ? g_object_ref (self) : NULL;
#line 156 "contacts-avatar.c"
}

static void
___lambda5_ (ContactsAvatar* self,
             GObject* s,
             GParamSpec* p)
{
#line 39 "../src/contacts-avatar.vala"
	g_return_if_fail (s != NULL);
#line 39 "../src/contacts-avatar.vala"
	g_return_if_fail (p != NULL);
#line 40 "../src/contacts-avatar.vala"
	contacts_avatar_load_avatar (self, NULL, NULL);
#line 170 "contacts-avatar.c"
}

static void
____lambda5__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 39 "../src/contacts-avatar.vala"
	___lambda5_ ((ContactsAvatar*) self, _sender, pspec);
#line 180 "contacts-avatar.c"
}

ContactsAvatar*
contacts_avatar_construct (GType object_type,
                           gint size,
                           FolksIndividual* individual)
{
	ContactsAvatar * self = NULL;
	FolksIndividual* _tmp0_;
	gboolean _tmp1_ = FALSE;
#line 36 "../src/contacts-avatar.vala"
	self = (ContactsAvatar*) g_object_new (object_type, NULL);
#line 37 "../src/contacts-avatar.vala"
	_tmp0_ = _g_object_ref0 (individual);
#line 37 "../src/contacts-avatar.vala"
	_g_object_unref0 (self->priv->individual);
#line 37 "../src/contacts-avatar.vala"
	self->priv->individual = _tmp0_;
#line 38 "../src/contacts-avatar.vala"
	if (individual != NULL) {
#line 39 "../src/contacts-avatar.vala"
		g_signal_connect_object ((GObject*) individual, "notify::avatar", (GCallback) ____lambda5__g_object_notify, self, 0);
#line 203 "contacts-avatar.c"
	}
#line 44 "../src/contacts-avatar.vala"
	self->priv->size = size;
#line 45 "../src/contacts-avatar.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, size, size);
#line 48 "../src/contacts-avatar.vala"
	if (individual == NULL) {
#line 48 "../src/contacts-avatar.vala"
		_tmp1_ = TRUE;
#line 213 "contacts-avatar.c"
	} else {
		GLoadableIcon* _tmp2_;
		GLoadableIcon* _tmp3_;
#line 48 "../src/contacts-avatar.vala"
		_tmp2_ = folks_avatar_details_get_avatar ((FolksAvatarDetails*) individual);
#line 48 "../src/contacts-avatar.vala"
		_tmp3_ = _tmp2_;
#line 48 "../src/contacts-avatar.vala"
		_tmp1_ = _tmp3_ == NULL;
#line 223 "contacts-avatar.c"
	}
#line 48 "../src/contacts-avatar.vala"
	self->priv->avatar_loaded = _tmp1_;
#line 50 "../src/contacts-avatar.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 36 "../src/contacts-avatar.vala"
	return self;
#line 231 "contacts-avatar.c"
}

ContactsAvatar*
contacts_avatar_new (gint size,
                     FolksIndividual* individual)
{
#line 36 "../src/contacts-avatar.vala"
	return contacts_avatar_construct (CONTACTS_TYPE_AVATAR, size, individual);
#line 240 "contacts-avatar.c"
}

/**
   * Manually set the avatar to the given pixbuf, even if the contact has an avatar.
   */
void
contacts_avatar_set_pixbuf (ContactsAvatar* self,
                            GdkPixbuf* a_pixbuf)
{
	GdkPixbuf* _tmp0_;
#line 56 "../src/contacts-avatar.vala"
	g_return_if_fail (self != NULL);
#line 57 "../src/contacts-avatar.vala"
	_g_object_unref0 (self->priv->cache);
#line 57 "../src/contacts-avatar.vala"
	self->priv->cache = NULL;
#line 58 "../src/contacts-avatar.vala"
	_tmp0_ = _g_object_ref0 (a_pixbuf);
#line 58 "../src/contacts-avatar.vala"
	_g_object_unref0 (self->priv->pixbuf);
#line 58 "../src/contacts-avatar.vala"
	self->priv->pixbuf = _tmp0_;
#line 59 "../src/contacts-avatar.vala"
	gtk_widget_queue_draw ((GtkWidget*) self);
#line 265 "contacts-avatar.c"
}

static void
contacts_avatar_load_avatar_data_free (gpointer _data)
{
	ContactsAvatarLoadAvatarData* _data_;
	_data_ = _data;
#line 26 "../src/contacts-avatar.vala"
	_g_object_unref0 (_data_->self);
#line 26 "../src/contacts-avatar.vala"
	g_slice_free (ContactsAvatarLoadAvatarData, _data_);
#line 277 "contacts-avatar.c"
}

static void
contacts_avatar_load_avatar (ContactsAvatar* self,
                             GAsyncReadyCallback _callback_,
                             gpointer _user_data_)
{
	ContactsAvatarLoadAvatarData* _data_;
	ContactsAvatar* _tmp0_;
#line 26 "../src/contacts-avatar.vala"
	_data_ = g_slice_new0 (ContactsAvatarLoadAvatarData);
#line 26 "../src/contacts-avatar.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 26 "../src/contacts-avatar.vala"
	g_task_set_task_data (_data_->_async_result, _data_, contacts_avatar_load_avatar_data_free);
#line 26 "../src/contacts-avatar.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 26 "../src/contacts-avatar.vala"
	_data_->self = _tmp0_;
#line 26 "../src/contacts-avatar.vala"
	contacts_avatar_load_avatar_co (_data_);
#line 299 "contacts-avatar.c"
}

static void
contacts_avatar_load_avatar_finish (ContactsAvatar* self,
                                    GAsyncResult* _res_)
{
	ContactsAvatarLoadAvatarData* _data_;
#line 26 "../src/contacts-avatar.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 309 "contacts-avatar.c"
}

static void
contacts_avatar_load_avatar_ready (GObject* source_object,
                                   GAsyncResult* _res_,
                                   gpointer _user_data_)
{
	ContactsAvatarLoadAvatarData* _data_;
#line 67 "../src/contacts-avatar.vala"
	_data_ = _user_data_;
#line 67 "../src/contacts-avatar.vala"
	_data_->_source_object_ = source_object;
#line 67 "../src/contacts-avatar.vala"
	_data_->_res_ = _res_;
#line 67 "../src/contacts-avatar.vala"
	contacts_avatar_load_avatar_co (_data_);
#line 326 "contacts-avatar.c"
}

static gboolean
contacts_avatar_load_avatar_co (ContactsAvatarLoadAvatarData* _data_)
{
#line 62 "../src/contacts-avatar.vala"
	switch (_data_->_state_) {
#line 62 "../src/contacts-avatar.vala"
		case 0:
#line 336 "contacts-avatar.c"
		goto _state_0;
#line 62 "../src/contacts-avatar.vala"
		case 1:
#line 340 "contacts-avatar.c"
		goto _state_1;
#line 62 "../src/contacts-avatar.vala"
		case 2:
#line 344 "contacts-avatar.c"
		goto _state_2;
		default:
#line 62 "../src/contacts-avatar.vala"
		g_assert_not_reached ();
#line 349 "contacts-avatar.c"
	}
	_state_0:
#line 63 "../src/contacts-avatar.vala"
	_data_->_tmp0_ = _data_->self->priv->individual;
#line 63 "../src/contacts-avatar.vala"
	_vala_assert (_data_->_tmp0_ != NULL, "this.individual != null");
#line 65 "../src/contacts-avatar.vala"
	_data_->self->priv->avatar_loaded = TRUE;
#line 358 "contacts-avatar.c"
	{
#line 67 "../src/contacts-avatar.vala"
		_data_->_tmp1_ = _data_->self->priv->individual;
#line 67 "../src/contacts-avatar.vala"
		_data_->_tmp2_ = folks_avatar_details_get_avatar ((FolksAvatarDetails*) _data_->_tmp1_);
#line 67 "../src/contacts-avatar.vala"
		_data_->_tmp3_ = _data_->_tmp2_;
#line 67 "../src/contacts-avatar.vala"
		_data_->_state_ = 1;
#line 67 "../src/contacts-avatar.vala"
		g_loadable_icon_load_async (_data_->_tmp3_, _data_->self->priv->size, NULL, contacts_avatar_load_avatar_ready, _data_);
#line 67 "../src/contacts-avatar.vala"
		return FALSE;
#line 372 "contacts-avatar.c"
		_state_1:
#line 67 "../src/contacts-avatar.vala"
		_data_->_tmp4_ = g_loadable_icon_load_finish (_data_->_tmp3_, _data_->_res_, NULL, &_data_->_inner_error0_);
#line 67 "../src/contacts-avatar.vala"
		_data_->stream = _data_->_tmp4_;
#line 67 "../src/contacts-avatar.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 380 "contacts-avatar.c"
			goto __catch3_g_error;
		}
#line 68 "../src/contacts-avatar.vala"
		_g_object_unref0 (_data_->self->priv->cache);
#line 68 "../src/contacts-avatar.vala"
		_data_->self->priv->cache = NULL;
#line 69 "../src/contacts-avatar.vala"
		_data_->_tmp6_ = _data_->stream;
#line 69 "../src/contacts-avatar.vala"
		_data_->_state_ = 2;
#line 69 "../src/contacts-avatar.vala"
		gdk_pixbuf_new_from_stream_at_scale_async (_data_->_tmp6_, _data_->self->priv->size, _data_->self->priv->size, TRUE, NULL, contacts_avatar_load_avatar_ready, _data_);
#line 69 "../src/contacts-avatar.vala"
		return FALSE;
#line 395 "contacts-avatar.c"
		_state_2:
#line 69 "../src/contacts-avatar.vala"
		_data_->_tmp7_ = (GdkPixbuf*) gdk_pixbuf_new_from_stream_finish (_data_->_res_, &_data_->_inner_error0_);
#line 69 "../src/contacts-avatar.vala"
		_data_->_tmp5_ = _data_->_tmp7_;
#line 69 "../src/contacts-avatar.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 69 "../src/contacts-avatar.vala"
			_g_object_unref0 (_data_->stream);
#line 405 "contacts-avatar.c"
			goto __catch3_g_error;
		}
#line 69 "../src/contacts-avatar.vala"
		_data_->_tmp8_ = _data_->_tmp5_;
#line 69 "../src/contacts-avatar.vala"
		_data_->_tmp5_ = NULL;
#line 69 "../src/contacts-avatar.vala"
		_g_object_unref0 (_data_->self->priv->pixbuf);
#line 69 "../src/contacts-avatar.vala"
		_data_->self->priv->pixbuf = _data_->_tmp8_;
#line 70 "../src/contacts-avatar.vala"
		gtk_widget_queue_draw ((GtkWidget*) _data_->self);
#line 66 "../src/contacts-avatar.vala"
		_g_object_unref0 (_data_->_tmp5_);
#line 66 "../src/contacts-avatar.vala"
		_g_object_unref0 (_data_->stream);
#line 422 "contacts-avatar.c"
	}
	goto __finally3;
	__catch3_g_error:
	{
#line 66 "../src/contacts-avatar.vala"
		_data_->e = _data_->_inner_error0_;
#line 66 "../src/contacts-avatar.vala"
		_data_->_inner_error0_ = NULL;
#line 72 "../src/contacts-avatar.vala"
		_data_->_tmp9_ = _data_->self->priv->individual;
#line 72 "../src/contacts-avatar.vala"
		_data_->_tmp10_ = folks_individual_get_display_name (_data_->_tmp9_);
#line 72 "../src/contacts-avatar.vala"
		_data_->_tmp11_ = _data_->_tmp10_;
#line 72 "../src/contacts-avatar.vala"
		_data_->_tmp12_ = _data_->e;
#line 72 "../src/contacts-avatar.vala"
		_data_->_tmp13_ = _data_->_tmp12_->message;
#line 72 "../src/contacts-avatar.vala"
		g_debug ("contacts-avatar.vala:72: Couldn't load avatar of contact %s. Reason: %" \
"s", _data_->_tmp11_, _data_->_tmp13_);
#line 66 "../src/contacts-avatar.vala"
		_g_error_free0 (_data_->e);
#line 445 "contacts-avatar.c"
	}
	__finally3:
#line 66 "../src/contacts-avatar.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 66 "../src/contacts-avatar.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 66 "../src/contacts-avatar.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 66 "../src/contacts-avatar.vala"
		g_object_unref (_data_->_async_result);
#line 66 "../src/contacts-avatar.vala"
		return FALSE;
#line 458 "contacts-avatar.c"
	}
#line 62 "../src/contacts-avatar.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 62 "../src/contacts-avatar.vala"
	if (_data_->_state_ != 0) {
#line 62 "../src/contacts-avatar.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 62 "../src/contacts-avatar.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 468 "contacts-avatar.c"
		}
	}
#line 62 "../src/contacts-avatar.vala"
	g_object_unref (_data_->_async_result);
#line 62 "../src/contacts-avatar.vala"
	return FALSE;
#line 475 "contacts-avatar.c"
}

static gboolean
contacts_avatar_real_draw (GtkWidget* base,
                           cairo_t* cr)
{
	ContactsAvatar * self;
	GdkPixbuf* _tmp0_;
	gboolean result = FALSE;
#line 76 "../src/contacts-avatar.vala"
	self = (ContactsAvatar*) base;
#line 76 "../src/contacts-avatar.vala"
	g_return_val_if_fail (cr != NULL, FALSE);
#line 78 "../src/contacts-avatar.vala"
	if (!self->priv->avatar_loaded) {
#line 79 "../src/contacts-avatar.vala"
		contacts_avatar_load_avatar (self, NULL, NULL);
#line 493 "contacts-avatar.c"
	}
#line 81 "../src/contacts-avatar.vala"
	_tmp0_ = self->priv->cache;
#line 81 "../src/contacts-avatar.vala"
	if (_tmp0_ != NULL) {
#line 499 "contacts-avatar.c"
	} else {
		GdkPixbuf* _tmp1_;
#line 83 "../src/contacts-avatar.vala"
		_tmp1_ = self->priv->pixbuf;
#line 83 "../src/contacts-avatar.vala"
		if (_tmp1_ != NULL) {
#line 506 "contacts-avatar.c"
			GdkPixbuf* _tmp2_;
#line 84 "../src/contacts-avatar.vala"
			_tmp2_ = contacts_avatar_create_contact_avatar (self);
#line 84 "../src/contacts-avatar.vala"
			_g_object_unref0 (self->priv->cache);
#line 84 "../src/contacts-avatar.vala"
			self->priv->cache = _tmp2_;
#line 514 "contacts-avatar.c"
		} else {
			GdkPixbuf* _tmp3_;
#line 86 "../src/contacts-avatar.vala"
			_tmp3_ = contacts_avatar_create_fallback (self);
#line 86 "../src/contacts-avatar.vala"
			_g_object_unref0 (self->priv->cache);
#line 86 "../src/contacts-avatar.vala"
			self->priv->cache = _tmp3_;
#line 523 "contacts-avatar.c"
		}
	}
#line 88 "../src/contacts-avatar.vala"
	contacts_avatar_draw_cached_avatar (self, cr);
#line 90 "../src/contacts-avatar.vala"
	result = TRUE;
#line 90 "../src/contacts-avatar.vala"
	return result;
#line 532 "contacts-avatar.c"
}

static void
contacts_avatar_draw_cached_avatar (ContactsAvatar* self,
                                    cairo_t* cr)
{
	GdkPixbuf* _tmp0_;
#line 93 "../src/contacts-avatar.vala"
	g_return_if_fail (self != NULL);
#line 93 "../src/contacts-avatar.vala"
	g_return_if_fail (cr != NULL);
#line 94 "../src/contacts-avatar.vala"
	_tmp0_ = self->priv->cache;
#line 94 "../src/contacts-avatar.vala"
	gdk_cairo_set_source_pixbuf (cr, _tmp0_, (gdouble) 0, (gdouble) 0);
#line 95 "../src/contacts-avatar.vala"
	cairo_paint (cr);
#line 550 "contacts-avatar.c"
}

static GdkPixbuf*
contacts_avatar_create_contact_avatar (ContactsAvatar* self)
{
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
	GdkPixbuf* result = NULL;
#line 98 "../src/contacts-avatar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 99 "../src/contacts-avatar.vala"
	_tmp0_ = self->priv->pixbuf;
#line 99 "../src/contacts-avatar.vala"
	_tmp1_ = contacts_avatar_utils_round_image (_tmp0_);
#line 99 "../src/contacts-avatar.vala"
	result = _tmp1_;
#line 99 "../src/contacts-avatar.vala"
	return result;
#line 569 "contacts-avatar.c"
}

static GdkPixbuf*
contacts_avatar_create_fallback (ContactsAvatar* self)
{
	gchar* name = NULL;
	gchar* _tmp0_;
	gboolean show_label = FALSE;
	FolksIndividual* _tmp1_;
	GdkPixbuf* pixbuf = NULL;
	const gchar* _tmp8_;
	GdkPixbuf* _tmp9_;
	GdkPixbuf* _tmp10_;
	GdkPixbuf* _tmp11_;
	GdkPixbuf* result = NULL;
#line 102 "../src/contacts-avatar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 103 "../src/contacts-avatar.vala"
	_tmp0_ = g_strdup ("");
#line 103 "../src/contacts-avatar.vala"
	name = _tmp0_;
#line 104 "../src/contacts-avatar.vala"
	show_label = FALSE;
#line 105 "../src/contacts-avatar.vala"
	_tmp1_ = self->priv->individual;
#line 105 "../src/contacts-avatar.vala"
	if (_tmp1_ != NULL) {
#line 597 "contacts-avatar.c"
		gchar* _tmp2_;
		const gchar* _tmp3_;
#line 106 "../src/contacts-avatar.vala"
		_tmp2_ = contacts_avatar_find_display_name (self);
#line 106 "../src/contacts-avatar.vala"
		_g_free0 (name);
#line 106 "../src/contacts-avatar.vala"
		name = _tmp2_;
#line 110 "../src/contacts-avatar.vala"
		_tmp3_ = name;
#line 110 "../src/contacts-avatar.vala"
		if (g_strcmp0 (_tmp3_, "") == 0) {
#line 610 "contacts-avatar.c"
			FolksIndividual* _tmp4_;
			const gchar* _tmp5_;
			const gchar* _tmp6_;
			gchar* _tmp7_;
#line 111 "../src/contacts-avatar.vala"
			_tmp4_ = self->priv->individual;
#line 111 "../src/contacts-avatar.vala"
			_tmp5_ = folks_individual_get_display_name (_tmp4_);
#line 111 "../src/contacts-avatar.vala"
			_tmp6_ = _tmp5_;
#line 111 "../src/contacts-avatar.vala"
			_tmp7_ = g_strdup (_tmp6_);
#line 111 "../src/contacts-avatar.vala"
			_g_free0 (name);
#line 111 "../src/contacts-avatar.vala"
			name = _tmp7_;
#line 627 "contacts-avatar.c"
		} else {
#line 113 "../src/contacts-avatar.vala"
			show_label = TRUE;
#line 631 "contacts-avatar.c"
		}
	}
#line 116 "../src/contacts-avatar.vala"
	_tmp8_ = name;
#line 116 "../src/contacts-avatar.vala"
	_tmp9_ = contacts_avatar_utils_generate_user_picture (_tmp8_, self->priv->size, show_label);
#line 116 "../src/contacts-avatar.vala"
	pixbuf = _tmp9_;
#line 117 "../src/contacts-avatar.vala"
	_tmp10_ = pixbuf;
#line 117 "../src/contacts-avatar.vala"
	_tmp11_ = contacts_avatar_utils_round_image (_tmp10_);
#line 117 "../src/contacts-avatar.vala"
	_g_object_unref0 (pixbuf);
#line 117 "../src/contacts-avatar.vala"
	pixbuf = _tmp11_;
#line 119 "../src/contacts-avatar.vala"
	result = pixbuf;
#line 119 "../src/contacts-avatar.vala"
	_g_free0 (name);
#line 119 "../src/contacts-avatar.vala"
	return result;
#line 654 "contacts-avatar.c"
}

static gchar*
contacts_avatar_find_display_name (ContactsAvatar* self)
{
	gchar* name = NULL;
	gchar* _tmp0_;
	FolksPersona* primary_persona = NULL;
	FolksPersona* _tmp15_;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	const gchar* _tmp27_;
	gchar* result = NULL;
#line 126 "../src/contacts-avatar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 127 "../src/contacts-avatar.vala"
	_tmp0_ = g_strdup ("");
#line 127 "../src/contacts-avatar.vala"
	name = _tmp0_;
#line 128 "../src/contacts-avatar.vala"
	primary_persona = NULL;
#line 676 "contacts-avatar.c"
	{
		GeeIterator* _p_it = NULL;
		FolksIndividual* _tmp1_;
		GeeSet* _tmp2_;
		GeeSet* _tmp3_;
		GeeIterator* _tmp4_;
#line 129 "../src/contacts-avatar.vala"
		_tmp1_ = self->priv->individual;
#line 129 "../src/contacts-avatar.vala"
		_tmp2_ = folks_individual_get_personas (_tmp1_);
#line 129 "../src/contacts-avatar.vala"
		_tmp3_ = _tmp2_;
#line 129 "../src/contacts-avatar.vala"
		_tmp4_ = gee_iterable_iterator ((GeeIterable*) _tmp3_);
#line 129 "../src/contacts-avatar.vala"
		_p_it = _tmp4_;
#line 129 "../src/contacts-avatar.vala"
		while (TRUE) {
#line 695 "contacts-avatar.c"
			GeeIterator* _tmp5_;
			FolksPersona* p = NULL;
			GeeIterator* _tmp6_;
			gpointer _tmp7_;
			FolksPersona* _tmp8_;
			FolksPersonaStore* _tmp9_;
			FolksPersonaStore* _tmp10_;
			gboolean _tmp11_;
			gboolean _tmp12_;
#line 129 "../src/contacts-avatar.vala"
			_tmp5_ = _p_it;
#line 129 "../src/contacts-avatar.vala"
			if (!gee_iterator_next (_tmp5_)) {
#line 129 "../src/contacts-avatar.vala"
				break;
#line 711 "contacts-avatar.c"
			}
#line 129 "../src/contacts-avatar.vala"
			_tmp6_ = _p_it;
#line 129 "../src/contacts-avatar.vala"
			_tmp7_ = gee_iterator_get (_tmp6_);
#line 129 "../src/contacts-avatar.vala"
			p = (FolksPersona*) _tmp7_;
#line 130 "../src/contacts-avatar.vala"
			_tmp8_ = p;
#line 130 "../src/contacts-avatar.vala"
			_tmp9_ = folks_persona_get_store (_tmp8_);
#line 130 "../src/contacts-avatar.vala"
			_tmp10_ = _tmp9_;
#line 130 "../src/contacts-avatar.vala"
			_tmp11_ = folks_persona_store_get_is_primary_store (_tmp10_);
#line 130 "../src/contacts-avatar.vala"
			_tmp12_ = _tmp11_;
#line 130 "../src/contacts-avatar.vala"
			if (_tmp12_) {
#line 731 "contacts-avatar.c"
				FolksPersona* _tmp13_;
				FolksPersona* _tmp14_;
#line 131 "../src/contacts-avatar.vala"
				_tmp13_ = p;
#line 131 "../src/contacts-avatar.vala"
				_tmp14_ = _g_object_ref0 (_tmp13_);
#line 131 "../src/contacts-avatar.vala"
				_g_object_unref0 (primary_persona);
#line 131 "../src/contacts-avatar.vala"
				primary_persona = _tmp14_;
#line 132 "../src/contacts-avatar.vala"
				_g_object_unref0 (p);
#line 132 "../src/contacts-avatar.vala"
				break;
#line 746 "contacts-avatar.c"
			}
#line 129 "../src/contacts-avatar.vala"
			_g_object_unref0 (p);
#line 750 "contacts-avatar.c"
		}
#line 129 "../src/contacts-avatar.vala"
		_g_object_unref0 (_p_it);
#line 754 "contacts-avatar.c"
	}
#line 135 "../src/contacts-avatar.vala"
	_tmp15_ = primary_persona;
#line 135 "../src/contacts-avatar.vala"
	_tmp16_ = contacts_avatar_look_up_alias_for_display_name (self, _tmp15_);
#line 135 "../src/contacts-avatar.vala"
	_g_free0 (name);
#line 135 "../src/contacts-avatar.vala"
	name = _tmp16_;
#line 136 "../src/contacts-avatar.vala"
	_tmp17_ = name;
#line 136 "../src/contacts-avatar.vala"
	if (g_strcmp0 (_tmp17_, "") == 0) {
#line 768 "contacts-avatar.c"
		{
			GeeIterator* _p_it = NULL;
			FolksIndividual* _tmp18_;
			GeeSet* _tmp19_;
			GeeSet* _tmp20_;
			GeeIterator* _tmp21_;
#line 137 "../src/contacts-avatar.vala"
			_tmp18_ = self->priv->individual;
#line 137 "../src/contacts-avatar.vala"
			_tmp19_ = folks_individual_get_personas (_tmp18_);
#line 137 "../src/contacts-avatar.vala"
			_tmp20_ = _tmp19_;
#line 137 "../src/contacts-avatar.vala"
			_tmp21_ = gee_iterable_iterator ((GeeIterable*) _tmp20_);
#line 137 "../src/contacts-avatar.vala"
			_p_it = _tmp21_;
#line 137 "../src/contacts-avatar.vala"
			while (TRUE) {
#line 787 "contacts-avatar.c"
				GeeIterator* _tmp22_;
				FolksPersona* p = NULL;
				GeeIterator* _tmp23_;
				gpointer _tmp24_;
				FolksPersona* _tmp25_;
				gchar* _tmp26_;
#line 137 "../src/contacts-avatar.vala"
				_tmp22_ = _p_it;
#line 137 "../src/contacts-avatar.vala"
				if (!gee_iterator_next (_tmp22_)) {
#line 137 "../src/contacts-avatar.vala"
					break;
#line 800 "contacts-avatar.c"
				}
#line 137 "../src/contacts-avatar.vala"
				_tmp23_ = _p_it;
#line 137 "../src/contacts-avatar.vala"
				_tmp24_ = gee_iterator_get (_tmp23_);
#line 137 "../src/contacts-avatar.vala"
				p = (FolksPersona*) _tmp24_;
#line 138 "../src/contacts-avatar.vala"
				_tmp25_ = p;
#line 138 "../src/contacts-avatar.vala"
				_tmp26_ = contacts_avatar_look_up_alias_for_display_name (self, _tmp25_);
#line 138 "../src/contacts-avatar.vala"
				_g_free0 (name);
#line 138 "../src/contacts-avatar.vala"
				name = _tmp26_;
#line 137 "../src/contacts-avatar.vala"
				_g_object_unref0 (p);
#line 818 "contacts-avatar.c"
			}
#line 137 "../src/contacts-avatar.vala"
			_g_object_unref0 (_p_it);
#line 822 "contacts-avatar.c"
		}
	}
#line 141 "../src/contacts-avatar.vala"
	_tmp27_ = name;
#line 141 "../src/contacts-avatar.vala"
	if (g_strcmp0 (_tmp27_, "") == 0) {
#line 829 "contacts-avatar.c"
		{
			GeeIterator* _p_it = NULL;
			FolksIndividual* _tmp28_;
			GeeSet* _tmp29_;
			GeeSet* _tmp30_;
			GeeIterator* _tmp31_;
#line 142 "../src/contacts-avatar.vala"
			_tmp28_ = self->priv->individual;
#line 142 "../src/contacts-avatar.vala"
			_tmp29_ = folks_individual_get_personas (_tmp28_);
#line 142 "../src/contacts-avatar.vala"
			_tmp30_ = _tmp29_;
#line 142 "../src/contacts-avatar.vala"
			_tmp31_ = gee_iterable_iterator ((GeeIterable*) _tmp30_);
#line 142 "../src/contacts-avatar.vala"
			_p_it = _tmp31_;
#line 142 "../src/contacts-avatar.vala"
			while (TRUE) {
#line 848 "contacts-avatar.c"
				GeeIterator* _tmp32_;
				FolksPersona* p = NULL;
				GeeIterator* _tmp33_;
				gpointer _tmp34_;
				FolksPersona* _tmp35_;
				gchar* _tmp36_;
#line 142 "../src/contacts-avatar.vala"
				_tmp32_ = _p_it;
#line 142 "../src/contacts-avatar.vala"
				if (!gee_iterator_next (_tmp32_)) {
#line 142 "../src/contacts-avatar.vala"
					break;
#line 861 "contacts-avatar.c"
				}
#line 142 "../src/contacts-avatar.vala"
				_tmp33_ = _p_it;
#line 142 "../src/contacts-avatar.vala"
				_tmp34_ = gee_iterator_get (_tmp33_);
#line 142 "../src/contacts-avatar.vala"
				p = (FolksPersona*) _tmp34_;
#line 143 "../src/contacts-avatar.vala"
				_tmp35_ = p;
#line 143 "../src/contacts-avatar.vala"
				_tmp36_ = contacts_avatar_look_up_name_details_for_display_name (self, _tmp35_);
#line 143 "../src/contacts-avatar.vala"
				_g_free0 (name);
#line 143 "../src/contacts-avatar.vala"
				name = _tmp36_;
#line 142 "../src/contacts-avatar.vala"
				_g_object_unref0 (p);
#line 879 "contacts-avatar.c"
			}
#line 142 "../src/contacts-avatar.vala"
			_g_object_unref0 (_p_it);
#line 883 "contacts-avatar.c"
		}
	}
#line 146 "../src/contacts-avatar.vala"
	result = name;
#line 146 "../src/contacts-avatar.vala"
	_g_object_unref0 (primary_persona);
#line 146 "../src/contacts-avatar.vala"
	return result;
#line 892 "contacts-avatar.c"
}

static gchar*
contacts_avatar_look_up_alias_for_display_name (ContactsAvatar* self,
                                                FolksPersona* p)
{
	FolksAliasDetails* a = NULL;
	FolksAliasDetails* _tmp0_;
	gboolean _tmp1_ = FALSE;
	FolksAliasDetails* _tmp2_;
	gchar* _tmp10_;
	gchar* result = NULL;
#line 149 "../src/contacts-avatar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 150 "../src/contacts-avatar.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (p, FOLKS_TYPE_ALIAS_DETAILS) ? ((FolksAliasDetails*) p) : NULL);
#line 150 "../src/contacts-avatar.vala"
	a = _tmp0_;
#line 151 "../src/contacts-avatar.vala"
	_tmp2_ = a;
#line 151 "../src/contacts-avatar.vala"
	if (_tmp2_ != NULL) {
#line 915 "contacts-avatar.c"
		FolksAliasDetails* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
#line 151 "../src/contacts-avatar.vala"
		_tmp3_ = a;
#line 151 "../src/contacts-avatar.vala"
		_tmp4_ = folks_alias_details_get_alias (_tmp3_);
#line 151 "../src/contacts-avatar.vala"
		_tmp5_ = _tmp4_;
#line 151 "../src/contacts-avatar.vala"
		_tmp1_ = _tmp5_ != NULL;
#line 927 "contacts-avatar.c"
	} else {
#line 151 "../src/contacts-avatar.vala"
		_tmp1_ = FALSE;
#line 931 "contacts-avatar.c"
	}
#line 151 "../src/contacts-avatar.vala"
	if (_tmp1_) {
#line 935 "contacts-avatar.c"
		FolksAliasDetails* _tmp6_;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
#line 152 "../src/contacts-avatar.vala"
		_tmp6_ = a;
#line 152 "../src/contacts-avatar.vala"
		_tmp7_ = folks_alias_details_get_alias (_tmp6_);
#line 152 "../src/contacts-avatar.vala"
		_tmp8_ = _tmp7_;
#line 152 "../src/contacts-avatar.vala"
		_tmp9_ = g_strdup (_tmp8_);
#line 152 "../src/contacts-avatar.vala"
		result = _tmp9_;
#line 152 "../src/contacts-avatar.vala"
		_g_object_unref0 (a);
#line 152 "../src/contacts-avatar.vala"
		return result;
#line 954 "contacts-avatar.c"
	}
#line 154 "../src/contacts-avatar.vala"
	_tmp10_ = g_strdup ("");
#line 154 "../src/contacts-avatar.vala"
	result = _tmp10_;
#line 154 "../src/contacts-avatar.vala"
	_g_object_unref0 (a);
#line 154 "../src/contacts-avatar.vala"
	return result;
#line 964 "contacts-avatar.c"
}

static gchar*
contacts_avatar_look_up_name_details_for_display_name (ContactsAvatar* self,
                                                       FolksPersona* p)
{
	FolksNameDetails* n = NULL;
	FolksNameDetails* _tmp0_;
	FolksNameDetails* _tmp1_;
	gchar* _tmp27_;
	gchar* result = NULL;
#line 157 "../src/contacts-avatar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 158 "../src/contacts-avatar.vala"
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (p, FOLKS_TYPE_NAME_DETAILS) ? ((FolksNameDetails*) p) : NULL);
#line 158 "../src/contacts-avatar.vala"
	n = _tmp0_;
#line 159 "../src/contacts-avatar.vala"
	_tmp1_ = n;
#line 159 "../src/contacts-avatar.vala"
	if (_tmp1_ != NULL) {
#line 986 "contacts-avatar.c"
		gboolean _tmp2_ = FALSE;
		FolksNameDetails* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
#line 160 "../src/contacts-avatar.vala"
		_tmp3_ = n;
#line 160 "../src/contacts-avatar.vala"
		_tmp4_ = folks_name_details_get_full_name (_tmp3_);
#line 160 "../src/contacts-avatar.vala"
		_tmp5_ = _tmp4_;
#line 160 "../src/contacts-avatar.vala"
		if (_tmp5_ != NULL) {
#line 999 "contacts-avatar.c"
			FolksNameDetails* _tmp6_;
			const gchar* _tmp7_;
			const gchar* _tmp8_;
#line 160 "../src/contacts-avatar.vala"
			_tmp6_ = n;
#line 160 "../src/contacts-avatar.vala"
			_tmp7_ = folks_name_details_get_full_name (_tmp6_);
#line 160 "../src/contacts-avatar.vala"
			_tmp8_ = _tmp7_;
#line 160 "../src/contacts-avatar.vala"
			_tmp2_ = g_strcmp0 (_tmp8_, "") != 0;
#line 1011 "contacts-avatar.c"
		} else {
#line 160 "../src/contacts-avatar.vala"
			_tmp2_ = FALSE;
#line 1015 "contacts-avatar.c"
		}
#line 160 "../src/contacts-avatar.vala"
		if (_tmp2_) {
#line 1019 "contacts-avatar.c"
			FolksNameDetails* _tmp9_;
			const gchar* _tmp10_;
			const gchar* _tmp11_;
			gchar* _tmp12_;
#line 161 "../src/contacts-avatar.vala"
			_tmp9_ = n;
#line 161 "../src/contacts-avatar.vala"
			_tmp10_ = folks_name_details_get_full_name (_tmp9_);
#line 161 "../src/contacts-avatar.vala"
			_tmp11_ = _tmp10_;
#line 161 "../src/contacts-avatar.vala"
			_tmp12_ = g_strdup (_tmp11_);
#line 161 "../src/contacts-avatar.vala"
			result = _tmp12_;
#line 161 "../src/contacts-avatar.vala"
			_g_object_unref0 (n);
#line 161 "../src/contacts-avatar.vala"
			return result;
#line 1038 "contacts-avatar.c"
		} else {
			FolksNameDetails* _tmp13_;
			FolksStructuredName* _tmp14_;
			FolksStructuredName* _tmp15_;
#line 162 "../src/contacts-avatar.vala"
			_tmp13_ = n;
#line 162 "../src/contacts-avatar.vala"
			_tmp14_ = folks_name_details_get_structured_name (_tmp13_);
#line 162 "../src/contacts-avatar.vala"
			_tmp15_ = _tmp14_;
#line 162 "../src/contacts-avatar.vala"
			if (_tmp15_ != NULL) {
#line 1051 "contacts-avatar.c"
				FolksNameDetails* _tmp16_;
				FolksStructuredName* _tmp17_;
				FolksStructuredName* _tmp18_;
				gchar* _tmp19_;
#line 163 "../src/contacts-avatar.vala"
				_tmp16_ = n;
#line 163 "../src/contacts-avatar.vala"
				_tmp17_ = folks_name_details_get_structured_name (_tmp16_);
#line 163 "../src/contacts-avatar.vala"
				_tmp18_ = _tmp17_;
#line 163 "../src/contacts-avatar.vala"
				_tmp19_ = folks_structured_name_to_string (_tmp18_);
#line 163 "../src/contacts-avatar.vala"
				result = _tmp19_;
#line 163 "../src/contacts-avatar.vala"
				_g_object_unref0 (n);
#line 163 "../src/contacts-avatar.vala"
				return result;
#line 1070 "contacts-avatar.c"
			} else {
				FolksNameDetails* _tmp20_;
				const gchar* _tmp21_;
				const gchar* _tmp22_;
#line 164 "../src/contacts-avatar.vala"
				_tmp20_ = n;
#line 164 "../src/contacts-avatar.vala"
				_tmp21_ = folks_name_details_get_nickname (_tmp20_);
#line 164 "../src/contacts-avatar.vala"
				_tmp22_ = _tmp21_;
#line 164 "../src/contacts-avatar.vala"
				if (g_strcmp0 (_tmp22_, "") != 0) {
#line 1083 "contacts-avatar.c"
					FolksNameDetails* _tmp23_;
					const gchar* _tmp24_;
					const gchar* _tmp25_;
					gchar* _tmp26_;
#line 165 "../src/contacts-avatar.vala"
					_tmp23_ = n;
#line 165 "../src/contacts-avatar.vala"
					_tmp24_ = folks_name_details_get_nickname (_tmp23_);
#line 165 "../src/contacts-avatar.vala"
					_tmp25_ = _tmp24_;
#line 165 "../src/contacts-avatar.vala"
					_tmp26_ = g_strdup (_tmp25_);
#line 165 "../src/contacts-avatar.vala"
					result = _tmp26_;
#line 165 "../src/contacts-avatar.vala"
					_g_object_unref0 (n);
#line 165 "../src/contacts-avatar.vala"
					return result;
#line 1102 "contacts-avatar.c"
				}
			}
		}
	}
#line 168 "../src/contacts-avatar.vala"
	_tmp27_ = g_strdup ("");
#line 168 "../src/contacts-avatar.vala"
	result = _tmp27_;
#line 168 "../src/contacts-avatar.vala"
	_g_object_unref0 (n);
#line 168 "../src/contacts-avatar.vala"
	return result;
#line 1115 "contacts-avatar.c"
}

static void
contacts_avatar_class_init (ContactsAvatarClass * klass,
                            gpointer klass_data)
{
#line 26 "../src/contacts-avatar.vala"
	contacts_avatar_parent_class = g_type_class_peek_parent (klass);
#line 26 "../src/contacts-avatar.vala"
	g_type_class_adjust_private_offset (klass, &ContactsAvatar_private_offset);
#line 26 "../src/contacts-avatar.vala"
	((GtkWidgetClass *) klass)->draw = (gboolean (*) (GtkWidget*, cairo_t*)) contacts_avatar_real_draw;
#line 26 "../src/contacts-avatar.vala"
	G_OBJECT_CLASS (klass)->finalize = contacts_avatar_finalize;
#line 1130 "contacts-avatar.c"
}

static void
contacts_avatar_instance_init (ContactsAvatar * self,
                               gpointer klass)
{
#line 26 "../src/contacts-avatar.vala"
	self->priv = contacts_avatar_get_instance_private (self);
#line 28 "../src/contacts-avatar.vala"
	self->priv->pixbuf = NULL;
#line 29 "../src/contacts-avatar.vala"
	self->priv->cache = NULL;
#line 31 "../src/contacts-avatar.vala"
	self->priv->individual = NULL;
#line 34 "../src/contacts-avatar.vala"
	self->priv->avatar_loaded = FALSE;
#line 1147 "contacts-avatar.c"
}

static void
contacts_avatar_finalize (GObject * obj)
{
	ContactsAvatar * self;
#line 26 "../src/contacts-avatar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_AVATAR, ContactsAvatar);
#line 28 "../src/contacts-avatar.vala"
	_g_object_unref0 (self->priv->pixbuf);
#line 29 "../src/contacts-avatar.vala"
	_g_object_unref0 (self->priv->cache);
#line 31 "../src/contacts-avatar.vala"
	_g_object_unref0 (self->priv->individual);
#line 26 "../src/contacts-avatar.vala"
	G_OBJECT_CLASS (contacts_avatar_parent_class)->finalize (obj);
#line 1164 "contacts-avatar.c"
}

/**
 * The Avatar of a Contact is responsible for showing an {@link Folks.Individual}'s
 * avatar, or a fallback if it's not available.
 */
static GType
contacts_avatar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsAvatarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_avatar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsAvatar), 0, (GInstanceInitFunc) contacts_avatar_instance_init, NULL };
	GType contacts_avatar_type_id;
	contacts_avatar_type_id = g_type_register_static (gtk_drawing_area_get_type (), "ContactsAvatar", &g_define_type_info, 0);
	ContactsAvatar_private_offset = g_type_add_instance_private (contacts_avatar_type_id, sizeof (ContactsAvatarPrivate));
	return contacts_avatar_type_id;
}

GType
contacts_avatar_get_type (void)
{
	static volatile gsize contacts_avatar_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_avatar_type_id__volatile)) {
		GType contacts_avatar_type_id;
		contacts_avatar_type_id = contacts_avatar_get_type_once ();
		g_once_init_leave (&contacts_avatar_type_id__volatile, contacts_avatar_type_id);
	}
	return contacts_avatar_type_id__volatile;
}

