/* contacts-type-combo.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-type-combo.vala, do not modify */

/*
 * Copyright (C) 2011 Alexander Larsson <alexl@redhat.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include "contacts.h"
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <folks/folks.h>

#define CONTACTS_TYPE_TYPECOMBO (contacts_typecombo_get_type ())
#define CONTACTS_TYPECOMBO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_TYPECOMBO, ContactsTypeCombo))
#define CONTACTS_TYPECOMBO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_TYPECOMBO, ContactsTypeComboClass))
#define CONTACTS_IS_TYPECOMBO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_TYPECOMBO))
#define CONTACTS_IS_TYPECOMBO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_TYPECOMBO))
#define CONTACTS_TYPECOMBO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_TYPECOMBO, ContactsTypeComboClass))

typedef struct _ContactsTypeCombo ContactsTypeCombo;
typedef struct _ContactsTypeComboClass ContactsTypeComboClass;
typedef struct _ContactsTypeComboPrivate ContactsTypeComboPrivate;
enum  {
	CONTACTS_TYPECOMBO_0_PROPERTY,
	CONTACTS_TYPECOMBO_ACTIVE_DESCRIPTOR_PROPERTY,
	CONTACTS_TYPECOMBO_NUM_PROPERTIES
};
static GParamSpec* contacts_typecombo_properties[CONTACTS_TYPECOMBO_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _ContactsTypeCombo {
	GtkComboBox parent_instance;
	ContactsTypeComboPrivate * priv;
};

struct _ContactsTypeComboClass {
	GtkComboBoxClass parent_class;
};

struct _ContactsTypeComboPrivate {
	ContactsTypeSet* type_set;
};

static gint ContactsTypeCombo_private_offset;
static gpointer contacts_typecombo_parent_class = NULL;

GType contacts_typecombo_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsTypeCombo, g_object_unref)
ContactsTypeCombo* contacts_typecombo_new (ContactsTypeSet* type_set);
ContactsTypeCombo* contacts_typecombo_construct (GType object_type,
                                                 ContactsTypeSet* type_set);
static gboolean contacts_typecombo_is_separator (ContactsTypeCombo* self,
                                          GtkTreeModel* model,
                                          GtkTreeIter* iter);
void contacts_typecombo_set_active_from_field_details (ContactsTypeCombo* self,
                                                       FolksAbstractFieldDetails* details);
void contacts_typecombo_set_active_descriptor (ContactsTypeCombo* self,
                                               ContactsTypeDescriptor* value);
void contacts_typecombo_set_active_from_vcard_type (ContactsTypeCombo* self,
                                                    const gchar* type);
ContactsTypeDescriptor* contacts_typecombo_get_active_descriptor (ContactsTypeCombo* self);
static GObject * contacts_typecombo_constructor (GType type,
                                          guint n_construct_properties,
                                          GObjectConstructParam * construct_properties);
static gboolean _contacts_typecombo_is_separator_gtk_tree_view_row_separator_func (GtkTreeModel* model,
                                                                            GtkTreeIter* iter,
                                                                            gpointer self);
static void contacts_typecombo_finalize (GObject * obj);
static GType contacts_typecombo_get_type_once (void);
static void _vala_contacts_typecombo_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec);
static void _vala_contacts_typecombo_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec);

static inline gpointer
contacts_typecombo_get_instance_private (ContactsTypeCombo* self)
{
	return G_STRUCT_MEMBER_P (self, ContactsTypeCombo_private_offset);
}

/**
   * Creates a TypeCombo for the given TypeSet. To set the active value,
   * use the "current-decsriptor" property, set_active_from_field_details(),
   * or set_active_from_vcard_type()
   */
ContactsTypeCombo*
contacts_typecombo_construct (GType object_type,
                              ContactsTypeSet* type_set)
{
	ContactsTypeCombo * self = NULL;
	GtkListStore* _tmp0_;
	GtkListStore* _tmp1_;
#line 69 "../src/contacts-type-combo.vala"
	g_return_val_if_fail (type_set != NULL, NULL);
#line 69 "../src/contacts-type-combo.vala"
	self = (ContactsTypeCombo*) g_object_new (object_type, NULL);
#line 70 "../src/contacts-type-combo.vala"
	self->priv->type_set = type_set;
#line 71 "../src/contacts-type-combo.vala"
	_tmp0_ = contacts_typeset_get_store (type_set);
#line 71 "../src/contacts-type-combo.vala"
	_tmp1_ = _tmp0_;
#line 71 "../src/contacts-type-combo.vala"
	gtk_combo_box_set_model ((GtkComboBox*) self, (GtkTreeModel*) _tmp1_);
#line 69 "../src/contacts-type-combo.vala"
	return self;
#line 132 "contacts-type-combo.c"
}

ContactsTypeCombo*
contacts_typecombo_new (ContactsTypeSet* type_set)
{
#line 69 "../src/contacts-type-combo.vala"
	return contacts_typecombo_construct (CONTACTS_TYPE_TYPECOMBO, type_set);
#line 140 "contacts-type-combo.c"
}

static gboolean
contacts_typecombo_is_separator (ContactsTypeCombo* self,
                                 GtkTreeModel* model,
                                 GtkTreeIter* iter)
{
	const gchar* s = NULL;
	GtkTreeIter _tmp0_;
	const gchar* _tmp1_ = NULL;
	gboolean result = FALSE;
#line 74 "../src/contacts-type-combo.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 74 "../src/contacts-type-combo.vala"
	g_return_val_if_fail (model != NULL, FALSE);
#line 74 "../src/contacts-type-combo.vala"
	g_return_val_if_fail (iter != NULL, FALSE);
#line 76 "../src/contacts-type-combo.vala"
	_tmp0_ = *iter;
#line 76 "../src/contacts-type-combo.vala"
	gtk_tree_model_get (model, &_tmp0_, 0, &_tmp1_, -1);
#line 76 "../src/contacts-type-combo.vala"
	s = _tmp1_;
#line 77 "../src/contacts-type-combo.vala"
	result = s == NULL;
#line 77 "../src/contacts-type-combo.vala"
	return result;
#line 168 "contacts-type-combo.c"
}

/**
   * Sets the value to the type of the given {@link Folks.AbstractFieldDetails}.
   */
void
contacts_typecombo_set_active_from_field_details (ContactsTypeCombo* self,
                                                  FolksAbstractFieldDetails* details)
{
	ContactsTypeSet* _tmp0_;
	ContactsTypeDescriptor* _tmp1_;
	ContactsTypeDescriptor* _tmp2_;
#line 83 "../src/contacts-type-combo.vala"
	g_return_if_fail (self != NULL);
#line 83 "../src/contacts-type-combo.vala"
	g_return_if_fail (details != NULL);
#line 84 "../src/contacts-type-combo.vala"
	_tmp0_ = self->priv->type_set;
#line 84 "../src/contacts-type-combo.vala"
	_tmp1_ = contacts_typeset_lookup_descriptor_for_field_details (_tmp0_, details);
#line 84 "../src/contacts-type-combo.vala"
	_tmp2_ = _tmp1_;
#line 84 "../src/contacts-type-combo.vala"
	contacts_typecombo_set_active_descriptor (self, _tmp2_);
#line 84 "../src/contacts-type-combo.vala"
	_g_object_unref0 (_tmp2_);
#line 195 "contacts-type-combo.c"
}

/**
   * Sets the value to the type that best matches the given vcard type
   * (for example "HOME" or "WORK").
   */
void
contacts_typecombo_set_active_from_vcard_type (ContactsTypeCombo* self,
                                               const gchar* type)
{
	GtkTreeIter iter = {0};
	ContactsTypeSet* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	GtkTreeIter _tmp2_;
#line 91 "../src/contacts-type-combo.vala"
	g_return_if_fail (self != NULL);
#line 91 "../src/contacts-type-combo.vala"
	g_return_if_fail (type != NULL);
#line 93 "../src/contacts-type-combo.vala"
	_tmp0_ = self->priv->type_set;
#line 93 "../src/contacts-type-combo.vala"
	contacts_typeset_get_iter_for_vcard_type (_tmp0_, type, &_tmp1_);
#line 93 "../src/contacts-type-combo.vala"
	iter = _tmp1_;
#line 94 "../src/contacts-type-combo.vala"
	_tmp2_ = iter;
#line 94 "../src/contacts-type-combo.vala"
	gtk_combo_box_set_active_iter ((GtkComboBox*) self, &_tmp2_);
#line 224 "contacts-type-combo.c"
}

ContactsTypeDescriptor*
contacts_typecombo_get_active_descriptor (ContactsTypeCombo* self)
{
	ContactsTypeDescriptor* result;
	GtkTreeIter iter = {0};
	GtkTreeIter _tmp0_ = {0};
	GtkTreeModel* _tmp1_;
	GtkTreeModel* _tmp2_;
	GtkTreeIter _tmp3_;
	ContactsTypeDescriptor* descriptor = NULL;
	GtkTreeModel* _tmp4_;
	GtkTreeModel* _tmp5_;
	GtkTreeIter _tmp6_;
	ContactsTypeDescriptor* _tmp7_ = NULL;
#line 36 "../src/contacts-type-combo.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "../src/contacts-type-combo.vala"
	gtk_combo_box_get_active_iter ((GtkComboBox*) self, &_tmp0_);
#line 39 "../src/contacts-type-combo.vala"
	iter = _tmp0_;
#line 40 "../src/contacts-type-combo.vala"
	_tmp1_ = gtk_combo_box_get_model ((GtkComboBox*) self);
#line 40 "../src/contacts-type-combo.vala"
	_tmp2_ = _tmp1_;
#line 40 "../src/contacts-type-combo.vala"
	_tmp3_ = iter;
#line 40 "../src/contacts-type-combo.vala"
	_vala_assert (!contacts_typecombo_is_separator (self, _tmp2_, &_tmp3_), "!is_separator (this.model, iter)");
#line 43 "../src/contacts-type-combo.vala"
	_tmp4_ = gtk_combo_box_get_model ((GtkComboBox*) self);
#line 43 "../src/contacts-type-combo.vala"
	_tmp5_ = _tmp4_;
#line 43 "../src/contacts-type-combo.vala"
	_tmp6_ = iter;
#line 43 "../src/contacts-type-combo.vala"
	gtk_tree_model_get (_tmp5_, &_tmp6_, 1, &_tmp7_, -1);
#line 43 "../src/contacts-type-combo.vala"
	descriptor = _tmp7_;
#line 44 "../src/contacts-type-combo.vala"
	result = descriptor;
#line 44 "../src/contacts-type-combo.vala"
	return result;
#line 269 "contacts-type-combo.c"
}

void
contacts_typecombo_set_active_descriptor (ContactsTypeCombo* self,
                                          ContactsTypeDescriptor* value)
{
	GtkTreeIter _tmp0_;
#line 46 "../src/contacts-type-combo.vala"
	g_return_if_fail (self != NULL);
#line 47 "../src/contacts-type-combo.vala"
	_tmp0_ = value->iter;
#line 47 "../src/contacts-type-combo.vala"
	gtk_combo_box_set_active_iter ((GtkComboBox*) self, &_tmp0_);
#line 46 "../src/contacts-type-combo.vala"
	g_object_notify_by_pspec ((GObject *) self, contacts_typecombo_properties[CONTACTS_TYPECOMBO_ACTIVE_DESCRIPTOR_PROPERTY]);
#line 285 "contacts-type-combo.c"
}

static gboolean
_contacts_typecombo_is_separator_gtk_tree_view_row_separator_func (GtkTreeModel* model,
                                                                   GtkTreeIter* iter,
                                                                   gpointer self)
{
	gboolean result;
	result = contacts_typecombo_is_separator ((ContactsTypeCombo*) self, model, iter);
#line 61 "../src/contacts-type-combo.vala"
	return result;
#line 297 "contacts-type-combo.c"
}

static GObject *
contacts_typecombo_constructor (GType type,
                                guint n_construct_properties,
                                GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	ContactsTypeCombo * self;
	GtkCellRendererText* renderer = NULL;
	GtkCellRendererText* _tmp0_;
	GtkCellRendererText* _tmp1_;
	GtkCellRendererText* _tmp2_;
#line 51 "../src/contacts-type-combo.vala"
	parent_class = G_OBJECT_CLASS (contacts_typecombo_parent_class);
#line 51 "../src/contacts-type-combo.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 51 "../src/contacts-type-combo.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_TYPECOMBO, ContactsTypeCombo);
#line 52 "../src/contacts-type-combo.vala"
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_START);
#line 53 "../src/contacts-type-combo.vala"
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_FILL);
#line 54 "../src/contacts-type-combo.vala"
	gtk_widget_set_hexpand ((GtkWidget*) self, TRUE);
#line 55 "../src/contacts-type-combo.vala"
	gtk_widget_set_visible ((GtkWidget*) self, TRUE);
#line 57 "../src/contacts-type-combo.vala"
	_tmp0_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 57 "../src/contacts-type-combo.vala"
	g_object_ref_sink (_tmp0_);
#line 57 "../src/contacts-type-combo.vala"
	renderer = _tmp0_;
#line 58 "../src/contacts-type-combo.vala"
	_tmp1_ = renderer;
#line 58 "../src/contacts-type-combo.vala"
	gtk_cell_layout_pack_start ((GtkCellLayout*) self, (GtkCellRenderer*) _tmp1_, TRUE);
#line 59 "../src/contacts-type-combo.vala"
	_tmp2_ = renderer;
#line 59 "../src/contacts-type-combo.vala"
	gtk_cell_layout_set_attributes ((GtkCellLayout*) self, (GtkCellRenderer*) _tmp2_, "text", 0, NULL);
#line 61 "../src/contacts-type-combo.vala"
	gtk_combo_box_set_row_separator_func ((GtkComboBox*) self, _contacts_typecombo_is_separator_gtk_tree_view_row_separator_func, g_object_ref (self), g_object_unref);
#line 51 "../src/contacts-type-combo.vala"
	_g_object_unref0 (renderer);
#line 51 "../src/contacts-type-combo.vala"
	return obj;
#line 346 "contacts-type-combo.c"
}

static void
contacts_typecombo_class_init (ContactsTypeComboClass * klass,
                               gpointer klass_data)
{
#line 28 "../src/contacts-type-combo.vala"
	contacts_typecombo_parent_class = g_type_class_peek_parent (klass);
#line 28 "../src/contacts-type-combo.vala"
	g_type_class_adjust_private_offset (klass, &ContactsTypeCombo_private_offset);
#line 28 "../src/contacts-type-combo.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_contacts_typecombo_get_property;
#line 28 "../src/contacts-type-combo.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_contacts_typecombo_set_property;
#line 28 "../src/contacts-type-combo.vala"
	G_OBJECT_CLASS (klass)->constructor = contacts_typecombo_constructor;
#line 28 "../src/contacts-type-combo.vala"
	G_OBJECT_CLASS (klass)->finalize = contacts_typecombo_finalize;
#line 365 "contacts-type-combo.c"
	/**
	   * The {@link Contacts.TypeDescriptor} that is currently shown
	   */
#line 28 "../src/contacts-type-combo.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), CONTACTS_TYPECOMBO_ACTIVE_DESCRIPTOR_PROPERTY, contacts_typecombo_properties[CONTACTS_TYPECOMBO_ACTIVE_DESCRIPTOR_PROPERTY] = g_param_spec_object ("active-descriptor", "active-descriptor", "active-descriptor", CONTACTS_TYPE_TYPEDESCRIPTOR, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 371 "contacts-type-combo.c"
}

static void
contacts_typecombo_instance_init (ContactsTypeCombo * self,
                                  gpointer klass)
{
#line 28 "../src/contacts-type-combo.vala"
	self->priv = contacts_typecombo_get_instance_private (self);
#line 380 "contacts-type-combo.c"
}

static void
contacts_typecombo_finalize (GObject * obj)
{
	ContactsTypeCombo * self;
#line 28 "../src/contacts-type-combo.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_TYPECOMBO, ContactsTypeCombo);
#line 28 "../src/contacts-type-combo.vala"
	G_OBJECT_CLASS (contacts_typecombo_parent_class)->finalize (obj);
#line 391 "contacts-type-combo.c"
}

/**
 * The TypeCombo is a widget that fills itself with the types of a certain
 * category (using {@link Contacts.TypeSet}). For example, it allows the user
 * to choose between "Personal", "Home" and "Work" for email addresses,
 * together with all the custom labels it has encountered since then.
 */
static GType
contacts_typecombo_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsTypeComboClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_typecombo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsTypeCombo), 0, (GInstanceInitFunc) contacts_typecombo_instance_init, NULL };
	GType contacts_typecombo_type_id;
	contacts_typecombo_type_id = g_type_register_static (gtk_combo_box_get_type (), "ContactsTypeCombo", &g_define_type_info, 0);
	ContactsTypeCombo_private_offset = g_type_add_instance_private (contacts_typecombo_type_id, sizeof (ContactsTypeComboPrivate));
	return contacts_typecombo_type_id;
}

GType
contacts_typecombo_get_type (void)
{
	static volatile gsize contacts_typecombo_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_typecombo_type_id__volatile)) {
		GType contacts_typecombo_type_id;
		contacts_typecombo_type_id = contacts_typecombo_get_type_once ();
		g_once_init_leave (&contacts_typecombo_type_id__volatile, contacts_typecombo_type_id);
	}
	return contacts_typecombo_type_id__volatile;
}

static void
_vala_contacts_typecombo_get_property (GObject * object,
                                       guint property_id,
                                       GValue * value,
                                       GParamSpec * pspec)
{
	ContactsTypeCombo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CONTACTS_TYPE_TYPECOMBO, ContactsTypeCombo);
#line 28 "../src/contacts-type-combo.vala"
	switch (property_id) {
#line 28 "../src/contacts-type-combo.vala"
		case CONTACTS_TYPECOMBO_ACTIVE_DESCRIPTOR_PROPERTY:
#line 28 "../src/contacts-type-combo.vala"
		g_value_set_object (value, contacts_typecombo_get_active_descriptor (self));
#line 28 "../src/contacts-type-combo.vala"
		break;
#line 438 "contacts-type-combo.c"
		default:
#line 28 "../src/contacts-type-combo.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "../src/contacts-type-combo.vala"
		break;
#line 444 "contacts-type-combo.c"
	}
}

static void
_vala_contacts_typecombo_set_property (GObject * object,
                                       guint property_id,
                                       const GValue * value,
                                       GParamSpec * pspec)
{
	ContactsTypeCombo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CONTACTS_TYPE_TYPECOMBO, ContactsTypeCombo);
#line 28 "../src/contacts-type-combo.vala"
	switch (property_id) {
#line 28 "../src/contacts-type-combo.vala"
		case CONTACTS_TYPECOMBO_ACTIVE_DESCRIPTOR_PROPERTY:
#line 28 "../src/contacts-type-combo.vala"
		contacts_typecombo_set_active_descriptor (self, g_value_get_object (value));
#line 28 "../src/contacts-type-combo.vala"
		break;
#line 464 "contacts-type-combo.c"
		default:
#line 28 "../src/contacts-type-combo.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "../src/contacts-type-combo.vala"
		break;
#line 470 "contacts-type-combo.c"
	}
}

