/* contacts-contact-form.c generated by valac 0.47.2.1-ce69, the Vala compiler
 * generated from contacts-contact-form.vala, do not modify */

/*
 * Copyright (C) 2018 Niels De Graef <nielsdegraef@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <folks/folks.h>
#include "contacts.h"
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>

#define CONTACTS_TYPE_CONTACT_FORM (contacts_contact_form_get_type ())
#define CONTACTS_CONTACT_FORM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CONTACTS_TYPE_CONTACT_FORM, ContactsContactForm))
#define CONTACTS_CONTACT_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CONTACTS_TYPE_CONTACT_FORM, ContactsContactFormClass))
#define CONTACTS_IS_CONTACT_FORM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CONTACTS_TYPE_CONTACT_FORM))
#define CONTACTS_IS_CONTACT_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CONTACTS_TYPE_CONTACT_FORM))
#define CONTACTS_CONTACT_FORM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CONTACTS_TYPE_CONTACT_FORM, ContactsContactFormClass))

typedef struct _ContactsContactForm ContactsContactForm;
typedef struct _ContactsContactFormClass ContactsContactFormClass;
typedef struct _ContactsContactFormPrivate ContactsContactFormPrivate;
enum  {
	CONTACTS_CONTACT_FORM_0_PROPERTY,
	CONTACTS_CONTACT_FORM_NUM_PROPERTIES
};
static GParamSpec* contacts_contact_form_properties[CONTACTS_CONTACT_FORM_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ContactsContactForm {
	GtkGrid parent_instance;
	ContactsContactFormPrivate * priv;
	FolksIndividual* individual;
	ContactsStore* store;
	GtkGrid* container_grid;
	gint last_row;
};

struct _ContactsContactFormClass {
	GtkGridClass parent_class;
};

struct _ContactsContactFormPrivate {
	GtkScrolledWindow* main_sw;
};

static gint ContactsContactForm_private_offset;
static gpointer contacts_contact_form_parent_class = NULL;

GType contacts_contact_form_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ContactsContactForm, g_object_unref)
gchar** contacts_contact_form_sort_persona_properties (ContactsContactForm* self,
                                                       gchar** props,
                                                       gint props_length1,
                                                       gint* result_length1);
static gint __lambda10_ (ContactsContactForm* self,
                  const gchar* a,
                  const gchar* b);
static gint ___lambda10__gcompare_data_func (gconstpointer a,
                                      gconstpointer b,
                                      gpointer self);
GtkLabel* contacts_contact_form_create_persona_store_label (ContactsContactForm* self,
                                                            FolksPersona* p);
ContactsContactForm* contacts_contact_form_construct (GType object_type);
static GObject * contacts_contact_form_constructor (GType type,
                                             guint n_construct_properties,
                                             GObjectConstructParam * construct_properties);
static void contacts_contact_form_finalize (GObject * obj);
static GType contacts_contact_form_get_type_once (void);

const gchar* CONTACTS_CONTACT_FORM_SORTED_PROPERTIES[8] = {"email-addresses", "phone-numbers", "im-addresses", "urls", "nickname", "birthday", "postal-addresses", "notes"};

static inline gpointer
contacts_contact_form_get_instance_private (ContactsContactForm* self)
{
	return G_STRUCT_MEMBER_P (self, ContactsContactForm_private_offset);
}

static gint
__lambda10_ (ContactsContactForm* self,
             const gchar* a,
             const gchar* b)
{
	gint result = 0;
#line 60 "../src/contacts-contact-form.vala"
	g_return_val_if_fail (a != NULL, 0);
#line 60 "../src/contacts-contact-form.vala"
	g_return_val_if_fail (b != NULL, 0);
#line 108 "contacts-contact-form.c"
	{
		const gchar** prop_collection = NULL;
		gint prop_collection_length1 = 0;
		gint _prop_collection_size_ = 0;
		gint prop_it = 0;
#line 61 "../src/contacts-contact-form.vala"
		prop_collection = CONTACTS_CONTACT_FORM_SORTED_PROPERTIES;
#line 61 "../src/contacts-contact-form.vala"
		prop_collection_length1 = G_N_ELEMENTS (CONTACTS_CONTACT_FORM_SORTED_PROPERTIES);
#line 61 "../src/contacts-contact-form.vala"
		for (prop_it = 0; prop_it < prop_collection_length1; prop_it = prop_it + 1) {
#line 120 "contacts-contact-form.c"
			const gchar* prop = NULL;
#line 61 "../src/contacts-contact-form.vala"
			prop = prop_collection[prop_it];
#line 124 "contacts-contact-form.c"
			{
				const gchar* _tmp0_;
				const gchar* _tmp3_;
#line 62 "../src/contacts-contact-form.vala"
				_tmp0_ = prop;
#line 62 "../src/contacts-contact-form.vala"
				if (g_strcmp0 (a, _tmp0_) == 0) {
#line 132 "contacts-contact-form.c"
					gint _tmp1_ = 0;
					const gchar* _tmp2_;
#line 63 "../src/contacts-contact-form.vala"
					_tmp2_ = prop;
#line 63 "../src/contacts-contact-form.vala"
					if (g_strcmp0 (b, _tmp2_) == 0) {
#line 63 "../src/contacts-contact-form.vala"
						_tmp1_ = 0;
#line 141 "contacts-contact-form.c"
					} else {
#line 63 "../src/contacts-contact-form.vala"
						_tmp1_ = -1;
#line 145 "contacts-contact-form.c"
					}
#line 63 "../src/contacts-contact-form.vala"
					result = _tmp1_;
#line 63 "../src/contacts-contact-form.vala"
					return result;
#line 151 "contacts-contact-form.c"
				}
#line 65 "../src/contacts-contact-form.vala"
				_tmp3_ = prop;
#line 65 "../src/contacts-contact-form.vala"
				if (g_strcmp0 (b, _tmp3_) == 0) {
#line 66 "../src/contacts-contact-form.vala"
					result = 1;
#line 66 "../src/contacts-contact-form.vala"
					return result;
#line 161 "contacts-contact-form.c"
				}
			}
		}
	}
#line 69 "../src/contacts-contact-form.vala"
	result = 0;
#line 69 "../src/contacts-contact-form.vala"
	return result;
#line 170 "contacts-contact-form.c"
}

static gint
___lambda10__gcompare_data_func (gconstpointer a,
                                 gconstpointer b,
                                 gpointer self)
{
	gint result;
	result = __lambda10_ ((ContactsContactForm*) self, (const gchar*) a, (const gchar*) b);
#line 60 "../src/contacts-contact-form.vala"
	return result;
#line 182 "contacts-contact-form.c"
}

gchar**
contacts_contact_form_sort_persona_properties (ContactsContactForm* self,
                                               gchar** props,
                                               gint props_length1,
                                               gint* result_length1)
{
	GCompareDataFunc compare_properties = NULL;
	gpointer compare_properties_target;
	GDestroyNotify compare_properties_target_destroy_notify;
	GeeArrayList* sorted_props = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp4_;
	GCompareDataFunc _tmp5_;
	gpointer _tmp5__target;
	GDestroyNotify _tmp5__target_destroy_notify;
	GeeArrayList* _tmp6_;
	gint _tmp7_ = 0;
	gpointer* _tmp8_;
	gchar** _tmp9_;
	gint _tmp9__length1;
	gchar** result = NULL;
#line 59 "../src/contacts-contact-form.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 60 "../src/contacts-contact-form.vala"
	compare_properties = ___lambda10__gcompare_data_func;
#line 60 "../src/contacts-contact-form.vala"
	compare_properties_target = g_object_ref (self);
#line 60 "../src/contacts-contact-form.vala"
	compare_properties_target_destroy_notify = g_object_unref;
#line 72 "../src/contacts-contact-form.vala"
	_tmp0_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL);
#line 72 "../src/contacts-contact-form.vala"
	sorted_props = _tmp0_;
#line 218 "contacts-contact-form.c"
	{
		gchar** s_collection = NULL;
		gint s_collection_length1 = 0;
		gint _s_collection_size_ = 0;
		gint s_it = 0;
#line 73 "../src/contacts-contact-form.vala"
		s_collection = props;
#line 73 "../src/contacts-contact-form.vala"
		s_collection_length1 = props_length1;
#line 73 "../src/contacts-contact-form.vala"
		for (s_it = 0; s_it < s_collection_length1; s_it = s_it + 1) {
#line 230 "contacts-contact-form.c"
			gchar* _tmp1_;
			gchar* s = NULL;
#line 73 "../src/contacts-contact-form.vala"
			_tmp1_ = g_strdup (s_collection[s_it]);
#line 73 "../src/contacts-contact-form.vala"
			s = _tmp1_;
#line 237 "contacts-contact-form.c"
			{
				GeeArrayList* _tmp2_;
				const gchar* _tmp3_;
#line 74 "../src/contacts-contact-form.vala"
				_tmp2_ = sorted_props;
#line 74 "../src/contacts-contact-form.vala"
				_tmp3_ = s;
#line 74 "../src/contacts-contact-form.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp2_, _tmp3_);
#line 73 "../src/contacts-contact-form.vala"
				_g_free0 (s);
#line 249 "contacts-contact-form.c"
			}
		}
	}
#line 76 "../src/contacts-contact-form.vala"
	_tmp4_ = sorted_props;
#line 76 "../src/contacts-contact-form.vala"
	_tmp5_ = compare_properties;
#line 76 "../src/contacts-contact-form.vala"
	_tmp5__target = compare_properties_target;
#line 76 "../src/contacts-contact-form.vala"
	_tmp5__target_destroy_notify = compare_properties_target_destroy_notify;
#line 76 "../src/contacts-contact-form.vala"
	compare_properties = NULL;
#line 76 "../src/contacts-contact-form.vala"
	compare_properties_target = NULL;
#line 76 "../src/contacts-contact-form.vala"
	compare_properties_target_destroy_notify = NULL;
#line 76 "../src/contacts-contact-form.vala"
	gee_list_sort ((GeeList*) _tmp4_, _tmp5_, _tmp5__target, _tmp5__target_destroy_notify);
#line 77 "../src/contacts-contact-form.vala"
	_tmp6_ = sorted_props;
#line 77 "../src/contacts-contact-form.vala"
	_tmp8_ = gee_collection_to_array ((GeeCollection*) _tmp6_, &_tmp7_);
#line 77 "../src/contacts-contact-form.vala"
	_tmp9_ = _tmp8_;
#line 77 "../src/contacts-contact-form.vala"
	_tmp9__length1 = _tmp7_;
#line 77 "../src/contacts-contact-form.vala"
	if (result_length1) {
#line 77 "../src/contacts-contact-form.vala"
		*result_length1 = _tmp9__length1;
#line 281 "contacts-contact-form.c"
	}
#line 77 "../src/contacts-contact-form.vala"
	result = _tmp9_;
#line 77 "../src/contacts-contact-form.vala"
	_g_object_unref0 (sorted_props);
#line 77 "../src/contacts-contact-form.vala"
	(compare_properties_target_destroy_notify == NULL) ? NULL : (compare_properties_target_destroy_notify (compare_properties_target), NULL);
#line 77 "../src/contacts-contact-form.vala"
	compare_properties = NULL;
#line 77 "../src/contacts-contact-form.vala"
	compare_properties_target = NULL;
#line 77 "../src/contacts-contact-form.vala"
	compare_properties_target_destroy_notify = NULL;
#line 77 "../src/contacts-contact-form.vala"
	return result;
#line 297 "contacts-contact-form.c"
}

GtkLabel*
contacts_contact_form_create_persona_store_label (ContactsContactForm* self,
                                                  FolksPersona* p)
{
	GtkLabel* store_name = NULL;
	GtkLabel* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	GtkLabel* result = NULL;
#line 80 "../src/contacts-contact-form.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 80 "../src/contacts-contact-form.vala"
	g_return_val_if_fail (p != NULL, NULL);
#line 81 "../src/contacts-contact-form.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new ("");
#line 81 "../src/contacts-contact-form.vala"
	g_object_ref_sink (_tmp0_);
#line 81 "../src/contacts-contact-form.vala"
	store_name = _tmp0_;
#line 82 "../src/contacts-contact-form.vala"
	_tmp1_ = contacts_utils_format_persona_store_name_for_contact (p);
#line 82 "../src/contacts-contact-form.vala"
	_tmp2_ = _tmp1_;
#line 82 "../src/contacts-contact-form.vala"
	_tmp3_ = g_markup_printf_escaped ("<span font='16px bold'>%s</span>", _tmp2_);
#line 82 "../src/contacts-contact-form.vala"
	_tmp4_ = _tmp3_;
#line 82 "../src/contacts-contact-form.vala"
	gtk_label_set_markup (store_name, _tmp4_);
#line 82 "../src/contacts-contact-form.vala"
	_g_free0 (_tmp4_);
#line 82 "../src/contacts-contact-form.vala"
	_g_free0 (_tmp2_);
#line 84 "../src/contacts-contact-form.vala"
	gtk_widget_set_halign ((GtkWidget*) store_name, GTK_ALIGN_START);
#line 85 "../src/contacts-contact-form.vala"
	gtk_label_set_xalign (store_name, 0.0f);
#line 86 "../src/contacts-contact-form.vala"
	gtk_widget_set_margin_start ((GtkWidget*) store_name, 6);
#line 88 "../src/contacts-contact-form.vala"
	result = store_name;
#line 88 "../src/contacts-contact-form.vala"
	return result;
#line 345 "contacts-contact-form.c"
}

ContactsContactForm*
contacts_contact_form_construct (GType object_type)
{
	ContactsContactForm * self = NULL;
#line 30 "../src/contacts-contact-form.vala"
	self = (ContactsContactForm*) g_object_new (object_type, NULL);
#line 30 "../src/contacts-contact-form.vala"
	return self;
#line 356 "contacts-contact-form.c"
}

static GObject *
contacts_contact_form_constructor (GType type,
                                   guint n_construct_properties,
                                   GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	ContactsContactForm * self;
	GtkGrid* _tmp0_;
	GtkScrolledWindow* _tmp1_;
	GtkAdjustment* _tmp2_;
	GtkScrolledWindow* _tmp3_;
	GtkStyleContext* _tmp4_;
#line 54 "../src/contacts-contact-form.vala"
	parent_class = G_OBJECT_CLASS (contacts_contact_form_parent_class);
#line 54 "../src/contacts-contact-form.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 54 "../src/contacts-contact-form.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_CONTACT_FORM, ContactsContactForm);
#line 55 "../src/contacts-contact-form.vala"
	_tmp0_ = self->container_grid;
#line 55 "../src/contacts-contact-form.vala"
	_tmp1_ = self->priv->main_sw;
#line 55 "../src/contacts-contact-form.vala"
	_tmp2_ = gtk_scrolled_window_get_vadjustment (_tmp1_);
#line 55 "../src/contacts-contact-form.vala"
	gtk_container_set_focus_vadjustment ((GtkContainer*) _tmp0_, _tmp2_);
#line 56 "../src/contacts-contact-form.vala"
	_tmp3_ = self->priv->main_sw;
#line 56 "../src/contacts-contact-form.vala"
	_tmp4_ = gtk_widget_get_style_context ((GtkWidget*) _tmp3_);
#line 56 "../src/contacts-contact-form.vala"
	gtk_style_context_add_class (_tmp4_, "contacts-contact-form");
#line 54 "../src/contacts-contact-form.vala"
	return obj;
#line 394 "contacts-contact-form.c"
}

static void
contacts_contact_form_class_init (ContactsContactFormClass * klass,
                                  gpointer klass_data)
{
#line 30 "../src/contacts-contact-form.vala"
	contacts_contact_form_parent_class = g_type_class_peek_parent (klass);
#line 30 "../src/contacts-contact-form.vala"
	g_type_class_adjust_private_offset (klass, &ContactsContactForm_private_offset);
#line 30 "../src/contacts-contact-form.vala"
	G_OBJECT_CLASS (klass)->constructor = contacts_contact_form_constructor;
#line 30 "../src/contacts-contact-form.vala"
	G_OBJECT_CLASS (klass)->finalize = contacts_contact_form_finalize;
#line 30 "../src/contacts-contact-form.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gnome/Contacts/ui/contacts-contact-form.ui");
#line 30 "../src/contacts-contact-form.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "main_sw", FALSE, ContactsContactForm_private_offset + G_STRUCT_OFFSET (ContactsContactFormPrivate, main_sw));
#line 30 "../src/contacts-contact-form.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "container_grid", FALSE, G_STRUCT_OFFSET (ContactsContactForm, container_grid));
#line 415 "contacts-contact-form.c"
}

static void
contacts_contact_form_instance_init (ContactsContactForm * self,
                                     gpointer klass)
{
#line 30 "../src/contacts-contact-form.vala"
	self->priv = contacts_contact_form_get_instance_private (self);
#line 52 "../src/contacts-contact-form.vala"
	self->last_row = 0;
#line 30 "../src/contacts-contact-form.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 428 "contacts-contact-form.c"
}

static void
contacts_contact_form_finalize (GObject * obj)
{
	ContactsContactForm * self;
#line 30 "../src/contacts-contact-form.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CONTACTS_TYPE_CONTACT_FORM, ContactsContactForm);
#line 43 "../src/contacts-contact-form.vala"
	_g_object_unref0 (self->individual);
#line 45 "../src/contacts-contact-form.vala"
	_g_object_unref0 (self->store);
#line 48 "../src/contacts-contact-form.vala"
	_g_object_unref0 (self->priv->main_sw);
#line 51 "../src/contacts-contact-form.vala"
	_g_object_unref0 (self->container_grid);
#line 30 "../src/contacts-contact-form.vala"
	G_OBJECT_CLASS (contacts_contact_form_parent_class)->finalize (obj);
#line 447 "contacts-contact-form.c"
}

/**
 * A parent class for the {@link ContactEditor} and the {@link ContactSheet}.
 *
 * This exploits the common structure of both widgets: they both display a
 * (possibly empty) contact, starting with a header and subsequently iterating
 * over the several {@link Folks.Persona}s, displaying their properties.
 */
static GType
contacts_contact_form_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ContactsContactFormClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) contacts_contact_form_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ContactsContactForm), 0, (GInstanceInitFunc) contacts_contact_form_instance_init, NULL };
	GType contacts_contact_form_type_id;
	contacts_contact_form_type_id = g_type_register_static (gtk_grid_get_type (), "ContactsContactForm", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	ContactsContactForm_private_offset = g_type_add_instance_private (contacts_contact_form_type_id, sizeof (ContactsContactFormPrivate));
	return contacts_contact_form_type_id;
}

GType
contacts_contact_form_get_type (void)
{
	static volatile gsize contacts_contact_form_type_id__volatile = 0;
	if (g_once_init_enter (&contacts_contact_form_type_id__volatile)) {
		GType contacts_contact_form_type_id;
		contacts_contact_form_type_id = contacts_contact_form_get_type_once ();
		g_once_init_leave (&contacts_contact_form_type_id__volatile, contacts_contact_form_type_id);
	}
	return contacts_contact_form_type_id__volatile;
}

